// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/core/workers/JobProxy","require exports dojo/_base/kernel dojo/_base/url dojo/Deferred ../../kernel ../../config ../../request ../urlUtils".split(" "),function(n,y,r,s,p,t,k,u,g){function v(){if(!w){var b=new p,a=new Worker(l);a.onerror=function(a){a.preventDefault()};b.resolve(a);return b.promise}m||(b=new s(l),k.defaults?k.defaults.io.corsEnabledServers.push(b.host):k.request.corsEnabledServers.push(b.host),m=u(l,{responseType:"text"}));return m.then(function(a){a=
new Worker(URL.createObjectURL(new Blob([a.data],{type:"text/javascript"})));a.onerror=function(a){a.preventDefault()};return a})}var l=g.makeAbsolute(n.toUrl("./worker.js")),q=g.makeAbsolute(n.toUrl("./worker-init.js")),x=g.makeAbsolute("../../../../../../",q)+"/",w=!g.hasSameOrigin(l,location.href),m=null;return function(){function b(a,b,e){var c=this;this.connections=a;this.index=b;this.workerInitCallback=e;this.msgCount=0;this.outgoingJobs={};this.incomingJobs={};this.incomingStaticJobs={};v().then(function(a){c.worker=
a;c.worker.addEventListener("message",c.message.bind(c),!1)})}b.prototype.terminate=function(){this.worker.terminate()};b.prototype.openConnection=function(a,b){return this.invoke("\x3copen-connection\x3e",{path:a},void 0,b)};b.prototype.closeConnection=function(a){this.invoke("\x3cclose-connection\x3e",void 0,void 0,a)};b.prototype.postConfigMessage=function(a){a=JSON.parse(JSON.stringify(a));this.worker.postMessage({type:"\x3cconfigure\x3e",configure:{esriConfig:a,dojoConfig:{async:!0,baseUrl:x,
locale:r.locale,has:{"esri-cors":1,"dojo-test-sniff":0,"config-deferredInstrumentation":0},paths:{esri:"esri",dojo:"dojo",dojox:"dojox",dstore:"dstore",moment:"moment"}},loaderUrl:q}})};b.prototype.invoke=function(a,b,e,c){var d=this,f=++this.msgCount,h=new p(function(a){d.worker.postMessage({type:"\x3ccancel\x3e",id:f,connection:c,data:{reason:a}});d.outgoingJobs[f]&&delete d.outgoingJobs[f]});this.outgoingJobs[f]=h;this.worker.postMessage({type:a,id:f,connection:c,data:b},e);return h.promise};b.prototype.message=
function(a){var b=this;if(a&&a.data){var e=a.data.type;if(e){var c=a.data,d=a.data.id;if("\x3cresponse\x3e"===e&&d){if(a=this.outgoingJobs[d])delete this.outgoingJobs[d],c.error?a.reject(c.error):a.resolve(c.data)}else if("\x3cworker-loaded\x3e"===e)this.postConfigMessage(k);else if("\x3cworker-configured\x3e"===e)this.workerInitCallback&&("function"===typeof this.workerInitCallback&&"number"===typeof this.index)&&this.workerInitCallback(this.index);else if("\x3ccancel\x3e"===e&&d)(a=this.incomingJobs[d])&&
a.cancel(c.data.reason),c.staticMsg&&(a=this.incomingStaticJobs[d])&&a.cancel(c.data.reason);else if("\x3cstatic-message\x3e"===e){var f=c.staticMsg;a=t.workerMessages[f];!a||"function"!==typeof a?this.worker.postMessage({type:"\x3cstatic-message\x3e",staticMsg:f,id:d,error:a+" message type is not available on the kernel!"}):(c=a.call(this,c.data),this.incomingStaticJobs[d]=c,c.then(function(a){b.worker.postMessage({type:"\x3cstatic-message\x3e",staticMsg:f,id:d,data:a.data},a.buffers)}).otherwise(function(a){a||
(a="Error encountered at method"+f);(!a.dojoType||"cancel"!==a.dojoType)&&b.worker.postMessage({type:"\x3cstatic-message\x3e",staticMsg:f,id:d,error:a})}).always(function(){delete b.incomingStaticJobs[d]}))}else{var h=c.connection;if(a=this.connections[h])if(a=a.client){var g=a[e];"function"===typeof g&&(c=g.call(a,c.data),this.incomingJobs[d]=c,c.then(function(a){b.worker.postMessage({type:"\x3cresponse\x3e",id:d,connection:h,error:a.error,data:a.data},a.buffers)}).otherwise(function(a){a||(a="Error encountered at method"+
e);(!a.dojoType||"cancel"!==a.dojoType)&&b.worker.postMessage({type:"\x3cresponse\x3e",id:d,connection:h,error:a})}).always(function(){delete b.incomingJobs[d]}))}}}}};return b}()});