// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
define("esri/layers/BaseRasterLayer","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/_base/array dojo/sniff dojo/dom-construct dojo/dom-style ../lang ../domUtils ../geometry/Point ./layer".split(" "),function(l,m,c,n,p,q,f,r,g,s,t){return l([t],{declaredClass:"esri.layers.BaseRasterLayer",managedSuspension:!0,opacity:1,constructor:function(a,b){this.drawMode=b&&void 0!==b.drawMode?b.drawMode:!0;this.drawType=b&&b.drawType?b.drawType:"2d";this.pixelData=null;this._initialize(a,b)},setDrawMode:function(a){this.drawMode=
a},setOpacity:function(a){this.opacity!==a&&(this.opacity=a,this.onOpacityChange(a))},onOpacityChange:function(){},refresh:function(){if(!this._canDraw()||10>p("ie"))this.onError(Error("Unable to refresh. This layer is not supported in the current browser."));else this._map&&this._extentChangeHandler(this._map.extent)},clear:function(){this._canDraw()&&"2d"===this.drawType&&this._context.clearRect(0,0,this._mapWidth,this._mapHeight)},getContext:function(){return this._context},onResume:function(){this.inherited(arguments);
this._toggleTime();this._displayTimer=this._displayTimer||setTimeout(m.hitch(this,function(){this._extentChangeHandler(this._map.extent,null,!0)}),0)},onSuspend:function(){this.inherited(arguments);this._toggleTime();clearTimeout(this._displayTimer);this._displayTimer=null},redraw:function(){this.hasDataChanged=!1;this._setPixelData(this.originalPixelData)},getCurrentResolution:function(){var a=this._map.extent;return new s((a.xmax-a.xmin)/this._map.width,(a.ymax-a.ymin)/this._map.height,a.spatialReference)},
setPixelFilter:function(a,b){this.pixelFilter=a;b||this.redraw()},_toggleTime:function(){},_setMap:function(a,b){this.inherited(arguments);var e=this._canvas=q.create("canvas",{id:"canvas",width:a.width+"px",height:a.height+"px",style:"position: absolute; left: 0px; top: 0px;"},b);r.isDefined(this.opacity)&&f.set(e,"opacity",this.opacity);(this._context=e.getContext(this.drawType))||console.error("Unable to create the context. This browser might not support \x3ccanvas\x3e elements.");this._mapWidth=
a.width;this._mapHeight=a.height;this._connects=[];this._connects.push(c.connect(a,"onPan",this,this._panHandler));this._connects.push(c.connect(a,"onPanEnd",this,this._panEndHandler));this._connects.push(c.connect(a,"onZoom",this,this._onZoomHandler));this._connects.push(c.connect(a,"onZoomEnd",this,this._onZoomEndHandler));this._connects.push(c.connect(a,"onResize",this,this._onResizeHandler));this._connects.push(c.connect(a,"onExtentChange",this,this._extentChangeHandler));this._connects.push(c.connect(this,
"onVisibilityChange",this,this._visibilityChangeHandler));this._connects.push(c.connect(this,"onOpacityChange",this,this._opacityChangeHandler));this._startRect={left:0,top:0,width:a.width,height:a.height};this.evaluateSuspension();if(this.suspended&&!a.loaded)var d=c.connect(a,"onLoad",this,function(){c.disconnect(d);d=null;this.evaluateSuspension()});return e},_unsetMap:function(a,b){n.forEach(this._connects,c.disconnect,this);this._canvas&&b.removeChild(this._canvas);this._map=this._canvas=this._context=
this.data=this._connects=null;clearTimeout(this._displayTimer);this._displayTimer=null;this.inherited(arguments)},_canDraw:function(){return!(!this._map||!this._canvas||!this._context)},_requestDataErrorHandler:function(a){"CancelError"!==a.name&&(this.clear(),this.onError(a))},_drawPixelData:function(){f.set(this._canvas,{left:"0px",top:"0px",width:this._map.width+"px",height:this._map.height+"px"});this._startRect={left:0,top:0,width:this._map.width,height:this._map.height};if(this._canDraw&&this.drawMode)if(this._useBrowserDecoding())this._fireUpdateEnd();
else if(this.drawMode)if(!this.pixelData||!this.pixelData.pixelBlock)this.clear();else{var a=this.pixelData.pixelBlock,b=this._context,e=b.createImageData(a.width,a.height);e.data.set(a.getAsRGBA());var d=this.pixelData.extent,c=this._map.extent,h=this.getCurrentResolution(),g=0,k=0;Math.abs(d.xmin-c.xmin)>h.x&&(g=Math.round((d.xmin-c.xmin)/h.x));Math.abs(c.ymax-d.ymax)>h.y&&(k=Math.round((c.ymax-d.ymax)/h.y));this.clear();b.putImageData(e,g,k,0,0,a.width,a.height);this._fireUpdateEnd()}},_panHandler:function(a,
b){f.set(this._canvas,{left:this._startRect.left+b.x+"px",top:this._startRect.top+b.y+"px"})},_panEndHandler:function(a,b){b&&(this._startRect.left+=b.x,this._startRect.top+=b.y)},_onZoomHandler:function(a,b,e){var d=this._startRect;a=d.width*b;b*=d.height;var c=d.left-(a-d.width)*(e.x-d.left)/d.width;e=d.top-(b-d.height)*(e.y-d.top)/d.height;f.set(this._canvas,{left:c+"px",top:e+"px",width:a+"px",height:b+"px"});this._endRect={left:c,top:e,width:a,height:b}},_onZoomEndHandler:function(){this._endRect&&
(this._startRect=this._endRect)},_onResizeHandler:function(a,b,c){f.set(this._canvas,{width:b+"px",height:c+"px"});this._startRect.width=this._canvas.width=b;this._startRect.height=this._canvas.height=c},_extentChangeHandler:function(a,b,c,d){if(!this.suspended&&(!b||!(0===b.x&&0===b.y&&!c)))this._fireUpdateStart(),a=this._map,this._requestData(a.extent,a.width,a.height)},_visibilityChangeHandler:function(a){a?g.show(this._canvas):g.hide(this._canvas)},_opacityChangeHandler:function(a){f.set(this._canvas,
"opacity",a)}})});