// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
require({cache:{"esri/PopupInfo":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/json dojo/i18n dojo/has dojo/Deferred dojo/sniff dojo/promise/all ./lang ./kernel ./request ./tasks/query ./tasks/QueryTask ./tasks/StatisticDefinition dojo/i18n!dojo/cldr/nls/number".split(" "),function(B,z,A,E,F,G,k,b,a,f,g,e,d,c,h,l){B=B(null,{declaredClass:"esri.PopupInfo",initialize:function(a,c){if(a){z.mixin(this,c);this.info=a;this.title=this.getTitle;this.content=this.getContent;
var f=this._fieldLabels={},d=this._fieldsMap={};a.fieldInfos&&A.forEach(a.fieldInfos,function(a){var c=a.fieldName.toLowerCase();f[c]=a.label;d[c]=a});this._relatedFieldPrefix="relationships/";this.titleHasRelatedFields=!!(a.title&&-1!==a.title.indexOf("{"+this._relatedFieldPrefix))}},toJson:function(){return E.fromJson(E.toJson(this.info))},getTitle:function(){},getContent:function(){},getFieldInfo:function(a){var c;A.some(this.info&&this.info.fieldInfos,function(f){f.fieldName===a&&(c=f);return!!c});
return c},getComponents:function(a){var c=this.info,f=new k,d,b;c.fieldInfos&&(b=A.filter(c.fieldInfos,function(a){return-1!==a.fieldName.indexOf(this._relatedFieldPrefix)},this));b&&0<b.length&&(d=this._getRelatedRecords({graphic:a,fieldsInfo:b}));d?d.always(z.hitch(this,function(){f.resolve(this._getPopupValues(a))})):f.resolve(this._getPopupValues(a));return f.promise},getAttachments:function(a){var c=a.getLayer();a=a.attributes;if(this.info.showAttachments&&(c&&c.hasAttachments&&c.objectIdField)&&
(a=a&&a[c.objectIdField]))return c.queryAttachmentInfos(a)},_getPopupValues:function(a,c){var d=this.info,b=a.getLayer(),e=z.clone(a.attributes)||{},h=z.clone(e),l=d.fieldInfos,g="",n="",y,t,w,k,D,I=b&&b._getDateOpts&&b._getDateOpts().properties,I=I&&I.slice(0),H={dateFormat:{properties:I,formatter:"DateFormat"+this._insertOffset(this._dateFormats.shortDateShortTime)}};if(this._relatedInfo)for(k in this._relatedInfo)if(this._relatedInfo.hasOwnProperty(k)){var J=this._relatedInfo[k],B=this._relatedLayersInfo[k];
J&&(A.forEach(J.relatedFeatures,function(a){for(D in a.attributes)if(a.attributes.hasOwnProperty(D)&&"esriRelCardinalityOneToOne"===B.relation.cardinality){var n=this._toRelatedFieldName([B.relation.id,D]);e[n]=h[n]=a.attributes[D]}},this),A.forEach(J.relatedStatsFeatures,function(a){for(D in a.attributes)if(a.attributes.hasOwnProperty(D)){var n=this._toRelatedFieldName([B.relation.id,D]);e[n]=h[n]=a.attributes[D]}},this))}l&&A.forEach(l,function(a){t=a.fieldName;var n=this._getLayerFieldInfo(b,t);
n&&(t=a.fieldName=n.name);h[t]=this._formatValue(h[t],t,H);I&&(a.format&&a.format.dateFormat)&&(a=A.indexOf(I,t),-1<a&&I.splice(a,1))},this);if(b){k=b.types;var F=(J=b.typeIdField)&&e[J];for(t in e)if(e.hasOwnProperty(t)&&-1===t.indexOf(this._relatedFieldPrefix)&&(w=e[t],f.isDefined(w))){var E=this._getDomainName(b,a,k,F,t,w);f.isDefined(E)?h[t]=E:t===J&&(E=this._getTypeName(b,a,w),f.isDefined(E)&&(h[t]=E))}}d.title&&(g=this._processFieldsInLinks(this._fixTokens(d.title,b),e),g=z.trim(f.substitute(h,
g,H)||""));if(c)return{title:g};d.description&&(n=this._processFieldsInLinks(this._fixTokens(d.description,b),e),n=z.trim(f.substitute(h,n,H)||""));l&&(y=[],A.forEach(l,function(a){(t=a.fieldName)&&a.visible&&y.push([a.label||t,f.substitute(h,"${"+t+"}",H)||""])}));var G,K;d.mediaInfos&&(G=[],A.forEach(d.mediaInfos,function(a){K=0;w=a.value;switch(a.type){case "image":var n=w.sourceURL,n=n&&z.trim(f.substitute(e,this._fixTokens(n,b)));K=!!n;break;case "piechart":case "linechart":case "columnchart":case "barchart":var c,
n=w.normalizeField;w.fields=A.map(w.fields,function(a){return(c=this._getLayerFieldInfo(b,a))?c.name:a},this);n&&(c=this._getLayerFieldInfo(b,n),w.normalizeField=c?c.name:n);K=A.some(w.fields,function(a){return f.isDefined(e[a])||-1!==a.indexOf(this._relatedFieldPrefix)&&this._relatedInfo},this);break;default:return}if(K){a=z.clone(a);w=a.value;var n=a.title?this._processFieldsInLinks(this._fixTokens(a.title,b),e):"",d=a.caption?this._processFieldsInLinks(this._fixTokens(a.caption,b),e):"";a.title=
n?z.trim(f.substitute(h,n,H)||""):"";a.caption=d?z.trim(f.substitute(h,d,H)||""):"";if("image"===a.type)w.sourceURL=f.substitute(e,this._fixTokens(w.sourceURL,b)),w.linkURL&&(w.linkURL=z.trim(f.substitute(e,this._fixTokens(w.linkURL,b))||""));else{var p,v;A.forEach(w.fields,function(a,n){if(-1!==a.indexOf(this._relatedFieldPrefix))v=this._getRelatedChartInfos(a,w,e,H),v instanceof Array?w.fields=v:w.fields[n]=v;else{var c=e[a],c=void 0===c?null:c;p=e[w.normalizeField]||0;c&&p&&(c/=p);w.fields[n]=
{y:c,tooltip:(this._fieldLabels[a.toLowerCase()]||a)+":\x3cbr/\x3e"+this._formatValue(c,a,H,!!p)}}},this)}G.push(a)}},this));return{title:g,description:n,hasDescription:!!d.description,fields:y&&y.length?y:null,mediaInfos:G&&G.length?G:null,formatted:h,editSummary:b&&b.getEditSummary?b.getEditSummary(a):""}},_getRelatedChartInfos:function(a,c,f,b){var e,d,h,l,n,g;e=[];g=this._fromRelatedFieldName(a);n=g[0];d=this._relatedInfo[n];n=this._relatedLayersInfo[n];d&&A.forEach(d.relatedFeatures,function(n){n=
n.attributes;var d,q;for(q in n)if(n.hasOwnProperty(q)&&q===g[1]){d={};l=n[q];c.normalizeField&&(h=-1!==c.normalizeField.indexOf(this._relatedFieldPrefix)?n[this._fromRelatedFieldName(c.normalizeField)[1]]:f[c.normalizeField]);l&&h&&(l/=h);if(c.tooltipField)if(-1!==c.tooltipField.indexOf(this._relatedFieldPrefix)){var D=this._fromRelatedFieldName(c.tooltipField)[1];d.tooltip=n[D]&&"string"===typeof n[D]?n[D]+":\x3cbr/\x3e"+this._formatValue(l,n[D],b,!!h):D+":\x3cbr/\x3e"+this._formatValue(l,D,b,!!h)}else d.tooltip=
(this._fieldLabels[a.toLowerCase()]||a)+":\x3cbr/\x3e"+this._formatValue(l,c.tooltipField,b,!!h);else d.tooltip=l;d.y=l;e.push(d)}},this);return"esriRelCardinalityOneToMany"===n.relation.cardinality||"esriRelCardinalityManyToMany"===n.relation.cardinality?e:e[0]},_dateFormats:{shortDate:"(datePattern: 'M/d/y', selector: 'date')",shortDateLE:"(datePattern: 'd/M/y', selector: 'date')",longMonthDayYear:"(datePattern: 'MMMM d, y', selector: 'date')",dayShortMonthYear:"(datePattern: 'd MMM y', selector: 'date')",
longDate:"(datePattern: 'EEEE, MMMM d, y', selector: 'date')",shortDateShortTime:"(datePattern: 'M/d/y', timePattern: 'h:mm a', selector: 'date and time')",shortDateLEShortTime:"(datePattern: 'd/M/y', timePattern: 'h:mm a', selector: 'date and time')",shortDateShortTime24:"(datePattern: 'M/d/y', timePattern: 'H:mm', selector: 'date and time')",shortDateLEShortTime24:"(datePattern: 'd/M/y', timePattern: 'H:mm', selector: 'date and time')",shortDateLongTime:"(datePattern: 'M/d/y', timePattern: 'h:mm:ss a', selector: 'date and time')",
shortDateLELongTime:"(datePattern: 'd/M/y', timePattern: 'h:mm:ss a', selector: 'date and time')",shortDateLongTime24:"(datePattern: 'M/d/y', timePattern: 'H:mm:ss', selector: 'date and time')",shortDateLELongTime24:"(datePattern: 'd/M/y', timePattern: 'H:mm:ss', selector: 'date and time')",longMonthYear:"(datePattern: 'MMMM y', selector: 'date')",shortMonthYear:"(datePattern: 'MMM y', selector: 'date')",year:"(datePattern: 'y', selector: 'date')"},_reHref:/href\s*=\s*\"([^\"]+)\"/ig,_reHrefApos:/href\s*=\s*\'([^\']+)\'/ig,
_fixTokens:function(a,c){var b=this;return a.replace(/(\{([^\{\r\n]+)\})/g,function(a,f,d){a=b._getLayerFieldInfo(c,d);return"$"+(a?"{"+a.name+"}":f)})},_encodeAttributes:function(a){a=z.clone(a)||{};var c,b;for(c in a)if((b=a[c])&&"string"===typeof b)b=encodeURIComponent(b).replace(/\'/g,"\x26apos;"),a[c]=b;return a},_processFieldsInLinks:function(a,c){var b=this._encodeAttributes(c),f=this;a&&(a=a.replace(this._reHref,function(a,d){return f._addValuesToHref(a,d,c,b)}).replace(this._reHrefApos,function(a,
d){return f._addValuesToHref(a,d,c,b)}));return a},_addValuesToHref:function(a,c,b,d){c=c&&z.trim(c);return f.substitute(c&&0===c.indexOf("${")?b:d,a)},_getLayerFieldInfo:function(a,c){return a&&a.getField?a.getField(c):null},_formatValue:function(a,c,b,d){var e=this._fieldsMap[c.toLowerCase()],h=e&&e.format;c=-1!==A.indexOf(b.dateFormat.properties,c);var g="number"===typeof a&&!c&&(!h||!h.dateFormat);if(!f.isDefined(a)||!e||!f.isDefined(h))return g?this._forceLTR(a):a;var k="",e=[],n=h.hasOwnProperty("places")||
h.hasOwnProperty("digitSeparator"),y=h.hasOwnProperty("digitSeparator")?h.digitSeparator:!0;if(n&&!c)k="NumberFormat",e.push("places: "+(f.isDefined(h.places)&&(!d||0<h.places)?Number(h.places):"Infinity")),e.length&&(k+="("+e.join(",")+")");else if(h.dateFormat)k="DateFormat"+this._insertOffset(this._dateFormats[h.dateFormat]||this._dateFormats.shortDateShortTime);else return g?this._forceLTR(a):a;var t=this._applyFormatting(a,k,b);n&&-1<a.constructor.toString().indexOf("Array")&&(t="",A.forEach(a,
z.hitch(this,function(a){t=t+this._applyFormatting(a,k,b)+" "})));n&&!y&&l.group&&(t=t.replace(RegExp("\\"+l.group,"g"),""));c&&(t='\x3cspan class\x3d"esriDateValue"\x3e'+t+"\x3c/span\x3e");return g?this._forceLTR(t):t},_applyFormatting:function(a,c,b){return f.substitute({myKey:a},"${myKey:"+c+"}",b)||""},_forceLTR:function(a){var c=b("ie");return c&&10>=c?a:"\x3cspan class\x3d'esriNumericValue'\x3e"+a+"\x3c/span\x3e"},_insertOffset:function(a){a&&(a=f.isDefined(this.utcOffset)?a.replace(/\)\s*$/,
", utcOffset:"+this.utcOffset+")"):a);return a},_getDomainName:function(a,c,b,d,f,e){return(a=a.getDomain&&a.getDomain(f,{feature:c}))&&a.codedValues?a.getName(e):null},_getTypeName:function(a,c,b){return(a=a.getType&&a.getType(c))&&a.name},_getRelatedRecords:function(a){var c=a.graphic,b=new k,d;this._relatedLayersInfo?this._queryRelatedLayers(c).then(z.hitch(this,function(a){this._setRelatedRecords(c,a);b.resolve(a)}),z.hitch(this,this._handlerErrorResponse,b)):this._getRelatedLayersInfo(a).then(z.hitch(this,
function(a){for(d in a)a.hasOwnProperty(d)&&a[d]&&(this._relatedLayersInfo[d].relatedLayerInfo=a[d]);this._queryRelatedLayers(c).then(z.hitch(this,function(a){this._setRelatedRecords(c,a);b.resolve(a)}),z.hitch(this,this._handlerErrorResponse,b))}),z.hitch(this,this._handlerErrorResponse,b));return b.promise},_getRelatedLayersInfo:function(c){var b=c.fieldsInfo,d,f,l={};d=c.graphic.getLayer();this._relatedLayersInfo||(this._relatedLayersInfo={});A.forEach(b,function(a){var c,b,n,f;c=this._fromRelatedFieldName(a.fieldName);
b=c[0];c=c[1];b&&(this._relatedLayersInfo[b]||(A.some(d.relationships,function(a){if(a.id==b)return f=a,!0}),f&&(this._relatedLayersInfo[b]={relation:f,relatedFields:[],outStatistics:[]})),this._relatedLayersInfo[b]&&(this._relatedLayersInfo[b].relatedFields.push(c),a.statisticType&&(n=new h,n.statisticType=a.statisticType,n.onStatisticField=c,n.outStatisticFieldName=c,this._relatedLayersInfo[b].outStatistics.push(n))))},this);for(f in this._relatedLayersInfo)this._relatedLayersInfo.hasOwnProperty(f)&&
this._relatedLayersInfo[f]&&(c=this._relatedLayersInfo[f].relation,c=d.url.replace(/[0-9]+$/,c.relatedTableId),this._relatedLayersInfo[f].relatedLayerUrl=c,l[f]=e({url:c,content:{f:"json"},callbackParamName:"callback"}));return a(l)},_queryRelatedLayers:function(c){var b={},d;for(d in this._relatedLayersInfo)this._relatedLayersInfo.hasOwnProperty(d)&&(b[d]=this._queryRelatedLayer({graphic:c,relatedInfo:this._relatedLayersInfo[d]}));return a(b)},_queryRelatedLayer:function(b){var f,e,h,l,g,k,u,n,y,
t;f=b.graphic;e=f.getLayer().url.match(/[0-9]+$/g)[0];n=b.relatedInfo;u=n.relatedLayerInfo;y=n.relatedLayerUrl;t=n.relation;A.some(u.relationships,function(a){if(a.relatedTableId===parseInt(e,10))return h=a,!0},this);h&&(b=new d,A.some(u.fields,function(a){if(a.name===h.keyField)return g=-1!==A.indexOf(["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],a.type)?"number":"string",!0}),l="string"===g?h.keyField+"\x3d'"+f.attributes[t.keyField]+"'":h.keyField+
"\x3d"+f.attributes[t.keyField],b.where=l,b.outFields=n.relatedFields,n.outStatistics&&(0<n.outStatistics.length&&u.supportsStatistics)&&(k=new d,k.where=b.where,k.outFields=b.outFields,k.outStatistics=n.outStatistics),f=new c(y),l=[],l.push(f.execute(b)),k&&l.push(f.execute(k)));return a(l)},_setRelatedRecords:function(a,c){this._relatedInfo=[];for(var b in c)if(c.hasOwnProperty(b)&&c[b]){var d=c[b];this._relatedInfo[b]={};this._relatedInfo[b].relatedFeatures=d[0].features;f.isDefined(d[1])&&(this._relatedInfo[b].relatedStatsFeatures=
d[1].features)}},_handlerErrorResponse:function(a,c){a.reject(c)},_fromRelatedFieldName:function(a){var c=[];-1!==a.indexOf(this._relatedFieldPrefix)&&(a=a.split("/"),c=a.slice(1));return c},_toRelatedFieldName:function(a){var c="";a&&0<a.length&&(c=this._relatedFieldPrefix+a[0]+"/"+a[1]);return c}});G("extend-esri")&&(g.PopupInfo=g.PopupInfoTemplate=B);return B})},"esri/tasks/QueryTask":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/_base/json dojo/has ../kernel ../request ../deferredUtils ../geometry/Extent ../geometry/normalizeUtils ./Task ./FeatureSet".split(" "),
function(B,z,A,E,F,G,k,b,a,f,g,e,d){B=B(e,{declaredClass:"esri.tasks.QueryTask",_eventMap:{complete:["featureSet"],"execute-for-count-complete":["count"],"execute-for-ids-complete":["objectIds"],"execute-relationship-query-complete":["featureSets"]},constructor:function(a,b){this._handler=z.hitch(this,this._handler);this._relationshipQueryHandler=z.hitch(this,this._relationshipQueryHandler);this._executeForIdsHandler=z.hitch(this,this._executeForIdsHandler);this._countHandler=z.hitch(this,this._countHandler);
this._extentHandler=z.hitch(this,this._extentHandler);this.source=b&&b.source;this.gdbVersion=b&&b.gdbVersion;this.registerConnectEvents()},__msigns:[{n:"execute",c:4,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForIds",c:3,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForCount",c:3,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForExtent",c:3,a:[{i:0,p:["geometry"]}],e:2}],onComplete:function(){},onExecuteRelationshipQueryComplete:function(){},onExecuteForIdsComplete:function(){},onExecuteForCountComplete:function(){},
onExecuteForExtentComplete:function(){},execute:function(a,d,f,e,g){var m=g.assembly;a=this._encode(z.mixin({},this._url.query,{f:"json"},a.toJson(m&&m[0])));var k=this._handler,r=this._errorHandler;this.source&&(m={source:this.source.toJson()},a.layer=F.toJson(m));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return b({url:this._url.path+"/query",content:a,callbackParamName:"callback",load:function(a,c){k(a,c,d,f,g.dfd)},error:function(a){r(a,f,g.dfd)},callbackSuffix:e},this.requestOptions)},executeRelationshipQuery:function(c,
d,f){c=this._encode(z.mixin({},this._url.query,{f:"json"},c.toJson()));var e=this._relationshipQueryHandler,g=this._errorHandler;this.gdbVersion&&(c.gdbVersion=this.gdbVersion);var m=new E(a._dfdCanceller);m._pendingDfd=b({url:this._url.path+"/queryRelatedRecords",content:c,callbackParamName:"callback",load:function(a,c){e(a,c,d,f,m)},error:function(a){g(a,f,m)}},this.requestOptions);return m},executeForIds:function(a,d,f,e){var g=e.assembly;a=this._encode(z.mixin({},this._url.query,{f:"json",returnIdsOnly:!0},
a.toJson(g&&g[0])));var m=this._executeForIdsHandler,k=this._errorHandler;this.source&&(g={source:this.source.toJson()},a.layer=F.toJson(g));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return b({url:this._url.path+"/query",content:a,callbackParamName:"callback",load:function(a,c){m(a,c,d,f,e.dfd)},error:function(a){k(a,f,e.dfd)}},this.requestOptions)},executeForCount:function(a,d,f,e){var g=e.assembly;a=this._encode(z.mixin({},this._url.query,{f:"json",returnIdsOnly:!0,returnCountOnly:!0},a.toJson(g&&
g[0])));var m=this._countHandler,k=this._errorHandler;this.source&&(g={source:this.source.toJson()},a.layer=F.toJson(g));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return b({url:this._url.path+"/query",content:a,callbackParamName:"callback",load:function(a,c){m(a,c,d,f,e.dfd)},error:function(a){k(a,f,e.dfd)}},this.requestOptions)},executeForExtent:function(a,f,d,e){var g=e.assembly;a=this._encode(z.mixin({},this._url.query,{f:"json",returnExtentOnly:!0,returnCountOnly:!0},a.toJson(g&&g[0])));
var m=this._extentHandler,k=this._errorHandler;this.source&&(g={source:this.source.toJson()},a.layer=F.toJson(g));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return b({url:this._url.path+"/query",content:a,callbackParamName:"callback",load:function(a,c){m(a,c,f,d,e.dfd)},error:function(a){k(a,d,e.dfd)}},this.requestOptions)},_handler:function(a,b,f,e,g){try{var m=new d(a);this._successHandler([m],"onComplete",f,g)}catch(k){this._errorHandler(k,e,g)}},_relationshipQueryHandler:function(a,b,f,e,
g){try{var m=a.geometryType,k=a.spatialReference,r={};A.forEach(a.relatedRecordGroups,function(a){var c={};c.geometryType=m;c.spatialReference=k;c.features=a.relatedRecords;c=new d(c);if(null!=a.objectId)r[a.objectId]=c;else for(var b in a)a.hasOwnProperty(b)&&"relatedRecords"!==b&&(r[a[b]]=c)});this._successHandler([r],"onExecuteRelationshipQueryComplete",f,g)}catch(q){this._errorHandler(q,e,g)}},_executeForIdsHandler:function(a,b,f,d,e){try{this._successHandler([a.objectIds],"onExecuteForIdsComplete",
f,e)}catch(g){this._errorHandler(g,d,e)}},_countHandler:function(a,b,f,d,e){try{var g,k=a.features,r=a.objectIds;if(r)g=r.length;else{if(k)throw Error("Unable to perform query. Please check your parameters.");g=a.count}this._successHandler([g],"onExecuteForCountComplete",f,e)}catch(q){this._errorHandler(q,d,e)}},_extentHandler:function(a,b,d,e,g){try{a.extent&&(a.extent=new f(a.extent)),this._successHandler([a],"onExecuteForExtentComplete",d,g)}catch(m){this._errorHandler(m,e,g)}}});g._createWrappers(B);
G("extend-esri")&&z.setObject("tasks.QueryTask",B,k);return B})},"esri/tasks/Task":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/json dojo/has ../kernel ../deferredUtils ../urlUtils ../Evented".split(" "),function(B,z,A,E,F,G,k,b){B=B(b,{declaredClass:"esri.tasks._Task",_eventMap:{error:["error"],complete:["result"]},constructor:function(a,b){a&&z.isString(a)&&(this._url=k.urlToObject(this.url=a));b&&b.requestOptions&&(this.requestOptions=b.requestOptions);this.normalization=!0;
this._errorHandler=z.hitch(this,this._errorHandler);this.registerConnectEvents()},_useSSL:function(){var a=this._url,b=/^http:/i;this.url&&(this.url=this.url.replace(b,"https:"));a&&a.path&&(a.path=a.path.replace(b,"https:"))},_encode:function(a,b,g){var e,d,c={},h,l;for(h in a)if("declaredClass"!==h&&(e=a[h],d=typeof e,null!==e&&void 0!==e&&"function"!==d))if(z.isArray(e)){c[h]=[];l=e.length;for(d=0;d<l;d++)c[h][d]=this._encode(e[d])}else"object"===d?e.toJson&&(d=e.toJson(g&&g[h]),"esri.tasks.FeatureSet"===
e.declaredClass&&d.spatialReference&&(d.sr=d.spatialReference,delete d.spatialReference),c[h]=b?d:A.toJson(d)):c[h]=e;return c},_successHandler:function(a,b,g,e){b&&this[b].apply(this,a);g&&g.apply(null,a);e&&G._resDfd(e,a)},_errorHandler:function(a,b,g){this.onError(a);b&&b(a);g&&g.errback(a)},setNormalization:function(a){this.normalization=a},onError:function(){}});E("extend-esri")&&(F.Task=B);return B})},"esri/tasks/FeatureSet":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../kernel ../lang ../graphic ../SpatialReference ../graphicsUtils ../geometry/jsonUtils ../symbols/jsonUtils".split(" "),
function(B,z,A,E,F,G,k,b,a,f,g){B=B(null,{declaredClass:"esri.tasks.FeatureSet",constructor:function(a){if(a){z.mixin(this,a);var d=this.features,c=a.spatialReference,h=f.getGeometryType(a.geometryType),c=this.spatialReference=new b(c);this.geometryType=a.geometryType;a.fields&&(this.fields=a.fields);A.forEach(d,function(a,b){var f=a.geometry&&a.geometry.spatialReference;d[b]=new k(h&&a.geometry?new h(a.geometry):null,a.symbol&&g.fromJson(a.symbol),a.attributes);d[b].geometry&&!f&&d[b].geometry.setSpatialReference(c)});
this._hydrate()}else this.features=[]},displayFieldName:null,geometryType:null,spatialReference:null,fieldAliases:null,toJson:function(b){var d={};this.displayFieldName&&(d.displayFieldName=this.displayFieldName);this.fields&&(d.fields=this.fields);this.spatialReference?d.spatialReference=this.spatialReference.toJson():this.features[0]&&this.features[0].geometry&&(d.spatialReference=this.features[0].geometry.spatialReference.toJson());this.features[0]&&(this.features[0].geometry&&(d.geometryType=
f.getJsonType(this.features[0].geometry)),d.features=a._encodeGraphics(this.features,b));d.exceededTransferLimit=this.exceededTransferLimit;d.transform=this.transform;return G.fixJson(d)},_hydrate:function(){var a=this.transform,b=this.geometryType;if(a&&b)for(var c=this.features,f=a.translate[0],g=a.translate[1],k=a.scale[0],p=a.scale[1],m=function(a,b,c){if("esriGeometryPoint"===a)return function(a){a.x=b(a.x);a.y=c(a.y)};if("esriGeometryPolyline"===a||"esriGeometryPolygon"===a)return function(a){a=
a.rings||a.paths;var d,n,f,e,g,h,l,m;d=0;for(n=a.length;d<n;d++){g=a[d];f=0;for(e=g.length;f<e;f++)h=g[f],0<f?(l+=h[0],m+=h[1]):(l=h[0],m=h[1]),h[0]=b(l),h[1]=c(m)}};if("esriGeometryEnvelope"===a)return function(a){a.xmin=b(a.xmin);a.ymin=c(a.ymin);a.xmax=b(a.xmax);a.ymax=c(a.ymax)};if("esriGeometryMultipoint"===a)return function(a){a=a.points;var d,n,f,e,g;d=0;for(n=a.length;d<n;d++)f=a[d],0<d?(e+=f[0],g+=f[1]):(e=f[0],g=f[1]),f[0]=b(e),f[1]=c(g)}}(b,function(a){return a*k+f},function(a){return g-
a*p}),a=0,b=c.length;a<b;a++)c[a].geometry&&m(c[a].geometry);this.transform=null},quantize:function(a){if(!this.geometryType)return this.transform=null,this;var b=a.translate[0],c=a.translate[1],f=a.scale[0],g=a.scale[1],k=this.features,p=function(a,b,c){var n,f,d,e,g,h,l=[];n=0;for(f=a.length;n<f;n++)if(d=a[n],0<n){if(h=b(d[0]),d=c(d[1]),h!==e||d!==g)l.push([h-e,d-g]),e=h,g=d}else e=b(d[0]),g=c(d[1]),l.push([e,g]);return 0<l.length?l:null},m=function(a,b,c){if("esriGeometryPoint"===a)return function(a){a.x=
b(a.x);a.y=c(a.y);return a};if("esriGeometryPolyline"===a||"esriGeometryPolygon"===a)return function(a){var d,f,e,g,h;e=a.rings||a.paths;h=[];d=0;for(f=e.length;d<f;d++)g=e[d],(g=p(g,b,c))&&h.push(g);return 0<h.length?(a.rings?a.rings=h:a.paths=h,a):null};if("esriGeometryMultipoint"===a)return function(a){var d;d=p(a.points,b,c);return 0<d.length?(a.points=d,a):null};if("esriGeometryEnvelope"===a)return function(a){return a}}(this.geometryType,function(a){return Math.round((a-b)/f)},function(a){return Math.round((c-
a)/g)}),s,r;s=0;for(r=k.length;s<r;s++)k[s].geometry&&(m(k[s].geometry)||k[s].setGeometry(null));this.transform=a;return this}});E("extend-esri")&&z.setObject("tasks.FeatureSet",B,F);return B})},"esri/tasks/StatisticDefinition":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel"],function(B,z,A,E){B=B(null,{declaredClass:"esri.tasks.StatisticDefinition",toJson:function(){return{statisticType:this.statisticType,onStatisticField:this.onStatisticField,outStatisticFieldName:this.outStatisticFieldName,
maxPointCount:this.maxPointCount,maxRecordCount:this.maxRecordCount,maxVertexCount:this.maxVertexCount}}});A("extend-esri")&&z.setObject("tasks.StatisticDefinition",B,E);return B})},"esri/layers/labelLayerUtils/DynamicLabelClass":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../../kernel ../../geometry/Extent ../../geometry/Polygon".split(" "),function(B,z,A,E,F,G){B=B(null,{declaredClass:"esri.layers.labelLayerUtils.DynamicLabelClass",constructor:function(){this._preparedLabels=
[];this._placedLabels=[];this._extent=null;this._y1=this._x1=this._y0=this._x0=this._ymax=this._ymin=this._xmax=this._xmin=0;this._scale=1},setMap:function(k,b){this._labelLayer=b;this._xmin=k.extent.xmin;this._xmax=k.extent.xmax;this._ymin=k.extent.ymin;this._ymax=k.extent.ymax;this._scale=(this._xmax-this._xmin)/k.width},_process:function(k){this._preparedLabels=k;this._placedLabels=[];var b;for(k=this._preparedLabels.length-1;0<=k;k--){var a=this._preparedLabels[k],f=Math.min(a.labelWidth,a.labelHeight),
g=a.labelWidth+0*f,f=a.labelHeight+0*f,e=(b=a.options)&&void 0!==b.lineLabelPlacement?b.lineLabelPlacement:"PlaceAtCenter",d=b&&void 0!==b.lineLabelPosition?b.lineLabelPosition:"Above",c=b&&void 0!==b.pointPriorities?b.pointPriorities:"AboveRight",h=[2,2,1,3,0,2,3,3,2];"AboveLeft"==c?h=[1,2,2,2,0,3,2,3,3]:"AboveCenter"==c?h=[2,1,2,2,0,2,3,3,3]:"AboveRight"==c?h=[2,2,1,3,0,2,3,3,2]:"CenterLeft"==c?h=[2,2,3,1,0,3,2,2,3]:"CenterCenter"==c?h=[0,0,0,0,1,0,0,0,0]:"CenterRight"==c?h=[3,2,2,3,0,1,3,2,2]:
"BelowLeft"==c?h=[2,3,3,2,0,3,1,2,2]:"BelowCenter"==c?h=[3,3,3,2,0,2,2,1,2]:"BelowRight"==c&&(h=[3,3,2,3,0,2,2,2,1]);var l=b&&void 0!==b.labelRotation?b.labelRotation:!0,c=a.angle*(Math.PI/180);b=b&&void 0!==b.howManyLabels?b.howManyLabels:"OneLabel";if("point"==a.geometry.type)this._generatePointPositions(a,a.geometry.x,a.geometry.y,a.text,c,g,f,a.symbolWidth,a.symbolHeight,h);else if("multipoint"==a.geometry.type){e=a.geometry;for(d=0;d<e.points.length;d++)this._generatePointPositions(a,e.points[d][0],
e.points[d][1],a.text,c,g,f,a.symbolWidth,a.symbolHeight,h)}else"polyline"==a.geometry.type?this._generateLinePositions(a,a.geometry,a.text,g,f,2*a.symbolHeight+f,e,d,l):"polygon"==a.geometry.type&&this._generatePolygonPositions(a,b,a.geometry,a.text,c,g,f)}return this._placedLabels},_generatePointPositions:function(k,b,a,f,g,e,d,c,h,l){c=(c+e)*this._scale;h=(h+d)*this._scale;var v,p;for(v=1;3>=v;v++)for(p=1;9>=p;p++)if(l[p-1]==v)switch(p){case 1:if(this._findPlace(k,f,b-c,a+h,g,e,d))return;break;
case 2:if(this._findPlace(k,f,b,a+h,g,e,d))return;break;case 3:if(this._findPlace(k,f,b+c,a+h,g,e,d))return;break;case 4:if(this._findPlace(k,f,b-c,a,g,e,d))return;break;case 5:if(this._findPlace(k,f,b,a,g,e,d))return;break;case 6:if(this._findPlace(k,f,b+c,a,g,e,d))return;break;case 7:if(this._findPlace(k,f,b-c,a-h,g,e,d))return;break;case 8:if(this._findPlace(k,f,b,a-h,g,e,d))return;break;case 9:if(this._findPlace(k,f,b+c,a-h,g,e,d))return}},_generateLinePositions:function(k,b,a,f,g,e,d,c,h){var l=
f*this._scale*f*this._scale,v,p,m;for(v=0;v<b.paths.length;v++){var s=b.paths[v],r=s.length,q=Math.floor((r-1)/2),x=0!==(r-1)%2?1:-1;"PlaceAtStart"==d&&(q=0,x=1);"PlaceAtEnd"==d&&(q=r-2,x=-1);for(;0<=q&&q<r-1;){for(p=q;p<r;p++){var u=s[q][0],n=s[q][1],y=s[p][0]-u,t=s[p][1]-n;if(y*y+t*t>l){for(var w=Math.atan2(t,y);w>Math.PI/2;)w-=Math.PI;for(;w<-(Math.PI/2);)w+=Math.PI;var C=Math.sin(w),D=Math.cos(w),I=0,H=0;"Above"==c&&(I=e*C*this._scale,H=e*D*this._scale);"Below"==c&&(I=-e*C*this._scale,H=-e*D*
this._scale);if(1==p-q){if(this._clipLine(u,n,s[p][0],s[p][1])&&(u=this._x1-this._x0,m=this._y1-this._y0,u*u+m*m>l&&(p=Math.atan2(m,u),y=f/2+2*g,n=y*this._scale*Math.cos(p),y=y*this._scale*Math.sin(p),"PlaceAtStart"==d?(u=this._x0+n,m=this._y0+y):"PlaceAtEnd"==d?(u=this._x1-n,m=this._y1-y):(u=this._x0+u/2,m=this._y0+m/2),this._findPlace(k,a,u-I,m+H,h?-p:0,f,g))))return}else{var z=0;for(m=q;m<=p;m++)z=Math.max(z,Math.abs((s[m][1]-n)*D-(s[m][0]-u)*C));if(z<g&&this._findPlace(k,a,u+y/2-I,n+t/2+H,h?-w:
0,f,g))return}break}}q+=x}}},_generatePolygonPositions:function(k,b,a,f,g,e,d){var c;if("ManyLabels"==b)for(b=0;b<a.rings.length;b++)c=a.rings[b],G.prototype.isClockwise(c)&&(c=this._findCentroid(c,this._xmin,this._ymin,this._xmax,this._ymax),this._findPlace(k,f,c[0],c[1],g,e,d));else{c=this._findCentroidForFeature(a,this._xmin,this._ymin,this._xmax,this._ymax);var h=c[1],l=0;for(b=0;10>b;b++){l+=d/4;c=this._findCentroidForFeature(a,this._xmin,h+(l-d/4),this._xmax,h+(l+d/4));if(this._findPlace(k,
f,c[0],c[1],g,e,d))break;c=this._findCentroidForFeature(a,this._xmin,h-(l+d/4),this._xmax,h-(l-d/4));if(this._findPlace(k,f,c[0],c[1],g,e,d))break}}},_findCentroid:function(k,b,a,f,g){var e=k.length,d=[0,0],c=0,h=k[0][0],l=k[0][1];h>f&&(h=f);h<b&&(h=b);l>g&&(l=g);l<a&&(l=a);for(var v=1;v<e-1;v++){var p=k[v][0],m=k[v][1],s=k[v+1][0],r=k[v+1][1];p>f&&(p=f);p<b&&(p=b);m>g&&(m=g);m<a&&(m=a);s>f&&(s=f);s<b&&(s=b);r>g&&(r=g);r<a&&(r=a);var q=(p-h)*(r-l)-(s-h)*(m-l);d[0]+=q*(h+p+s);d[1]+=q*(l+m+r);c+=q}d[0]/=
3*c;d[1]/=3*c;if(isNaN(d[0])||isNaN(d[1]))return d;a=[];this._fillBuffer(k,a,d);d[0]=this._sortBuffer(a,d[0],b,f);return d},_findCentroidForFeature:function(k,b,a,f,g){for(var e,d=0,c=[0,0],h=0;h<k.rings.length;h++){var l=k.rings[h],v=l.length,p=l[0][0],m=l[0][1];p>f&&(p=f);p<b&&(p=b);m>g&&(m=g);m<a&&(m=a);for(e=1;e<v-1;e++){var s=l[e][0],r=l[e][1],q=l[e+1][0],x=l[e+1][1];s>f&&(s=f);s<b&&(s=b);r>g&&(r=g);r<a&&(r=a);q>f&&(q=f);q<b&&(q=b);x>g&&(x=g);x<a&&(x=a);var u=(s-p)*(x-m)-(q-p)*(r-m);c[0]+=u*
(p+s+q);c[1]+=u*(m+r+x);d+=u}}c[0]/=3*d;c[1]/=3*d;if(isNaN(c[0])||isNaN(c[1]))return c;a=[];for(e=0;e<k.rings.length;e++)this._fillBuffer(k.rings[e],a,c);c[0]=this._sortBuffer(a,c[0],b,f);return c},_fillBuffer:function(k,b,a){for(var f=k.length-1,g=k[0][1]>=k[f][1]?1:-1,e=0;e<=f;e++){var d=e,c=e+1;e==f&&(c=0);var h=k[d][0],d=k[d][1],l=k[c][0],c=k[c][1],v=c>=d?1:-1;if(d<=a[1]&&a[1]<=c||c<=a[1]&&a[1]<=d)a[1]!=d&&a[1]!=c?(b.push((a[1]-d)*(l-h)/(c-d)+h),g=v):a[1]==d&&a[1]!=c?(g!=v&&b.push(h),g=v):a[1]!=
d&&a[1]==c?(b.push(l),g=v):a[1]==d&&a[1]==c&&(1==g&&b.push(h),b.push(l),g=v)}},_sortBuffer:function(k,b,a,f){var g=k.length;k.sort();if(0<g){for(var e=0,d=b=0;d<g-1;d+=2){var c=Math.abs(k[d+1]-k[d]);!(k[d]<=a&&k[d+1]<=a)&&(!(k[d]>=f&&k[d+1]>=f)&&c>e)&&(e=c,b=d)}g=k[b];k=k[b+1];g>f&&(g=f);g<a&&(g=a);k>f&&(k=f);k<a&&(k=a);b=(g+k)/2}return b},_findPlace:function(k,b,a,f,g,e,d){if(isNaN(a)||isNaN(f))return!1;for(var c=0;c<this._placedLabels.length;c++){var h=this._placedLabels[c].angle,l=this._placedLabels[c].width*
this._scale,v=this._placedLabels[c].height*this._scale,p=this._placedLabels[c].x-a,m=this._placedLabels[c].y-f;if(0===g&&0===h){if(this._findPlace2(-e*this._scale,-d*this._scale,e*this._scale,d*this._scale,p-l,m-v,p+l,m+v))return!1}else{var s=new F(-e*this._scale,-d*this._scale,e*this._scale,d*this._scale,null),r=0,q=1;0!==g&&(r=Math.sin(g),q=Math.cos(g));var x=p*q-m*r,p=p*r+m*q,h=h-g,r=Math.sin(h),q=Math.cos(h),u=-l*q- -v*r,m=-l*r+-v*q,h=+l*q- -v*r,n=+l*r+-v*q,l=x+u,v=p-m,r=x+h,q=p-n,u=x-u,m=p+m,
x=x-h,p=p+n,h=new G;h.addRing([[l,v],[r,q],[u,m],[x,p],[l,v]]);if(s.intersects(h))return!1}}for(;g>Math.PI/2;)g-=Math.PI;for(;g<-(Math.PI/2);)g+=Math.PI;c={};c.layer=k;c.text=b;c.angle=g;c.x=a;c.y=f;c.width=e;c.height=d;this._placedLabels.push(c);return!0},_findPlace2:function(k,b,a,f,g,e,d,c){return(k>=g&&k<=d||a>=g&&a<=d||k<=g&&a>=d)&&(b>=e&&b<=c||f>=e&&f<=c||b<=e&&f>=c)?!0:!1},_clipLine:function(k,b,a,f){for(var g=this._code(k,b),e=this._code(a,f);0!==g||0!==e;){if(0!==(g&e))return!1;var d=a-k,
c=f-b;0!==g?(k<this._xmin?(b+=c*(this._xmin-k)/d,k=this._xmin):k>this._xmax?(b+=c*(this._xmax-k)/d,k=this._xmax):b<this._ymin?(k+=d*(this._ymin-b)/c,b=this._ymin):b>this._ymax&&(k+=d*(this._ymax-b)/c,b=this._ymax),g=this._code(k,b)):(a<this._xmin?(f+=c*(this._xmin-a)/d,a=this._xmin):a>this._xmax?(f+=c*(this._xmax-a)/d,a=this._xmax):f<this._ymin?(a+=d*(this._ymin-f)/c,f=this._ymin):f>this._ymax&&(a+=d*(this._ymax-f)/c,f=this._ymax),e=this._code(a,f))}this._x0=k;this._y0=b;this._x1=a;this._y1=f;return!0},
_code:function(k,b){var a=0;k<this._xmin&&(a+=8);k>this._xmax&&(a+=4);b<this._ymin&&(a+=2);b>this._ymax&&(a+=1);return a}});A("extend-esri")&&z.setObject("layers.labelLayerUtils.DynamicLabelClass",B,E);return B})},"esri/layers/labelLayerUtils/StaticLabelClass":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../../kernel ../../geometry/Extent ../../geometry/Point ../../geometry/Polygon".split(" "),function(B,z,A,E,F,G,k){return B(null,{declaredClass:"esri.layers.labelLayerUtils.StaticLabel",
constructor:function(){this._preparedLabels=[];this._placedLabels=[];this._extent=null;this._ymax=this._ymin=this._xmax=this._xmin=0;this._scale=1;this._LINE_STEP_CONST=1.5;this._POLYGON_X_STEP_CONST=1;this._POLYGON_Y_STEP_CONST=0.75;this._OVERRUN=2},setMap:function(b,a){this._labelLayer=a;this._map=b;this._xmin=b.extent.xmin;this._xmax=b.extent.xmax;this._ymin=b.extent.ymin;this._ymax=b.extent.ymax;this._scale=(this._xmax-this._xmin)/b.width},_process:function(b){var a,f,g,e,d,c,h,l,v;this._preparedLabels=
b;this._placedLabels=[];for(b=this._preparedLabels.length-1;0<=b;b--){a=this._preparedLabels[b];d=a.labelWidth;c=a.labelHeight;l=(h=a.options)&&h.lineLabelPlacement?h.lineLabelPlacement:"PlaceAtCenter";v=h&&h.lineLabelPosition?h.lineLabelPosition:"Above";f=h&&h.labelRotation?h.labelRotation:!0;g=a.angle*(Math.PI/180);e=h&&h.howManyLabels?h.howManyLabels:"OneLabel";var p=[];if("point"===a.geometry.type)this._generatePointPositions(a.geometry.x,a.geometry.y,a.text,g,d,c,a.symbolWidth,a.symbolHeight,
h,p);else if("multipoint"===a.geometry.type)for(f=0;f<a.geometry.points.length;f++)this._generatePointPositions(a.geometry.points[f][0],a.geometry.points[f][1],a.text,g,d,c,a.symbolWidth,a.symbolHeight,h,p);else if("polyline"===a.geometry.type)if("PlaceAtStart"===l)this._generateLinePositionsPlaceAtStart(a.geometry,!0,a.text,d,c,2*a.symbolHeight+c,l,v,f,p);else if("PlaceAtEnd"===l)this._generateLinePositionsPlaceAtEnd(a.geometry,!0,a.text,d,c,2*a.symbolHeight+c,l,v,f,p);else{h=[];var m=a.geometry.getExtent(),
s=this._map.extent;if(m.getWidth()<d*this._scale/this._OVERRUN&&m.getHeight()<d*this._scale/this._OVERRUN)continue;else 0.5*m.getWidth()<s.getWidth()&&0.5*m.getHeight()<s.getHeight()?(m=0.1*Math.min(this._map.width,this._map.height)*this._scale,this._generateLinePositionsPlaceAtCenter(a.geometry,!1,m,a.text,d,c,2*a.symbolHeight+c,l,v,f,h)):(m=0.2*Math.min(this._map.width,this._map.height)*this._scale,this._generateLinePositionsPlaceAtCenter(a.geometry,!0,m,a.text,d,c,2*a.symbolHeight+c,l,v,f,h));
this._postSorting(s,h,p)}else if("polygon"===a.geometry.type){l=[];for(f=0;f<a.geometry.rings.length;f++)v=a.geometry.rings[f],k.prototype.isClockwise(v)&&(h=this._calcRingExtent(v),h.xmax-h.xmin<4*d*this._scale/this._OVERRUN&&h.ymax-h.ymin<4*c*this._scale/this._OVERRUN||l.push(v));l.sort(function(a,b){return b.length-a.length});for(f=0;f<l.length;f++)this._generatePolygonPositionsForManyLabels(l[f],a.geometry.spatialReference,a.text,g,d,c,p)}for(f=0;f<p.length&&!(l=p[f].x,v=p[f].y,void 0!==p[f].angle&&
(g=p[f].angle),h=this._findPlace(a,a.text,l,v,g,d,c),"OneLabel"===e&&h&&this._labelLayer._isWithinScreenArea(new G(l,v,a.geometry.spatialReference)));f++);}return this._placedLabels},_generatePointPositions:function(b,a,f,g,e,d,c,h,l,k){f=l&&l.pointPriorities?l.pointPriorities:"AboveRight";e=(c+e)*this._scale;d=(h+d)*this._scale;switch(f.toLowerCase()){case "aboveleft":b-=e;a+=d;break;case "abovecenter":a+=d;break;case "aboveright":b+=e;a+=d;break;case "centerleft":b-=e;break;case "centercenter":break;
case "centerright":b+=e;break;case "belowleft":b-=e;a-=d;break;case "belowcenter":a-=d;break;case "belowright":b+=e;a-=d;break;default:return}k.push({x:b,y:a})},_generateLinePositionsPlaceAtStart:function(b,a,f,g,e,d,c,h,l,k){c=g*this._scale;var p=this._LINE_STEP_CONST*Math.min(this._map.width,this._map.height)*this._scale,m,s,r,q,x,u,n,y;for(m=0;m<b.paths.length;m++){var t=b.paths[m],w=c,C=0;for(s=0;s<t.length-1;s++)r=t[s][0],q=t[s][1],x=t[s+1][0],u=t[s+1][1],n=x-r,y=u-q,n=Math.sqrt(n*n+y*y),C+n>
w?(C=this._generatePositionsOnLine(b.spatialReference,a,w,p,C,r,q,x,u,f,g,e,d,h,l,k),w=p):C+=n}},_generateLinePositionsPlaceAtEnd:function(b,a,f,g,e,d,c,h,l,k){c=g*this._scale;var p=this._LINE_STEP_CONST*Math.min(this._map.width,this._map.height)*this._scale,m,s,r,q,x,u,n,y;for(m=0;m<b.paths.length;m++){var t=b.paths[m],w=c,C=0;for(s=t.length-2;0<=s;s--)r=t[s+1][0],q=t[s+1][1],x=t[s][0],u=t[s][1],n=x-r,y=u-q,n=Math.sqrt(n*n+y*y),C+n>w?(C=this._generatePositionsOnLine(b.spatialReference,a,w,p,C,r,
q,x,u,f,g,e,d,h,l,k),w=p):C+=n}},_generateLinePositionsPlaceAtCenter:function(b,a,f,g,e,d,c,h,l,k,p){var m,s,r,q,x,u,n,y;for(h=0;h<b.paths.length;h++){var t=b.paths[h];if(!(2>t.length)){if(2==t.length){q=t[0];m=t[1];r=q[0];q=q[1];t=m[0];u=m[1];x=(t-r)*(t-r)+(u-q)*(u-q);n=Math.atan2(u-q,t-r);u=Math.cos(n);n=Math.sin(n);t=[];y=r;for(var w=q;(y-r)*(y-r)+(w-q)*(w-q)<x;)t.push([y,w]),y+=f/2*u,w+=f/2*n;t.push(m)}var C=0;for(m=0;m<t.length-1;m++)r=t[m][0],q=t[m][1],x=t[m+1][0],u=t[m+1][1],n=x-r,y=u-q,C+=
Math.sqrt(n*n+y*y);for(m=w=0;m<t.length-1;m++){r=t[m][0];q=t[m][1];x=t[m+1][0];u=t[m+1][1];n=x-r;y=u-q;n=Math.sqrt(n*n+y*y);if(w+n>C/2)break;w+=n}m==t.length-1&&m--;r=t[m][0];q=t[m][1];x=t[m+1][0];u=t[m+1][1];n=x-r;y=u-q;w=C/2-w;n=Math.atan2(y,n);y=r+w*Math.cos(n);n=q+w*Math.sin(n);r=this._angleAndShifts(r,q,x,u,c,l,k);p.push({x:y+r.shiftX,y:n+r.shiftY,angle:r.angle});var C=y,D=n,w=0;for(s=m;s<t.length-1;s++)s==m?(r=C,q=D):(r=t[s][0],q=t[s][1]),x=t[s+1][0],u=t[s+1][1],n=x-r,y=u-q,n=Math.sqrt(n*n+
y*y),w=w+n>f?this._generatePositionsOnLine(b.spatialReference,a,f,f,w,r,q,x,u,g,e,d,c,l,k,p):w+n;w=0;for(s=m;0<=s;s--)s==m?(r=C,q=D):(r=t[s+1][0],q=t[s+1][1]),x=t[s][0],u=t[s][1],n=x-r,y=u-q,n=Math.sqrt(n*n+y*y),w=w+n>f?this._generatePositionsOnLine(b.spatialReference,a,f,f,w,r,q,x,u,g,e,d,c,l,k,p):w+n}}},_generatePositionsOnLine:function(b,a,f,g,e,d,c,h,l,k,p,m,s,r,q,x){k=Math.atan2(l-c,h-d);p=d;m=c;var u=p,n=m;do if(e=f-e,p+=e*Math.cos(k),m+=e*Math.sin(k),this._belongs(p,m,d,c,h,l))e=this._angleAndShifts(d,
c,h,l,s,r,q),f=p+e.shiftX,n=m+e.shiftY,a?this._labelLayer._isWithinScreenArea(new F(f,n,f,n,b))&&x.push({x:f,y:n,angle:e.angle}):x.push({x:f,y:n,angle:e.angle}),u=p,n=m,e=0,f=g;else return b=h-u,l-=n,Math.sqrt(b*b+l*l);while(1)},_postSorting:function(b,a,f){if(b&&0<a.length){var g=0.5*(b.xmin+b.xmax);b=0.5*(b.ymin+b.ymax);for(var e=a[0].x,d=a[0].y,c=Math.sqrt((e-g)*(e-g)+(d-b)*(d-b)),h=a[0].angle,l=0;l<a.length;l++){var k=a[l].x,p=a[l].y,m=Math.sqrt((k-g)*(k-g)+(p-b)*(p-b));m<c&&(e=k,d=p,c=m,h=a[l].angle)}f.push({x:e,
y:d,angle:h})}},_belongs:function(b,a,f,g,e,d){if(e==f&&d==g)return!1;if(e>f){if(b>e||b<f)return!1}else if(b<e||b>f)return!1;if(d>g){if(a>d||a<g)return!1}else if(a<d||a>g)return!1;return!0},_angleAndShifts:function(b,a,f,g,e,d,c){for(b=Math.atan2(g-a,f-b);b>Math.PI/2;)b-=Math.PI;for(;b<-(Math.PI/2);)b+=Math.PI;g=Math.sin(b);var h=Math.cos(b);f=a=0;"Above"==d&&(a=e*g*this._scale,f=e*h*this._scale);"Below"==d&&(a=-e*g*this._scale,f=-e*h*this._scale);e=[];e.angle=c?-b:0;e.shiftX=-a;e.shiftY=f;return e},
_generatePolygonPositionsForManyLabels:function(b,a,f,g,e,d,c){e=this._findCentroidForRing(b);g=e[0];var h=e[1],l=this._calcRingExtent(b);e=l.xmin;d=l.ymin;var k=l.xmax,l=l.ymax,p=(l-d)/(this._map.height*this._scale);if(!(10<(k-e)/(this._map.width*this._scale)&&10<p)){var m=!0;if(k-e>this._map.width*this._scale||l-d>this._map.height*this._scale)m=!1;var p=this._map.width*this._scale*(m?0.1875:0.5),m=this._map.height*this._scale*(m?0.1875:0.5),s=!0,r=!0,q=0;do{h+=(q%2?-1:1)*q*m;if(this._scanRingByX(f,
a,b,g,h,e,k,p,c))break;h<d&&(s=!1);h>l&&(r=!1);q++}while(s||r)}},_scanRingByX:function(b,a,f,g,e,d,c,h,l){var k=!0,p=!0,m=0,s=1E3;do{g+=(m%2?-1:1)*m*h;var r=this._movePointInsideRing(f,g,e),q=this._labelLayer._isWithinScreenArea(new F(r,e,r,e,a)),x=this._isPointWithinRing(b,f,r,e);if(q&&x)return l.push({x:r,y:e}),!0;g<d&&(k=!1);g>c&&(p=!1);m++;s--;if(0>=s)return!0}while(k||p);return!1},_movePointInsideRing:function(b,a,f){for(var g=[],e=b.length-1,d=b[0][1]>=b[e][1]?1:-1,c=0;c<=e;c++){var h=c,l=c+
1;c==e&&(l=0);var k=b[h][0],h=b[h][1],p=b[l][0],l=b[l][1],m=l>=h?1:-1;if(h<=f&&f<=l||l<=f&&f<=h)f!=h&&f!=l?(g.push((f-h)*(p-k)/(l-h)+k),d=m):f==h&&f!=l?(d!=m&&g.push(k),d=m):f!=h&&f==l?(g.push(p),d=m):f==h&&f==l&&(1==d&&g.push(k),g.push(p),d=m)}g.sort(function(a,b){return a-b});b=g.length;if(0<b){for(c=f=a=0;c<b-1;c+=2)e=Math.abs(g[c+1]-g[c]),e>a&&(a=e,f=c);a=(g[f]+g[f+1])/2}return a},_calcRingExtent:function(b){var a,f;f=new F;for(a=0;a<b.length-1;a++){var g=b[a][0],e=b[a][1];if(void 0===f.xmin||
g<f.xmin)f.xmin=g;if(void 0===f.ymin||e<f.ymin)f.ymin=e;if(void 0===f.xmax||g>f.xmax)f.xmax=g;if(void 0===f.ymax||e>f.ymax)f.ymax=e}return f},_isPointWithinPolygon:function(b,a,f,g){var e;for(e=0;e<a.rings.length;e++)if(this._isPointWithinRing(b,a.rings[e],f,g))return!0;return!1},_isPointWithinRing:function(b,a,f,g){var e,d,c,h,l=[],k=a.length;for(b=0;b<k-1;b++)if(e=a[b][0],d=a[b][1],c=a[b+1][0],h=a[b+1][1],!(e==c&&d==h)){if(d==h)if(g==d)l.push(e);else continue;e==c?(d<h&&(g>=d&&g<h)&&l.push(e),d>
h&&(g<=d&&g>h)&&l.push(e)):(d=(c-e)/(h-d)*(g-d)+e,e<c&&(d>=e&&d<c)&&l.push(d),e>c&&(d<=e&&d>c)&&l.push(d))}l.sort(function(a,b){return a-b});for(b=0;b<l.length-1;b++)if(e=l[b],c=l[b+1],f>=e&&f<c)if(b%2)break;else return!0;return!1},_findCentroidForRing:function(b){for(var a=b.length,f=[0,0],g=0,e=b[0][0],d=b[0][1],c=1;c<a-1;c++){var h=b[c][0],l=b[c][1],k=b[c+1][0],p=b[c+1][1],m=(h-e)*(p-d)-(k-e)*(l-d);f[0]+=m*(e+h+k);f[1]+=m*(d+l+p);g+=m}f[0]/=3*g;f[1]/=3*g;return f},_findCentroidForFeature:function(b){for(var a=
0,f=[0,0],g=0;g<b.rings.length;g++)for(var e=b.rings[g],d=e.length,c=e[0][0],h=e[0][1],l=1;l<d-1;l++){var k=e[l][0],p=e[l][1],m=e[l+1][0],s=e[l+1][1],r=(k-c)*(s-h)-(m-c)*(p-h);f[0]+=r*(c+k+m);f[1]+=r*(h+p+s);a+=r}f[0]/=3*a;f[1]/=3*a;return f},_findPlace:function(b,a,f,g,e,d,c){if(isNaN(f)||isNaN(g))return!1;for(var h=0;h<this._placedLabels.length;h++){var l=this._placedLabels[h].angle,v=this._placedLabels[h].width*this._scale,p=this._placedLabels[h].height*this._scale,m=this._placedLabels[h].x-f,
s=this._placedLabels[h].y-g;if(0===e&&0===l){if(this._findPlace2(-d*this._scale,-c*this._scale,d*this._scale,c*this._scale,m-v,s-p,m+v,s+p))return!1}else{var r=new F(-d*this._scale,-c*this._scale,d*this._scale,c*this._scale,null),q=0,x=1;0!==e&&(q=Math.sin(e),x=Math.cos(e));var u=m*x-s*q,m=m*q+s*x,l=l-e,q=Math.sin(l),x=Math.cos(l),n=-v*x- -p*q,s=-v*q+-p*x,l=+v*x- -p*q,y=+v*q+-p*x,v=u+n,p=m-s,q=u+l,x=m-y,n=u-n,s=m+s,u=u-l,m=m+y,l=new k;l.addRing([[v,p],[q,x],[n,s],[u,m],[v,p]]);if(r.intersects(l))return!1}}for(;e>
Math.PI/2;)e-=Math.PI;for(;e<-(Math.PI/2);)e+=Math.PI;h={};h.layer=b;h.text=a;h.angle=e;h.x=f;h.y=g;h.width=d;h.height=c;this._placedLabels.push(h);return!0},_findPlace2:function(b,a,f,g,e,d,c,h){return(b>=e&&b<=c||f>=e&&f<=c||b<=e&&f>=c)&&(a>=d&&a<=h||g>=d&&g<=h||a<=d&&g>=h)?!0:!1}})})},"*noref":1}});
define("esri/layers/LabelLayer","require dojo/_base/declare dojo/_base/lang dojo/number dojo/i18n!dojo/cldr/nls/number dojo/_base/array dojo/_base/connect dojo/has dojox/gfx/_base ../kernel ../lang ../graphic ../PopupInfo ./labelLayerUtils/DynamicLabelClass ./labelLayerUtils/StaticLabelClass ../symbols/TextSymbol ../symbols/ShieldLabelSymbol ../geometry/Extent ../geometry/Point ../geometry/webMercatorUtils ./GraphicsLayer ./LabelClass ../renderers/SimpleRenderer".split(" "),function(B,z,A,E,F,G,k,
b,a,f,g,e,d,c,h,l,v,p,m,s,r,q,x){function u(a){return"sizeInfo"===a.type}B=z(r,{declaredClass:"esri.layers.LabelLayer",constructor:function(a){this._refreshLabels=A.hitch(this,this._refreshLabels);this.id="labels";this.featureLayers=[];this._featureLayerInfos=[];this._preparedLabels=[];this._engineType="STATIC";this._mapEventHandlers=[];a&&(a.id&&(this.id=a.id),a.mode&&(this._engineType="DYNAMIC"===a.mode.toUpperCase()?"DYNAMIC":"STATIC"))},_setMap:function(a){this._mapEventHandlers.push(a.on("extent-change",
A.hitch(this,"_handleLevelChange")));var b=this.inherited(arguments);this.refresh();return b},_unsetMap:function(){var a;for(a=0;a<this._mapEventHandlers.length;a++)k.disconnect(this._mapEventHandlers[a]);this.refresh();clearTimeout(this._refreshHandle);this._refreshHandle=null;this.inherited(arguments)},setAlgorithmType:function(a){this._engineType=a&&"DYNAMIC"===a.toUpperCase()?"DYNAMIC":"STATIC";this.refresh()},addFeatureLayer:function(a,b,c,d){if(!this.getFeatureLayer(a.layerId)){var f=[];f.push(a.on("update-end",
A.hitch(this,"refresh")));f.push(a.on("suspend",A.hitch(this,"refresh")));f.push(a.on("resume",A.hitch(this,"refresh")));f.push(a.on("edits-complete",A.hitch(this,"refresh")));f.push(a.on("labeling-info-change",A.hitch(this,"refresh")));f.push(a.on("time-extent-change",A.hitch(this,"refresh")));f.push(a.on("show-labels-change",A.hitch(this,"refresh")));this._featureLayerInfos.push({FeatureLayer:a,LabelExpressionInfo:c,LabelingOptions:d,LabelRenderer:b,EventHandlers:f});this.featureLayers.push(a);
this.refresh()}},getFeatureLayer:function(a){var b,c;for(b=0;b<this.featureLayers.length;b++)if(c=this.featureLayers[b],void 0!==c&&c.id==a)return c;return null},removeFeatureLayer:function(a){var b;a=this.getFeatureLayer(a);if(void 0!==a&&(b=G.indexOf(this.featureLayers,a),-1<b)){this.featureLayers.splice(b,1);for(a=0;a<this._featureLayerInfos[b].EventHandlers.length;a++)k.disconnect(this._featureLayerInfos[b].EventHandlers[a]);this._featureLayerInfos.splice(b,1);this.refresh()}},removeAllFeatureLayers:function(){var a;
for(a=0;a<this.featureLayers.length;a++){for(var b=0;b<this._featureLayerInfos[a].EventHandlers.length;b++)k.disconnect(this._featureLayerInfos[a].EventHandlers[b]);this.featureLayers=[];this._featureLayerInfos=[]}this.refresh()},getFeatureLayers:function(){return this.featureLayers},getFeatureLayerInfo:function(a){var b,c;for(b=0;b<this.featureLayers.length;b++)if(c=this.featureLayers[b],void 0!==c&&c.id==a)return this._featureLayerInfos[b];return null},refresh:function(){null==this._refreshHandle&&
(this._refreshHandle=setTimeout(this._refreshLabels,0))},_handleLevelChange:function(a){a.levelChange&&this.clear();this.refresh()},_refreshLabels:function(a){this._refreshHandle=null;var b,d,f,e,g,l=[],k,m="DYNAMIC"===this._engineType?new c:new h;if(this._map){m.setMap(this._map,this);this._preparedLabels=[];for(a=0;a<this.featureLayers.length;a++)if(d=this.featureLayers[a],d.visible&&d.showLabels&&d.visibleAtMapScale&&!d._suspended)if(b=this._featureLayerInfos[a],g=this._convertOptions(null),b.LabelRenderer){if(l=
d.labelingInfo)if(k=l[0])e=this._getLabelExpression(k),g=this._convertOptions(k);f=b.LabelRenderer;b.LabelExpressionInfo&&(e=b.LabelExpressionInfo);b.LabelingOptions&&(g=this._convertOptions(null),void 0!==b.LabelingOptions.pointPriorities&&(l=b.LabelingOptions.pointPriorities,g.pointPriorities="above-center"==l||"AboveCenter"==l||"esriServerPointLabelPlacementAboveCenter"==l?"AboveCenter":"above-left"==l||"AboveLeft"==l||"esriServerPointLabelPlacementAboveLeft"==l?"AboveLeft":"above-right"==l||"AboveRight"==
l||"esriServerPointLabelPlacementAboveRight"==l?"AboveRight":"below-center"==l||"BelowCenter"==l||"esriServerPointLabelPlacementBelowCenter"==l?"BelowCenter":"below-left"==l||"BelowLeft"==l||"esriServerPointLabelPlacementBelowLeft"==l?"BelowLeft":"below-right"==l||"BelowRight"==l||"esriServerPointLabelPlacementBelowRight"==l?"BelowRight":"center-center"==l||"CenterCenter"==l||"esriServerPointLabelPlacementCenterCenter"==l?"CenterCenter":"center-left"==l||"CenterLeft"==l||"esriServerPointLabelPlacementCenterLeft"==
l?"CenterLeft":"center-right"==l||"CenterRight"==l||"esriServerPointLabelPlacementCenterRight"==l?"CenterRight":"AboveRight"),void 0!==b.LabelingOptions.lineLabelPlacement&&(g.lineLabelPlacement=b.LabelingOptions.lineLabelPlacement),void 0!==b.LabelingOptions.lineLabelPosition&&(g.lineLabelPosition=b.LabelingOptions.lineLabelPosition),void 0!==b.LabelingOptions.labelRotation&&(g.labelRotation=b.LabelingOptions.labelRotation),void 0!==b.LabelingOptions.howManyLabels&&(g.howManyLabels=b.LabelingOptions.howManyLabels));
f instanceof q&&(e=this._getLabelExpression(f),f=new x(f.symbol),g=this._convertOptions(f));this._addLabels(d,f,e,g)}else if(l=d.labelingInfo)for(b=l.length-1;0<=b;b--)if(k=l[b])f=new q(k instanceof q?k.toJson():k),e=this._getLabelExpression(k),g=this._convertOptions(k),this._addLabels(d,f,e,g);e=m._process(this._preparedLabels);this.clear();this.drawLabels(this._map,e)}},drawLabels:function(a,b){this._scale=(a.extent.xmax-a.extent.xmin)/a.width;var c;for(c=0;c<b.length;c++){var d=b[c],f=d.x,g=d.y,
h=d.text,k=d.angle,p=d.layer.labelSymbol;"polyline"==d.layer.geometry.type&&d.layer.options.labelRotation&&p.setAngle(k*(180/Math.PI));p.setText(h);d=f;p instanceof l&&(f=p.getHeight(),k=Math.sin(k),d-=0.25*f*this._scale*k,g-=0.33*f*this._scale);k=new e(new m(d,g,a.extent.spatialReference));k.setSymbol(p);this.add(k)}},_addLabels:function(a,b,c,d){var f,e,g,h;if(this._isWithinScaleRange(b.minScale,b.maxScale)&&c&&""!==c){var l=this._map,k=!a.url&&!l.spatialReference.equals(a.spatialReference);for(f=
0;f<a.graphics.length;f++)if(e=a.graphics[f],!1!==e.visible){g=e.geometry;if(k){if(!s.canProject(g,l))continue;g=s.project(g,l)}g&&(this._isWhere(b.where,e.attributes)&&this._isWithinScreenArea(g))&&(h=this._buildLabelText(c,e.attributes,a.fields,d),this._addLabel(h,b,a.renderer,e,d,g,l))}}},_isWithinScreenArea:function(a){a="point"===a.type?new p(a.x,a.y,a.x,a.y,a.spatialReference):a.getExtent();if(void 0===a)return!1;a=this._intersects(this._map,a);return null===a||0===a.length?!1:!0},_isWithinScaleRange:function(a,
b){var c=this._map.getScale();return 0<a&&c>=a||0<b&&c<=b?!1:!0},_isWhere:function(a,b){try{if(!a)return!0;if(a){var c=a.split(" ");if(3===c.length)return this._sqlEquation(b[this._removeQuotes(c[0])],c[1],this._removeQuotes(c[2]));if(7===c.length){var d=this._sqlEquation(b[this._removeQuotes(c[0])],c[1],this._removeQuotes(c[2])),f=c[3],e=this._sqlEquation(b[this._removeQuotes(c[4])],c[5],this._removeQuotes(c[6]));switch(f){case "AND":return d&&e;case "OR":return d||e}}}return!1}catch(g){console.log("Error.: can't parse \x3d "+
a)}},_sqlEquation:function(a,b,c){switch(b){case "\x3d":return a==c?!0:!1;case "\x3c\x3e":return a!=c?!0:!1;case "\x3e":return a>c?!0:!1;case "\x3e\x3d":return a>=c?!0:!1;case "\x3c":return a<c?!0:!1;case "\x3c\x3d":return a<=c?!0:!1}return!1},_removeQuotes:function(a){var b=a.indexOf('"'),c=a.lastIndexOf('"');if(-1!=b&&-1!=c)return a.substr(1,a.length-2);b=a.indexOf("'");c=a.lastIndexOf("'");return-1!=b&&-1!=c?a.substr(1,a.length-2):a},_getSizeInfo:function(a){return a?a.sizeInfo||G.filter(a.visualVariables,
u)[0]:null},_addLabel:function(b,c,d,f,e,g,h){var k,m,p,q;if(b&&""!==A.trim(b)&&c){b=b.replace(/\s+/g," ");k=c.getSymbol(f);k instanceof l?(k=new l(k.toJson()),k.setVerticalAlignment("baseline"),k.setHorizontalAlignment("center")):k=k instanceof v?new v(k.toJson()):new l;k.setText(b);c.symbol=k;if(p=this._getProportionalSize(c.sizeInfo,f.attributes))k instanceof l?k.setSize(p):k instanceof v&&(k.setWidth(p),k.setHeight(p));q=p=0;if(d){m=d.getSymbol(f);var r=this._getSizeInfo(d),s;r&&(s=d.getSize(f,
{sizeInfo:r,resolution:h.getResolutionInMeters()}));if(s&&null!==s)p=q=s;else if(m)if("simplemarkersymbol"==m.type)q=p=m.size;else if("picturemarkersymbol"==m.type)p=m.width,q=m.height;else if("simplelinesymbol"==m.type||"cartographiclinesymbol"==m.type)p=m.width}d={};d.graphic=f;d.options=e;d.geometry=g;d.labelRenderer=c;d.labelSymbol=k;d.labelWidth=k.getWidth()/2;d.labelHeight=k.getHeight()/2;d.symbolWidth=a.normalizedLength(p)/2;d.symbolHeight=a.normalizedLength(q)/2;d.text=b;d.angle=k.angle;this._preparedLabels.push(d)}},
_buildLabelText:function(a,b,c,f){return a.replace(/{[^}]*}/g,function(a){var e,h=a;for(e=0;e<c.length;e++)if("{"+c[e].name+"}"==a){var h=b[c[e].name],k=c[e].domain;if(k&&A.isObject(k)){if("codedValue"==k.type&&f.useCodedValues){e=h;for(a=0;a<k.codedValues.length;a++)if(k.codedValues[a].code==e){h=k.codedValues[a].name;break}}else"range"==k.type&&(k.minValue<=h&&h<=k.maxValue)&&(h=k.name);break}k=c[e].type;if(f.fieldInfos){var l=f.fieldInfos;for(e=0;e<l.length;e++)if("{"+l[e].fieldName+"}"==a){a=
l[e].format;if("esriFieldTypeDate"==k)(a="DateFormat"+d.prototype._dateFormats[a.dateFormat?a.dateFormat:"shortDate"])&&(h=g.substitute({myKey:h},"${myKey:"+a+"}"));else if(("esriFieldTypeInteger"==k||"esriFieldTypeSingle"==k||"esriFieldTypeSmallInteger"==k||"esriFieldTypeLong"==k||"esriFieldTypeDouble"==k)&&a)h=E.format(h,{places:a.places}),a.digitSeparator||F.group&&(h=h.replace(RegExp("\\"+F.group,"g"),""));break}}break}else h="";return null===h?"":h})},_getLabelExpression:function(a){return a.labelExpressionInfo?
a.labelExpressionInfo.value:this._validSyntax(a.labelExpression)?this._convertLabelExpression(a.labelExpression):""},_validSyntax:function(a){return/^(\s*\[[^\]]+\]\s*)+$/i.test(a)},_convertLabelExpression:function(a){return a.replace(RegExp("\\[","g"),"{").replace(RegExp("\\]","g"),"}")},_getProportionalSize:function(a,b){if(!a)return null;var c=g.substitute(b,"${"+a.field+"}",{first:!0});return!a.minSize||!a.maxSize||!a.minDataValue||!a.maxDataValue||!c||0>=a.maxDataValue-a.minDataValue?null:(a.maxSize-
a.minSize)/(a.maxDataValue-a.minDataValue)*(c-a.minDataValue)+a.minSize},_convertOptions:function(a){var b=!0,c="shortDate",d=null,f=null,e="",g=!0;a&&(a.format&&(c=a.format.dateFormat,d={places:a.format.places,digitSeparator:a.format.digitSeparator}),f=a.fieldInfos,e=a.labelPlacement,null!=a.useCodedValues&&(b=a.useCodedValues));if("always-horizontal"==e||"esriServerPolygonPlacementAlwaysHorizontal"==e)g=!1;return{useCodedValues:b,dateFormat:c,numberFormat:d,fieldInfos:f,pointPriorities:"above-center"==
e||"esriServerPointLabelPlacementAboveCenter"==e?"AboveCenter":"above-left"==e||"esriServerPointLabelPlacementAboveLeft"==e?"AboveLeft":"above-right"==e||"esriServerPointLabelPlacementAboveRight"==e?"AboveRight":"below-center"==e||"esriServerPointLabelPlacementBelowCenter"==e?"BelowCenter":"below-left"==e||"esriServerPointLabelPlacementBelowLeft"==e?"BelowLeft":"below-right"==e||"esriServerPointLabelPlacementBelowRight"==e?"BelowRight":"center-center"==e||"esriServerPointLabelPlacementCenterCenter"==
e?"CenterCenter":"center-left"==e||"esriServerPointLabelPlacementCenterLeft"==e?"CenterLeft":"center-right"==e||"esriServerPointLabelPlacementCenterRight"==e?"CenterRight":"AboveRight",lineLabelPlacement:"above-start"==e||"below-start"==e||"center-start"==e?"PlaceAtStart":"above-end"==e||"below-end"==e||"center-end"==e?"PlaceAtEnd":"PlaceAtCenter",lineLabelPosition:"above-after"==e||"esriServerLinePlacementAboveAfter"==e||"above-along"==e||"esriServerLinePlacementAboveAlong"==e||"above-before"==e||
"esriServerLinePlacementAboveBefore"==e||"above-start"==e||"esriServerLinePlacementAboveStart"==e||"above-end"==e||"esriServerLinePlacementAboveEnd"==e?"Above":"below-after"==e||"esriServerLinePlacementBelowAfter"==e||"below-along"==e||"esriServerLinePlacementBelowAlong"==e||"below-before"==e||"esriServerLinePlacementBelowBefore"==e||"below-start"==e||"esriServerLinePlacementBelowStart"==e||"below-end"==e||"esriServerLinePlacementBelowEnd"==e?"Below":"center-after"==e||"esriServerLinePlacementCenterAfter"==
e||"center-along"==e||"esriServerLinePlacementCenterAlong"==e||"center-before"==e||"esriServerLinePlacementCenterBefore"==e||"center-start"==e||"esriServerLinePlacementCenterStart"==e||"center-end"==e||"esriServerLinePlacementCenterEnd"==e?"OnLine":"Above",labelRotation:g,howManyLabels:"OneLabel"}}});b("extend-esri")&&A.setObject("layers.LabelLayer",B,f);return B});