// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
define("esri/layers/WCSCapabilities",["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel","../geometry/Extent"],function(h,k,m,n,l){h=h(null,{declaredClass:"esri.layers.WCSCapabilities",version:null,name:null,onlineResources:null,coverages:null,supportedFormats:null,supportedVersions:null,profiles:null,supportedInterpolations:null,constructor:function(b){this._parse=k.hitch(this,this._parse);b&&k.mixin(this,this._parse(b))},_parse:function(b){var a=this._getElement(b,"Capabilities")||this._getElement(b,
"WCS_Capabilities");if(null===a)throw"not a valid capabilities file -- cannot find Capabilities or WCS_Capabilities root element";this.version=a=a.getAttribute("version");switch(a){case "1.0.0":this._parse100(b);break;case "1.1.0":case "1.1.1":case "1.1.2":this._parse110(b);break;case "2.0.1":this._parse201(b);break;default:throw"unsupported WCS version "+a;}},_getElements:function(b,a){if(!b)return null;if(!a)return b;var c=a;-1<a.indexOf("/")?(c=a.slice(0,a.indexOf("/")),a=a.slice(a.indexOf("/")+
1)):a="";return a?this._getElement(b,c).getElementsByTagNameNS("*",a):b.getElementsByTagNameNS("*",c)},_getElement:function(b,a){if(!b)return null;if(!a)return b;var c=a;-1<a.indexOf("/")?(c=a.slice(0,a.indexOf("/")),a=a.slice(a.indexOf("/")+1)):a="";c=this._getElements(b,c);return 0<c.length?a?this._getElement(c[0],a):c[0]:null},_getElementValue:function(b,a){var c=this._getElement(b,a);return c?(c=c.textContent||c.text||c.nodeValue||c.innerText)?c.trim():null:null},_getElementValues:function(b,
a){var c=this._getElements(b,a),f=[],d,e;for(e=0;e<c.length;e++)if(d=c[e].textContent||c[e].text||c[e].nodeValue||c[e].innerText)d=d.trim(),""!==d&&f.push(d);return f},_removeTrailingQuestionMark:function(b){return!b?null:b.indexOf("?")===b.length-1?b.substring(0,b.length-1):b},_parse100:function(b){var a=this._getElement(b,"Service");this.name=this._getElementValue(a,"name");this.supportedVersions=["1.0.0"];var a={},c=this._getElement(b,"Capability");a.getCapabilities=this._removeTrailingQuestionMark(this._getElement(c,
"GetCapabilities/Get/OnlineResource").getAttribute("xlink:href"));a.describeCoverage=this._removeTrailingQuestionMark(this._getElement(c,"DescribeCoverage/Get/OnlineResource").getAttribute("xlink:href"));a.getCoverage=this._removeTrailingQuestionMark(this._getElement(c,"GetCoverage/Get/OnlineResource").getAttribute("xlink:href"));this.onlineResources=a;b=this._getElements(b,"CoverageOfferingBrief");for(var c=[],f,d,e,a=0;a<b.length;a++)f=b[a],d={},d.id=this._getElementValue(f,"name"),d.label=this._getElementValue(f,
"label"),d.description=this._getElementValue(f,"description"),e=this._getElements(f,"pos"),f=this._getElementValue(e[0]).split(" "),e=this._getElementValue(e[1]).split(" "),d.lonLatEnvelope=new l({xmin:parseFloat(f[0]),ymin:parseFloat(f[1]),xmax:parseFloat(e[0]),ymax:parseFloat(e[1]),spatialReference:{wkid:4326}}),c.push(d);this.coverages=c;return!0},_parse110:function(b){this.name=this._getElementValue(b,"ServiceIdentification/Title");this.supportedVersions=this._getElementValues(b,"ServiceIdentification/ServiceTypeVersion");
var a={},c=this._getElement(b,"OperationsMetadata");a.getCapabilities=this._removeTrailingQuestionMark(this._getElement(c.querySelector("Operation[name\x3dGetCapabilities]"),"Get").getAttribute("xlink:href"));a.describeCoverage=this._removeTrailingQuestionMark(this._getElement(c.querySelector("Operation[name\x3dDescribeCoverage]"),"Get").getAttribute("xlink:href"));a.getCoverage=this._removeTrailingQuestionMark(this._getElement(c.querySelector("Operation[name\x3dGetCoverage]"),"Get").getAttribute("xlink:href"));
this.onlineResources=a;var a=this._getElement(b,"Contents"),c=[],f=this._getElements(a,"CoverageSummary"),d,e,g;for(b=0;b<f.length;b++)d=f[b],e={},e.title=this._getElementValue(d,"Title"),e["abstract"]=this._getElementValue(d,"Abstract"),e.id=this._getElementValue(d,"Identifier"),g=this._getElement(d,"WGS84BoundingBox"),d=this._getElementValue(g,"LowerCorner").split(" "),g=this._getElementValue(g,"UpperCorner").split(" "),e.lonLatEnvelope=new l({xmin:parseFloat(d[0]),ymin:parseFloat(d[1]),xmax:parseFloat(g[0]),
ymax:parseFloat(g[1]),spatialReference:{wkid:4326}}),c.push(e);this.coverages=c;c=[];a=this._getElements(a,"SupportedFormat");for(b=0;b<a.length;b++)c.push(this._getElementValue(a[b]));this.supportedFormats=c;return!0},_parse201:function(b){var a;a=this._getElement(b,"ServiceIdentification");this.name=this._getElementValue(a,"Title");this.supportedVersions=this._getElementValues(a,"ServiceTypeVersion");var c=this._getElements(a,"Profile"),f=[];for(a=0;a<c.length;a++)f.push(this._getElementValue(c[a]));
this.profiles=f;a={};c=this._getElement(b,"OperationsMetadata");a.getCapabilities=this._removeTrailingQuestionMark(this._getElement(c.querySelector("Operation[name\x3dGetCapabilities]"),"Get").getAttribute("xlink:href"));a.describeCoverage=this._removeTrailingQuestionMark(this._getElement(c.querySelector("Operation[name\x3dDescribeCoverage]"),"Get").getAttribute("xlink:href"));a.getCoverage=this._removeTrailingQuestionMark(this._getElement(c.querySelector("Operation[name\x3dGetCoverage]"),"Get").getAttribute("xlink:href"));
this.onlineResources=a;var c=this._getElements(b,"Contents/CoverageSummary"),f=[],d,e,g;for(a=0;a<c.length;a++)d=c[a],e={},e.id=this._getElementValue(d,"CoverageId"),g=this._getElement(d,"WGS84BoundingBox"),d=this._getElementValue(g,"LowerCorner").split(" "),g=this._getElementValue(g,"UpperCorner").split(" "),e.lonLatEnvelope=new l({xmin:parseFloat(d[0]),ymin:parseFloat(d[1]),xmax:parseFloat(g[0]),ymax:parseFloat(g[1]),spatialReference:{wkid:4326}}),f.push(e);this.coverages=f;b=this._getElement(b,
"ServiceMetadata");c=this._getElements(b,"formatSupported");f=[];for(a=0;a<c.length;a++)f.push(this._getElementValue(c[a]));this.supportedFormats=f;b=this._getElements(b,"interpolationSupported");c=[];for(a=0;a<b.length;a++)c.push(this._getElementValue(b[a]));this.supportedInterpolations=c.map(function(a){var b=null;-1<a.toLowerCase().indexOf("nearest")?b=0:-1<a.toLowerCase().indexOf("linear")?b=1:-1<a.toLowerCase().indexOf("cubic")&&(b=2);return b}).filter(function(a){return null!==a});return!0}});
m("extend-esri")&&k.setObject("layers.WCSCapabilities",h,n);return h});