// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
define("esri/layers/WCSLayer","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/_base/Deferred dojo/when dojo/io-query dojo/has ../kernel ../request ../deferredUtils ./BaseRasterLayer ./WCSConnection ./Raster ./rasterFormats/ImageCanvasDecoder ./pixelFilters/StretchFilter ../geometry/Extent ../geometry ../graphic".split(" "),function(w,k,x,s,B,C,D,E,F,u,q,G,y,H,I,z,t,J){var K=function(a,d){var b;for(b=0;b<a.length;b++)if(d(a[b]))return b;return-1},L=function(a,d){var b;for(b=0;b<a.length;b++)if(d(a[b]))return a[b]},
r=function(a,d,b){var c;if(b)for(c=0;c<a.length;c++){if(a[c][b].toLowerCase()===d.toLowerCase())return a[c]}else for(c=0;c<a.length;c++)if(a[c].toLowerCase()===d.toLowerCase())return a[c]},A={parse:function(a){var d={isMultiPart:!0,data:null},b=this._getMultiPartHeader(a);b?(d.isMultiPart=!0,d.data=this._getParts(a.data,b)):(d.isMultiPart=!1,d.data=a.data);return d},_getParts:function(a,d){var b=0,c=0,e=b=0,g=[],f=[],k=[],l=[],h,p,v;h="--"+d.boundary;p="--"+d.boundary+"\n";v="\n--"+d.boundary+"--\n";
for(b=0;b<h.length;b++)f.push(h.charCodeAt(b));for(b=0;b<p.length;b++)k.push(p.charCodeAt(b));for(b=0;b<v.length;b++)l.push(v.charCodeAt(b));h=k.length;f=new Uint8Array(a);p=Math.min(1E4,f.length);for(b=0;b<p;b++)f[b]===k[e]?e===h-1?(e=0,c&&g.push(this._parsePart(f.subarray(c,b+1-h),d)),c=b+1):e++:e=0;for(b=f.length-20;b<f.length;b++)if(f[b]===l[e])if(e===l.length-1){b=b-l.length+1;g.push(this._parsePart(f.subarray(c,b),d));break}else e++;else e=0;return g},_getMultiPartHeader:function(a){var d,b,
c=a.getHeader("Content-Type").split(";");if("multipart/related"===c[0]){d={boundary:"",start:"",type:""};for(a=1;a<c.length;a++)b=c[a].split("\x3d"),d[b[0].trim()]=b[1].trim().slice(1,b[1].length-1)}return d},_parsePart:function(a,d){var b=String.fromCharCode.apply(null,a.subarray(0,300)).split("\n"),c=0,e=0,g,f,k=Math.min(b.length,7);f={contentType:null,contentDescription:null,contentTransferEncoding:null,contentID:null,contentDisposition:null,contentData:null,contentLocation:null};for(c=0;c<k;c++){if("content"===
b[c].slice(0,7).toLowerCase()){if(e=e+b[c].length+1,g=b[c].split(":"),2===g.length)switch(g[0]){case "Content-Type":f.contentType=g[1].trim();break;case "Content-Description":f.contentDescription=g[1].trim();break;case "Content-Transfer-Encoding":f.contentTransferEncoding=g[1].trim();break;case "Content-ID":f.contentID=g[1].trim();break;case "Content-Disposition":f.contentDisposition=g[1].trim();break;case "Content-Location":f.contentLocation=g[1].trim()}}else if(10<b[c].length&&"inline"===f.contentDisposition.toLowerCase()){b=
new ArrayBuffer(a.length-e);c=new Uint8Array(b);c.set(a.subarray(e,a.length));f.contentData=b;break}else e=e+b[c].length+1;if(f.contentID===d.start&&f.contentType)if(-1<f.contentType.indexOf("text")){f.contentData=String.fromCharCode.apply(null,a.subarray(e,a.length));break}else f.contentData=a.subarray(e,a.length)}return f}};q=w([q],{declaredClass:"esri.layers.WCSLayer",format:null,interpolation:null,bandIds:null,optionalParameters:null,multidimensionalDefinition:null,projectedFullExtent:null,wcsConnection:null,
version:null,coverageId:null,coverageDescription:null,extent:null,timeInfo:null,pixelType:null,_projectedResolution:null,_WEB_MERCATOR:[102100,3857,102113,900913],_REVERSED_LAT_LONG_RANGES:[[4001,4999],[2044,2045],[2081,2083],[2085,2086],[2093,2093],[2096,2098],[2105,2132],[2169,2170],[2176,2180],[2193,2193],[2200,2200],[2206,2212],[2319,2319],[2320,2462],[2523,2549],[2551,2735],[2738,2758],[2935,2941],[2953,2953],[3006,3030],[3034,3035],[3058,3059],[3068,3068],[3114,3118],[3126,3138],[3300,3301],
[3328,3335],[3346,3346],[3350,3352],[3366,3366],[3416,3416],[20004,20032],[20064,20092],[21413,21423],[21473,21483],[21896,21899],[22171,22177],[22181,22187],[22191,22197],[25884,25884],[27205,27232],[27391,27398],[27492,27492],[28402,28432],[28462,28492],[30161,30179],[30800,30800],[31251,31259],[31275,31279],[31281,31290],[31466,31700]],constructor:function(a,d){this._pixelValueReadPromise=this._rasterReadPromise=null},_initialize:function(a,d){this._params={};w.safeMixin(this,d);this.optionalParameters=
this.optionalParameters||{};this.bandIds=this.bandIds||null;var b=this.url.indexOf("?");-1<b&&b<=this.url.length-1&&(this.optionalParameters=k.mixin(this.optionalParameters,C.queryToObject(this.url.substring(b+1,this.url.length))),this.url=this.url.substring(0,b));this.coverageId=this.coverageId||this.coverage||this.identifiers||this.optionalParameters.coverage||this.optionalParameters.coverageId||this.optionalParameters.identifiers;b=k.mixin({},{version:this.version,token:this.token,coverageId:this.coverageId},
this.optionalParameters);b=this.wcsConnection||(new G(this.url,b))._connectPromise;B(b,k.hitch(this,this._initialized),this._errorHandler)},_initialized:function(a){var d;this.wcsConnection=a;this.version=this.version||a.version;this.coverageId=this.coverageId||a.coverages[0].id;var b=r(a.coverages,this.coverageId,"id");this.coverageDescription=b;this.coverageDescription.supportedInterpolations=this.coverageDescription.supportedInterpolations||a.supportedInterpolations;this.extent=this.extent||b.extent;
this.timeInfo=b.timeInfo;!this.bandIds&&this.coverageDescription.bandInfo&&(this.bandIds=Object.keys(this.coverageDescription.bandInfo).map(function(a){return parseInt(a,10)}));if((void 0===this.format||null===this.format||""===this.format||"tiff"===this.format)&&b.supportedFormats)for(d=0;d<b.supportedFormats.length;d++)if(-1<b.supportedFormats[d].toLowerCase().indexOf("tiff")){this.format=b.supportedFormats[d];break}this.format=this.format||"image/tiff";this._findCredential();(this.credential&&
this.credential.ssl||a&&a._ssl)&&this._useSSL();this._params.token=this._getToken();this.loaded=!0;this.onLoad(this);if(a=this._loadCallback)delete this._loadCallback,a(this)},onRasterReadComplete:function(){},setInfoTemplate:function(a){this.infoTemplate=a},identify:function(a){var d=new s;this._identifyPixelValue(a).then(k.hitch(this,function(a){var c=[];if((this.infoTemplate&&this.infoTemplate.info&&this.infoTemplate.info.layerOptions&&this.infoTemplate.info.layerOptions.hasOwnProperty("showNoDataRecords")?
this.infoTemplate.info.layerOptions.showNoDataRecords:1)||"NoData"!==a.value){var e=new J;e.setInfoTemplate(this.infoTemplate);e._layer=this;e.geometry=this.projectedFullExtent;e.attributes={ObjectId:0,"Raster.ServicePixelValue":a.pixelValues.map(function(a){return a.toString()})};c.push(e)}d.resolve(c)}),k.hitch(this,function(a){d.reject(a)}));return d.promise},setUseMapTime:function(a,d){this.useMapTime=a;this._toggleTime();!d&&this._map&&this.refresh(!0)},_setMap:function(a,d){a.extent&&(this.projectedFullExtent=
(this.projectedFullExtent=this.projectedFullExtent||this._convertExtentToMap(this.coverageDescription.lonLatEnvelope,a.extent.spatialReference,1E-4))||this._convertExtentToMap(this.coverageDescription.extent,a.extent.spatialReference,1E-4),this._projectedResolution=this._projectedResolution||{x:(this.projectedFullExtent.xmax-this.projectedFullExtent.xmin)/this.coverageDescription.columns,y:(this.projectedFullExtent.ymax-this.projectedFullExtent.ymin)/this.coverageDescription.rows});return this.inherited(arguments)},
_convertExtentToNative:function(a){var d=null,b=this.coverageDescription.lonLatEnvelope.spatialReference.wkid,c=a.spatialReference.wkid;b===c||-1<this._WEB_MERCATOR.indexOf(b)&&-1<this._WEB_MERCATOR.indexOf(c)?d=a:4326===b&&-1<this._WEB_MERCATOR.indexOf(c)?d=t.webMercatorUtils.webMercatorToGeographic(a):4326===c&&-1<this._WEB_MERCATOR.indexOf(b)&&(d=t.webMercatorUtils.geographicToWebMercator(a));return d},_convertExtentToMap:function(a,d,b){var c=null;d=d?d.wkid:this._map.extent.spatialReference.wkid;
var e=a.spatialReference.wkid;d===e||-1<this._WEB_MERCATOR.indexOf(d)&&-1<this._WEB_MERCATOR.indexOf(e)?c=a:4326===d&&-1<this._WEB_MERCATOR.indexOf(e)?c=t.webMercatorUtils.webMercatorToGeographic(a):4326===e&&-1<this._WEB_MERCATOR.indexOf(d)&&(c=t.webMercatorUtils.geographicToWebMercator(a));c&&(c.spatialReference.wkid&&-1<this._WEB_MERCATOR.indexOf(c.spatialReference.wkid))&&(c.spatialReference.wkid=3857);if(b&&c&&c.spatialReference.wkid)if(3857===c.spatialReference.wkid)c.xmin+=b,c.ymin+=b,c.xmax-=
b,c.ymax-=b;else if(4326===c.spatialReference.wkid||180>=Math.abs(c.xmin)&&180>=Math.abs(c.xmax))a=1/111111,c.xmin+=b*a,c.ymin+=b*a,c.xmax-=b*a,c.ymax-=b*a;return c},_constructGetCoverageParams:function(a,d,b,c){var e=this.projectedFullExtent;if(a.xmax<=e.xmin||a.xmin>=e.xmax||a.ymax<=e.ymin||a.ymin>=e.ymax)return null;var g=new z(a);g.xmin=Math.max(g.xmin,e.xmin);g.xmax=Math.min(g.xmax,e.xmax);g.ymin=Math.max(g.ymin,e.ymin);g.ymax=Math.min(g.ymax,e.ymax);d=Math.round((g.xmax-g.xmin)/(a.xmax-a.xmin)*
d);b=Math.round((g.ymax-g.ymin)/(a.ymax-a.ymin)*b);a=this._params;k.mixin(a,{extent:g,width:d,height:b,crs:"EPSG:"+e.spatialReference.wkid,epsgNSCRS:"urn:ogc:def:crs:EPSG::"+e.spatialReference.wkid,coverageId:this.coverageId,format:this.format,interpolation:this.interpolation});c&&k.mixin(a,c);a.multidimensionalDefinition||(a.multidimensionalDefinition=this.multidimensionalDefinition);a.interpolation||(this.interpolation?a.interpolation=this.interpolation:this.coverageDescription.supportedInterpolations&&
0<this.coverageDescription.supportedInterpolations.length&&(a.interpolation=this.coverageDescription.supportedInterpolations[0]));c=["nearest neighbor","bilinear","bicubic"];e=["nearest","linear","cubic"];g=["nearest-neighbor","linear","cubic"];if(0===a.interpolation||1===a.interpolation||2===a.interpolation)"1.0.0"===this.version?a.interpolation=c[a.interpolation]:"1.1.0"===this.version||"1.1.1"===this.version||"1.1.2"===this.version?a.interpolation=e[a.interpolation]:"2.0.1"===this.version&&(a.interpolation=
"http://www.opengis.net/def/interpolation/OGC/1/"+g[a.interpolation]);this.bandIds&&(a.bandIds=this.bandIds.map(k.hitch(this,function(a){return this.coverageDescription.bandInfo[a]})));!a.time&&this.coverageDescription.timeInfo&&"2.0.1"!==this.version&&(a.time=this.coverageDescription.timeInfo.timeExtent.endTime.toISOString());return a},_requestData:function(a,d,b){this._rasterReadPromise&&this._rasterReadPromise.cancel();var c=this._constructGetCoverageParams(a,d,b);if(c){var e=this,g=new y("");
this._requestExtent=c.extent;var f;this._useBrowserDecoding()&&(a=new H({ctx:this._context}),f=k.hitch(a,"decode"));var n=new s(u._dfdCanceller);n._pendingDfd=this._getCoverage(c);var l,h,p=this._requestExtent;n._pendingDfd.then(function(a){a=A.parse(a);if("1.0.0"===e.version)a=a.data;else if(a.isMultiPart)a=a.data[a.data.length-1].contentData;else{h=Error("not a valid multipart coverage response");e._resolve([h],null,k.hitch(e,e._requestDataErrorHandler),n,!0);return}g.decode(a,{width:c.width,height:c.height,
planes:null,pixelType:"UNKNOWN",decodeFunc:f}).then(function(a){e.pixelType=e.pixelType||a.pixelType;if(!e.pixelFilter){var b=e._getDefaultFilter();e.pixelFilter=b.filter;e._pixelFilterArgs=b}l={pixelBlock:a,extent:p};e._resolve([l],"onRasterReadComplete",k.hitch(e,e._requestDataHandler),n,!1)},function(a){e._resolve([a],null,k.hitch(e,e._requestDataErrorHandler),n,!0)})},function(a){e._resolve([a],null,k.hitch(e,e._requestDataErrorHandler),n,!0)});this._rasterReadPromise=n.promise}else this.clear()},
_requestDataHandler:function(a){if(!this._rasterReadPromise||!this._rasterReadPromise.isCanceled())this.originalPixelData=a,this.hasDataChanged=!0,this._setPixelData(a)},_setPixelData:function(a){a=this._clonePixelData(a);this.pixelFilter&&this.pixelFilter(a);this.pixelData=a;if(!this._rasterReadPromise||!this._rasterReadPromise.isCanceled())this._drawPixelData(),this._rasterReadPromise=null},_useBrowserDecoding:function(){var a=this._requestExtent,d=this._map.width,b=this._map.height,c=this.getCurrentResolution();
return Math.round((a.xmax-a.xmin)/c.x)===d&&Math.round((a.ymax-a.ymin)/c.y)===b&&(void 0===this.pixelFilter||null===this.pixelFilter)&&("jpeg"===this.format.toLowerCase()||"jpg"===this.format.toLowerCase()||-1<this.format.toLowerCase().indexOf("png"))},_clonePixelData:function(a){if(null===a||void 0===a)return a;var d={};a.extent&&(d.extent=k.clone(a.extent));a=a.pixelBlock;if(null===a||void 0===a)return d;d.pixelBlock=a.clone();return d},_resolve:function(a,d,b,c,e){d&&this[d].apply(this,a);b&&b.apply(null,
a);c&&u._resDfd(c,a,e)},_getDefaultFilter:function(){var a=0;"U8"!==this.pixelType&&(a=6);return new I({stretchType:a,min:0,max:255,dRA:!0,minPercent:0.2,maxPercent:0.2,useGamma:!1})},_getCoverage:function(a){var d=this.version,b=this.coverageDescription,c,e=function(a){return a.toISOString()},g=k.hitch(this,function(){c={request:"GetCoverage",service:"WCS",version:d,coverage:a.coverageId,format:a.format||"GEOTIFF",crs:a.crs,bbox:a.extent.xmin+","+a.extent.ymin+","+a.extent.xmax+","+a.extent.ymax,
width:a.width,height:a.height,time:a.time,interpolation:a.interpolation,band:a.bandIds?a.bandIds.join(","):null}}),f=k.hitch(this,function(){var l=[(a.extent.xmax-a.extent.xmin)/a.width,(a.extent.ymin-a.extent.ymax)/a.height],h=L(b.nativeCoverageDescription.range,function(a){return a.axis.some(function(a){return"band"===a.identifier.toLowerCase()})}),f,g,m,k=h&&a.interpolation&&a.bandIds?h.identifier+":"+a.interpolation+"["+a.bandIds.join(",")+"]":null;if(a.multidimensionalDefinition)for(f=0;f<a.multidimensionalDefinition.length;f++)if(m=
a.multidimensionalDefinition[f].values,0<m.length)if(-1<a.multidimensionalDefinition[f].dimensionName.toLowerCase().indexOf("time"))m=m.map(e).join(","),a.time=m;else if(h=r(b.nativeCoverageDescription.range,a.multidimensionalDefinition[f].variableName,"identifier"))if(a.interpolation||(a.interpolation=h.supportedInterpolations[0]),g=r(h.axis,a.multidimensionalDefinition[f].dimensionName,"identifier"))m=m.join(","),k=h.identifier+":"+a.interpolation+"["+g.identifier+"["+m+"]]";this.coverageDescription._useEPSGAxis&&
this._useLatLong(a.extent.spatialReference.wkid)?(h=a.extent.ymin+","+a.extent.xmin+","+a.extent.ymax+","+a.extent.xmax+","+a.epsgNSCRS,f=a.extent.ymin+","+a.extent.xmin,l=l[1]+","+l[0]):(h=a.extent.xmin+","+a.extent.ymin+","+a.extent.xmax+","+a.extent.ymax+","+a.epsgNSCRS,f=a.extent.xmin+","+a.extent.ymin,l=l[0]+","+l[1]);c={request:"GetCoverage",service:"WCS",version:d,identifier:a.coverageId,format:a.format||"image/tiff",crs:a.crs,boundingbox:h,GridBaseCRS:a.epsgNSCRS,GridCS:a.epsgNSCRS,GridType:"urn:ogc:def:method:WCS:1.1:2dGridIn2dCrs",
GridOrigin:f,GridOffsets:l,time:a.time,rangeSubset:k}}),n=k.hitch(this,function(){var f=[],h=b.nativeCoverageDescription.domainSet.axisLabels;"x"===h[0].toLowerCase()||"x"===h[1].toLowerCase()?(f.push("x,http://www.opengis.net/def/crs/EPSG/0/"+a.extent.spatialReference.wkid+"("+a.extent.xmin+","+a.extent.xmax+")"),f.push("y,http://www.opengis.net/def/crs/EPSG/0/"+a.extent.spatialReference.wkid+"("+a.extent.ymin+","+a.extent.ymax+")")):-1<h[0].toLowerCase().indexOf("lat")||-1<h[0].toLowerCase().indexOf("north")?
(f.push(h[1]+",http://www.opengis.net/def/crs/EPSG/0/"+a.extent.spatialReference.wkid+"("+a.extent.xmin+","+a.extent.xmax+")"),f.push(h[0]+",http://www.opengis.net/def/crs/EPSG/0/"+a.extent.spatialReference.wkid+"("+a.extent.ymin+","+a.extent.ymax+")")):-1<h[0].toLowerCase().indexOf("lon")||-1<h[0].toLowerCase().indexOf("east")?(f.push(h[0]+",http://www.opengis.net/def/crs/EPSG/0/"+a.extent.spatialReference.wkid+"("+a.extent.xmin+","+a.extent.xmax+")"),f.push(h[1]+",http://www.opengis.net/def/crs/EPSG/0/"+
a.extent.spatialReference.wkid+"("+a.extent.ymin+","+a.extent.ymax+")")):this._useLatLong(a.extent.spatialReference.wkid)?(f.push(h[1]+",http://www.opengis.net/def/crs/EPSG/0/"+a.extent.spatialReference.wkid+"("+a.extent.xmin+","+a.extent.xmax+")"),f.push(h[0]+",http://www.opengis.net/def/crs/EPSG/0/"+a.extent.spatialReference.wkid+"("+a.extent.ymin+","+a.extent.ymax+")")):(f.push(h[0]+",http://www.opengis.net/def/crs/EPSG/0/"+a.extent.spatialReference.wkid+"("+a.extent.xmin+","+a.extent.xmax+")"),
f.push(h[1]+",http://www.opengis.net/def/crs/EPSG/0/"+a.extent.spatialReference.wkid+"("+a.extent.ymin+","+a.extent.ymax+")"));2<h.length&&(f.push(h[2]+",http://www.opengis.net(2014/04/08 00:00:00)"),f.push(h[3]+",http://www.opengis.net(0)"));var g=null,k,m,n=[],q=[];if(a.multidimensionalDefinition){for(g=0;g<b.nativeCoverageDescription.rangeType.length;g++)q=q.concat(b.nativeCoverageDescription.rangeType[g].map(function(a){return a.name}));for(g=0;g<a.multidimensionalDefinition.length;g++)k=r(h,
a.multidimensionalDefinition[g].dimensionName),m=r(q,a.multidimensionalDefinition[g].variableName),-1===n.indexOf(m)&&n.push(m),k&&(m=a.multidimensionalDefinition[g].values,0<m.length&&(m[0]instanceof Array&&(m=m[0]),m=-1<k.toLowerCase().indexOf("time")?m.map(e).join(","):m.join(","),-1===K(f,function(a){return 0===a.indexOf(k)})&&f.push(k+",http://www.opengis.net("+m+")")));g=0<n.length?n.join(","):null}h="http://www.opengis.net/def/crs/EPSG/0/"+a.extent.spatialReference.wkid;f=f.join("\x26subset\x3d");
c={request:"GetCoverage",service:"WCS",version:d,coverageId:a.coverageId,rangesubset:g,interpolation:a.interpolation,scaleSize:"x("+a.width+"),y("+a.height+")",subset:f,extension:null,format:a.format||"image/tiff",mediaType:null,outputcrs:h}});switch(d){case "1.0.0":g();break;case "1.1.0":case "1.1.1":case "1.1.2":f();break;case "2.0.1":n()}k.mixin(c,this.optionalParameters);a.token&&(c.token=a.token);return F({url:this.wcsConnection.onlineResources.getCoverage||this.url,content:c,handleAs:"arraybuffer"},
{returnFullResponse:!0})},_identifyPixelValue:function(a){var d=new s,b={objectId:0,name:"Pixel",value:null,location:a,pixelValues:null};this._pixelValueReadPromise&&this._pixelValueReadPromise.cancel();var c=this.projectedFullExtent,e=this._projectedResolution,g=c.xmin+Math.floor((a.x-c.xmin)/e.x)*e.x,c=c.ymin+Math.floor((a.y-c.ymin)/e.y)*e.y,f=new z;f.spatialReference=a.spatialReference;f.xmin=g;f.ymin=c;f.xmax=g+2*e.x;f.ymax=c+2*e.y;var k=this._constructGetCoverageParams(f,2,2),l=this;if(!k)return d.resolve(b),
l._pixelValueReadPromise=null,d;var h=new y(""),p;a=new s(u._dfdCanceller);a._pendingDfd=this._getCoverage(k);a._pendingDfd.then(function(a){a=A.parse(a);if("1.0.0"===l.version)a=a.data;else if(a.isMultiPart)a=a.data[a.data.length-1].contentData;else{p=Error("not a valid multipart coverage response");d.reject(p);l._pixelValueReadPromise=null;return}h.decode(a,{width:k.width,height:k.height,planes:null,pixelType:"UNKNOWN"}).then(function(a){a&&a.pixels&&(!a.mask||a.mask[0]?a.pixels&&(b.pixelValues=
a.pixels.map(function(a){return a[0]}),b.value=b.pixelValues.join(" ")):(b.value="NoData",b.pixelValues=[NaN]));d.resolve(b);l._pixelValueReadPromise=null},function(a){d.reject(a);l._pixelValueReadPromise=null})},function(a){d.reject(a);l._pixelValueReadPromise=null});return this._pixelValueReadPromise=d.promise},_useLatLong:function(a){if(!a)return!1;var d,b,c;for(b=0;b<this._REVERSED_LAT_LONG_RANGES.length;b++)if(c=this._REVERSED_LAT_LONG_RANGES[b],a>=c[0]&&a<=c[1]){d=!0;break}return d},_toggleTime:function(){var a=
this._map;this.timeInfo&&this.useMapTime&&a&&!this.suspended?(this._timeConnect||(this._timeConnect=x.connect(a,"onTimeExtentChange",this,this._onTimeExtentChangeHandler)),this._setTime(a.timeExtent)):(x.disconnect(this._timeConnect),this._timeConnect=null,this._setTime(null))},_setTime:function(a){var d;this._params&&(a?(d=[],a.startTime&&d.push(a.startTime.toISOString()),a.endTime&&d.push(a.endTime.toISOString()),this._params.time=d.join(",")):this._params.time=null)},_onTimeExtentChangeHandler:function(a){this.suspended||
(this._setTime(a),this.refresh(!0))}});k.mixin(q,{INTERPOLATION_NEARESTNEIGHBOR:0,INTERPOLATION_BILINEAR:1,INTERPOLATION_CUBICCONVOLUTION:2});D("extend-esri")&&k.setObject("layers.WCSLayer",q,E);return q});