// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/vectorTiles/renderers/Renderer","require exports ../../../core/libs/gl-matrix/mat4 ../GeometryUtils ./BackgroundRenderer ./LineRenderer ./FillRenderer ./SymbolRenderer ./TileInfoRenderer ./FadeRecorder".split(" "),function(s,t,e,h,l,m,n,p,q,r){return function(){function c(a,b){this._extrudeRotateVector=new Float32Array([0,0,1]);this._extrudeScaleVector=new Float32Array([1,1,1]);this._pixelRatio=1;this._SpriteMosaic=a;this._glyphMosaic=b;this._backgroundRenderer=
new l;this._lineRenderer=new m;this._fillRenderer=new n;this._symbolRenderer=new p;this._tileInfoRenderer=new q;this._fadeRecorder=new r.FadeRecorder(300);this._extrudeMatrix=new Float32Array(16);this._extrudeNoRotationMatrix=new Float32Array(16);this._backgroundColor=new Float32Array([1,0,0,1])}c.prototype.setStateParams=function(a,b,d){this._state=a;this._pixelRatio=b;this._fadeRecorder.recordLevel(d);this._extrudeScaleVector[0]=2/a.width;this._extrudeScaleVector[1]=-2/a.height;e.identity(this._extrudeMatrix);
e.rotate(this._extrudeMatrix,this._extrudeMatrix,-a.rotation*h.C_DEG_TO_RAD,this._extrudeRotateVector);e.scale(this._extrudeMatrix,this._extrudeMatrix,this._extrudeScaleVector);e.transpose(this._extrudeMatrix,this._extrudeMatrix);e.identity(this._extrudeNoRotationMatrix);e.scale(this._extrudeNoRotationMatrix,this._extrudeNoRotationMatrix,this._extrudeScaleVector);e.transpose(this._extrudeNoRotationMatrix,this._extrudeNoRotationMatrix)};c.prototype.drawClippingMasks=function(a,b){if(0!==b.length){a.setDepthWriteEnabled(!1);
a.setDepthTestEnabled(!1);a.setStencilTestEnabled(!0);a.setBlendingEnabled(!1);a.setColorMask(!1,!1,!1,!1);a.setStencilOp(7680,7680,7681);a.setClearStencil(0);a.clear(a.gl.STENCIL_BUFFER_BIT);for(var d=0;d<b.length;d++){var f=b[d];f.attached&&f.visible&&(a.setStencilFunctionSeparate(1032,519,f.stencilData.reference,f.stencilData.mask),a.setStencilWriteMask(f.stencilData.mask),this._backgroundRenderer.renderSolidColor(a,{u_matrix:f.tileTransform.transform,u_normalized_origin:f.tileTransform.displayCoord,
u_coord_range:f.coordRange,u_depth:0,u_color:this._backgroundColor}))}a.setColorMask(!0,!0,!0,!0);a.setBlendingEnabled(!0);a.setStencilWriteMask(255)}};c.prototype.renderDebug=function(a,b){var d=b.key;this._backgroundColor.set([d.col%2,d.row%2,0===d.col%2&&0===d.row%2?1:0,0.5]);this._backgroundRenderer.renderSolidColor(a,{u_matrix:b.tileTransform.transform,u_normalized_origin:b.tileTransform.displayCoord,u_coord_range:b.coordRange,u_depth:0,u_color:this._backgroundColor})};c.prototype.renderBucket=
function(a,b,d,f,g,c,e){switch(b.type){case 0:2!==g&&this._renderBackground(a,d,g,c,e);break;case 1:2!==g&&this._renderFill(a,b,d,g,c,e);break;case 2:1===g&&this._renderLine(a,b,d,c,e);break;case 3:2===g&&this._renderSymbol(a,b,d,f,c,e)}};c.prototype.renderTileInfo=function(a,b){this._tileInfoRenderer.render(a,b)};c.prototype.needsRedraw=function(){return this._fadeRecorder.needsRedraw()};c.prototype._renderBackground=function(a,b,d,f,c){this._backgroundRenderer.render(a,b,d,f,c,this._SpriteMosaic,
this._SpriteMosaic.pixelRatio)};c.prototype._renderLine=function(a,b,d,c,g){this._lineRenderer.render(a,b,d,this._state,c,g,this._extrudeMatrix,this._SpriteMosaic.pixelRatio)};c.prototype._renderFill=function(a,b,d,c,g,e){this._fillRenderer.render(a,b,d,this._state.rotation,c,g,e,this._SpriteMosaic,this._extrudeMatrix,this._SpriteMosaic.pixelRatio)};c.prototype._renderSymbol=function(a,b,d,c,e,h){var k=!0;c===e.key.level&&(k=!1);a.setStencilTestEnabled(k);this._symbolRenderer.render(a,b,d,this._state.rotation,
this._fadeRecorder.getFadeValues(),e,h,this._SpriteMosaic,this._glyphMosaic,this._extrudeMatrix,this._extrudeNoRotationMatrix,this._SpriteMosaic.pixelRatio)};return c}()});