// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
define("esri/renderers/Renderer","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has dojox/gfx/_base ../kernel ../Color ./arcadeUtils".split(" "),function(s,n,l,x,p,y,q,u){var v=Math.PI,z=1;s=s(null,{declaredClass:"esri.renderer.Renderer",constructor:function(a){this._cache={};if(a&&!a.declaredClass){this.rotationInfo=a.rotationInfo;if(!this.rotationInfo){var b=a.rotationType,c=a.rotationExpression;if(b||c)this.rotationInfo={type:b,expression:c}}this.setRotationInfo(this.rotationInfo);this.setSizeInfo(this._readSizeInfo(a.sizeInfo));
this.setColorInfo(this._readColorInfo(a.colorInfo));this.setOpacityInfo(this._readOpacityInfo(a.transparencyInfo));this.setVisualVariables(this._readVariables(a.visualVariables));this.setAuthoringInfo(a.authoringInfo)}this.getSymbol=n.hitch(this,this.getSymbol)},getSymbol:function(a){},_readSizeInfo:function(a){if(a){var b=a.minSize,c=a.maxSize;b&&(a.minSize="number"===typeof b?p.pt2px(b):this._readSizeInfo(b));c&&(a.maxSize="number"===typeof c?p.pt2px(c):this._readSizeInfo(c));a.stops&&l.forEach(a.stops,
function(a){a.size&&"number"===typeof a.size&&(a.size=p.pt2px(a.size))})}return a},_readColorInfo:function(a){a&&(l.forEach(a.colors,function(b,c){n.isArray(b)&&(a.colors[c]=q.toDojoColor(b))}),l.forEach(a.stops,function(b,c){b.color&&n.isArray(b.color)&&(a.stops[c].color=q.toDojoColor(b.color))}));return a},_readOpacityInfo:function(a){var b;a&&(b=n.mixin({},a),b.transparencyValues&&(b.opacityValues=l.map(b.transparencyValues,function(a){return 1-a/100}),delete b.transparencyValues),b.stops&&(b.stops=
l.map(b.stops,function(a){a=n.mixin({},a);a.opacity=1-a.transparency/100;delete a.transparency;return a})));return b},_readVariables:function(a){a&&(a=l.map(a,function(a){"sizeInfo"===a.type?a=this._readSizeInfo(a):"colorInfo"===a.type?a=this._readColorInfo(a):"transparencyInfo"===a.type&&(a=this._readOpacityInfo(a),a.type="opacityInfo");return a},this));return a},setAuthoringInfo:function(a){this.authoringInfo=a},setRotationInfo:function(a){if(a=this.rotationInfo="string"===typeof a?{field:a}:a){if(a.expression&&
!n.isFunction(a.expression)&&!a.field){var b=a.expression.match(this.rotationRE);b&&b[1]&&(a.field=b[1])}a.rotationType=a.type}return this},rotationRE:/^\[([^\]]+)\]$/i,getRotationAngle:function(a,b){var c=this._getVarInfo(b&&b.rotationInfo,"rotationInfo").variable,d="arithmetic"===this._getRotationType(c),c=c.field,e=a.attributes,k=0;c&&(n.isFunction(c)?k=c.apply(this,arguments):e&&(k=e[c]||0),k=(k+(d?-90:0))*(d?-1:1));return k},_getRotationType:function(a){return a&&("rotationInfo"===a.type?a.rotationType:
a.type)},_getDataValue:function(a,b,c,d){d||(d=this._getVarInfo(b,c),b=d.variable,d=this._cache[d.cacheKey],"sizeInfo"===c&&(d=d.root));return a._getDataValue(b,d,u)},setVisualVariables:function(a){var b=this._cache;l.forEach(this.visualVariables,function(a,d){b.hasOwnProperty(d)&&(b[d]=null)},this);this.visualVariables=a;l.some(a,function(a){return!!a.target})&&a.sort(function(a,b){return a.target===b.target?0:a.target?1:-1});l.forEach(a,function(a,d){"colorInfo"===a.type?b[d]=this._processColorInfo(a):
"opacityInfo"===a.type?b[d]=this._processOpacityInfo(a):"sizeInfo"===a.type&&(b[d]=this._processSizeInfo(a))},this);return this},getVisualVariableValues:function(a){var b=this.visualVariables,c;b&&(c=l.map(b,function(b){var c;switch(b.type){case "sizeInfo":c=this.getSize(a,{sizeInfo:b});break;case "colorInfo":c=this.getColor(a,{colorInfo:b});break;case "opacityInfo":c=this.getOpacity(a,{opacityInfo:b});break;case "rotationInfo":c=this.getRotationAngle(a,{rotationInfo:b})}return{variable:b,value:c}},
this));return c},hasVisualVariables:function(a,b){return a?!!this.getVisualVariablesForType(a,b):!(!this.getVisualVariablesForType("sizeInfo",b)&&!this.getVisualVariablesForType("colorInfo",b)&&!this.getVisualVariablesForType("opacityInfo",b)&&!this.getVisualVariablesForType("rotationInfo",b))},getVisualVariablesForType:function(a,b){var c=this.visualVariables,d;!b&&this[a]?("rotationInfo"===a&&(this[a].rotationType=this[a].type),d=[this[a]]):c&&(d=l.filter(c,function(c){return c.type===a&&("string"===
typeof b?c.target===b:!1===b?!c.target:!0)}))&&0===d.length&&(d=void 0);return d},setSizeInfo:function(a){this.sizeInfo=this.proportionalSymbolInfo=a;this._cache.sizeInfo=this._processSizeInfo(a);return this},_processSizeInfo:function(a){return a&&{root:this._createCache(a),minSize:this._createCache(a.minSize),maxSize:this._createCache(a.maxSize)}},_getVarInfo:function(a,b){var c;a&&a.type===b?(c=l.indexOf(this.visualVariables,a),a=this.visualVariables[c]):(c=b,a=this[b]);return{variable:a,cacheKey:c}},
setProportionalSymbolInfo:function(a){this.setSizeInfo(a);return this},getSize:function(a,b){var c=this._getVarInfo(b&&b.sizeInfo,"sizeInfo"),d=c.variable,c=this._cache[c.cacheKey],e=null;if(d)var k=d.minSize,e=d.maxSize,k="object"===typeof k&&k?this._getSize(a,k,c&&c.minSize,b):k,e="object"===typeof e&&e?this._getSize(a,e,c&&c.maxSize,b):e,e=this._getSize(a,d,c&&c.root,b,[k,e]);return e},_getSize:function(a,b,c,d,e){var k=b.expression,g=b.stops,h=0,f=c&&c.exprTree,l=c&&c.ipData,m="number"===typeof a?
a:null;if(b.field||k||f){var n=d&&d.scale,f=e?e[0]:b.minSize;e=e?e[1]:b.maxSize;var r=b.minDataValue,w=b.maxDataValue,q=b.valueUnit||"unknown",p=b.valueRepresentation,s=b.scaleBy,t=d&&d.shape;k?m="view.scale"===k.toLowerCase()?n:null:"number"!==typeof m&&(m=this._getDataValue(a,b,null,c));if(null==m)return null;if(g)f=this._lookupData(m,l),m=f[0],e=f[1],m===e?h=g[m].size:(m=g[m].size,g=g[e].size,h=m+(g-m)*f[2]);else if(null!=f&&null!=e&&null!=r&&null!=w)m<=r?h=f:m>=w?h=e:(g=(m-r)/(w-r),"area"===s&&
t?(f=(m="circle"===t)?v*Math.pow(f/2,2):f*f,e=m?v*Math.pow(e/2,2):e*e,g=f+g*(e-f),h=m?2*Math.sqrt(g/v):Math.sqrt(g)):h=f+g*(e-f));else if("unknown"===q)null!=f&&null!=r&&(f&&r?(g=m/r,h="circle"===t?2*Math.sqrt(g*Math.pow(f/2,2)):"square"===t||"diamond"===t||"image"===t?Math.sqrt(g*Math.pow(f,2)):g*f):h=m+(f||r),h=h<f?f:h,null!=e&&h>e&&(h=e));else{g=(d&&d.resolution?d.resolution:1)*this._meterIn[q];if("area"===p)h=Math.sqrt(m/v)/g,h*=2;else if(h=m/g,"radius"===p||"distance"===p)h*=2;null!=f&&h<f&&
(h=f);null!=e&&h>e&&(h=e)}}else h=g&&g[0]&&g[0].size,null==h&&(h=b.minSize);return h=isNaN(h)?0:h},getSizeRangeAtScale:function(a,b){var c,d=this._getVarInfo(a,"sizeInfo"),e=this._cache[d.cacheKey],k={scale:b};if((a=d.variable)&&b){var g=a.minSize,d=a.maxSize,g="object"===typeof g&&g?this._getSize({},g,e&&e.minSize,k):g,e="object"===typeof d&&d?this._getSize({},d,e&&e.maxSize,k):d;if(null!=g||null!=e)c={minSize:g,maxSize:e}}return c},setColorInfo:function(a){this.colorInfo=a;this._cache.colorInfo=
this._processColorInfo(a);return this},_createCache:function(a){return{ipData:this._interpolateData(a),exprTree:u.parseExpression(a&&a.valueExpression),version:z++}},_processColorInfo:function(a){a&&(l.forEach(a.colors,function(b,c){n.isArray(b)&&(a.colors[c]=new q(b))}),l.forEach(a.stops,function(b,c){b.color&&n.isArray(b.color)&&(a.stops[c].color=new q(b.color))}));return this._createCache(a)},getColor:function(a,b){var c=this._getVarInfo(b&&b.colorInfo,"colorInfo");return this._getColorComponent(a,
c.variable,this._cache[c.cacheKey])},setOpacityInfo:function(a){this.opacityInfo=a;this._cache.opacityInfo=this._processOpacityInfo(a);return this},_processOpacityInfo:function(a){return this._createCache(a)},getOpacity:function(a,b){var c=this._getVarInfo(b&&b.opacityInfo,"opacityInfo");return this._getColorComponent(a,c.variable,this._cache[c.cacheKey],!0)},_getColorComponent:function(a,b,c,d,e){var k=a.attributes,g=b&&b.field,h="number"===typeof a,f=h?a:null,l=c&&c.exprTree,m=c&&c.ipData,p;if(g||
l){var r=b.normalizationField,q=k?parseFloat(k[r]):void 0;"number"!==typeof f&&(l?f=u.executeExpression(l,u.createExecContext(a)):n.isFunction(g)?f=g.apply(this,arguments):k&&(f=k[g]));if(null!=f&&(!r||h||!isNaN(q)&&0!==q))!isNaN(q)&&!h&&(f/=q),p=d?this._getOpacity(f,b,m):this._getColor(f,b,m)}else b&&(k=b.stops,d?(p=k&&k[0]&&k[0].opacity,null==p&&(p=b.opacityValues&&b.opacityValues[0])):p=k&&k[0]&&k[0].color||b.colors&&b.colors[0]);e&&(e.data=f,e.value=p);return e||p},_interpolateData:function(a){var b;
if(a)if(a.colors||a.opacityValues){var c=(a.colors||a.opacityValues).length,d=a.minDataValue,e=(a.maxDataValue-d)/(c-1);b=[];for(a=0;a<c;a++)b[a]=d+a*e}else a.stops&&(b=l.map(a.stops,function(a){return a.value}));return b},_getOpacity:function(a,b,c){a=this._lookupData(a,c);var d;b=b||this.opacityInfo;a&&(c=a[0],d=a[1],c===d?d=this._getOpacValue(b,c):(c=this._getOpacValue(b,c),b=this._getOpacValue(b,d),d=c+(b-c)*a[2]));return d},_getOpacValue:function(a,b){return a.opacityValues?a.opacityValues[b]:
a.stops[b].opacity},_getColor:function(a,b,c){a=this._lookupData(a,c);var d;b=b||this.colorInfo;a&&(d=a[0],c=a[1],d=d===c?this._getColorObj(b,d):q.blendColors(this._getColorObj(b,d),this._getColorObj(b,c),a[2]));return d},_getColorObj:function(a,b){return a.colors?a.colors[b]:a.stops[b].color},_lookupData:function(a,b){var c;if(b){var d=0,e=b.length-1;l.some(b,function(b,c){if(a<b)return e=c,!0;d=c;return!1});c=[d,e,(a-b[d])/(b[e]-b[d])]}return c},_meterIn:{inches:1/0.0254,feet:1/0.3048,yards:1/0.9144,
miles:1/1609.344,"nautical-miles":1/1852,millimeters:1E3,centimeters:100,decimeters:10,meters:1,kilometers:0.0010,"decimal-degrees":180/20015077},_writeSizeInfo:function(a){if(a){a=n.mixin({},a);var b=a.minSize,c=a.maxSize;b&&(a.minSize="number"===typeof b?p.px2pt(b):this._writeSizeInfo(b));c&&(a.maxSize="number"===typeof c?p.px2pt(c):this._writeSizeInfo(c));if(b=a.legendOptions)if(a.legendOptions=n.mixin({},b),b=b.customValues)a.legendOptions.customValues=b.slice(0);a.stops&&(a.stops=l.map(a.stops,
function(a){a=n.mixin({},a);a.size&&"number"===typeof a.size&&(a.size=p.px2pt(a.size));return a}))}return a},_writeColorInfo:function(a){a&&(a=n.mixin({},a),a.colors&&(a.colors=l.map(a.colors,function(a){return q.toJsonColor(a)})),a.stops&&(a.stops=l.map(a.stops,function(a){a=n.mixin({},a);a.color&&(a.color=q.toJsonColor(a.color));return a})));return a},_writeOpacityInfo:function(a){var b;a&&(b=n.mixin({},a),b.opacityValues&&(b.transparencyValues=l.map(b.opacityValues,function(a){return 100*(1-a)}),
delete b.opacityValues),b.stops&&(b.stops=l.map(b.stops,function(a){a=n.mixin({},a);a.transparency=100*(1-a.opacity);delete a.opacity;return a})),b.legendOptions&&(b.legendOptions=n.mixin({},b.legendOptions)));return b},toJson:function(){var a=this.visualVariables,b=n.clone(this.authoringInfo),c=this.getVisualVariablesForType("rotationInfo",!1),d=(c=c&&c[0])&&c.field,d=c&&(c.expression||d&&(n.isFunction(d)?d:"["+d+"]"));a&&(a=l.map(a,function(a){"sizeInfo"===a.type?a=this._writeSizeInfo(a):"colorInfo"===
a.type?a=this._writeColorInfo(a):"opacityInfo"===a.type?(a=this._writeOpacityInfo(a),a.type="transparencyInfo"):"rotationInfo"===a.type&&(a=n.mixin({},a));return a},this));b&&l.forEach(b.visualVariables,function(a){"opacityInfo"===a.type&&(a.type="transparencyInfo")});return{rotationType:d&&(this._getRotationType(c)||"geographic"),rotationExpression:d,colorInfo:this._writeColorInfo(this.colorInfo),transparencyInfo:this._writeOpacityInfo(this.opacityInfo),sizeInfo:this._writeSizeInfo(this.sizeInfo),
visualVariables:a,authoringInfo:b}}});x("extend-esri")&&n.setObject("renderer.Renderer",s,y);return s});