// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
define("esri/dijit/FeatureTable/dataUtils","dojo/_base/array dojo/_base/lang dojo/Deferred dojo/string dojo/date/locale dojo/promise/all ../../config ../../numberUtils ../../request ../../layers/FeatureLayer ../../geometry/Extent ../../tasks/query ../../tasks/StatisticDefinition ../../tasks/QueryTask ../../tasks/RelationshipQuery dojo/i18n!../../nls/jsapi".split(" "),function(l,s,t,D,w,x,u,y,q,r,v,h,z,A,B,C){var m={i18nStrings:C.widgets.FeatureTable,numericFieldTypes:["esriFieldTypeInteger","esriFieldTypeSingle",
"esriFieldTypeDouble","esriFieldTypeSmallInteger"],statisticDefinitions:[{type:"count",name:"countField"},{type:"sum",name:"sumField"},{type:"min",name:"minField"},{type:"max",name:"maxField"},{type:"avg",name:"avgField"},{type:"stddev",name:"stddevField"}],getOrderByString:function(a,b){return a+(b?" DESC":" ASC")},getWhereString:function(a,b){return a+"\x3d'"+b+"'"},getRelationshipWhereClause:function(a){var b=a.layer,c=a.originRelationship,e=a.destinationRelationship;a=a.keyValue;var d=b._url.path,
d=d.substring(0,d.lastIndexOf("/")+1),f=[],k="",g,n,p,h;g=c.relationshipTableId||c.relatedTableId;c=c.keyFieldInRelationshipTable||c.keyField;n=e.keyFieldInRelationshipTable||e.keyField;d=d+g+"/query";b=this.getWhereString(b.layerId===g?n:c,a);return q({url:d,content:{f:"json",outFields:[c,n],returnGeometry:!1,where:b},handleAs:"json",callbackParamName:"callback"}).then(s.hitch(this,function(a){return a&&a.features&&(h=a.features,0<h.length)?(l.forEach(h,function(a,b){p=a.attributes[n];-1===l.indexOf(f,
p)&&(0<f.length&&b<h.length&&(k=k.concat(" OR ")),f.push(p),k=k.concat(this.getWhereString(e.keyField,p)))},this),k):null}))},isValueEmpty:function(a){return null===a||" "===a||""===a||"undefined"===typeof a},findFirst:function(a,b,c){return l.filter(a,function(a){return a.hasOwnProperty(b)&&a[b]===c})[0]||null},findFirstNumberColumn:function(a,b){var c;l.some(a,function(a,d){if(-1!==l.indexOf(this.numericFieldTypes,a.type)&&a.field!==b&&!a.hidden)return c=a,!0},this);return c},getRoundingPrecision:function(a){return 1E3<=
a?0:10<=a?2:0<=a?4:6},generateLinkFromString:function(a){var b,c,e;"string"===typeof a&&(b=a.indexOf("http:"),-1===b&&(b=a.indexOf("https:")),-1<b&&-1===a.indexOf("href\x3d")&&(c=a.indexOf(" ",b),-1===c&&(c=a.length),e=a.substring(b,c),a=a.substring(0,b)+"\x3ca href\x3d'"+e+"' target\x3d'_blank'\x3e"+e+"\x3c/a\x3e"+a.substring(c,a.length)));return a||""},isNumericFieldType:function(a){return-1!==l.indexOf(this.numericFieldTypes,a)},isIntegerFieldType:function(a){return"esriFieldTypeInteger"===a||
"esriFieldTypeSmallInteger"===a},isFloatFieldType:function(a){return"esriFieldTypeDouble"===a||"esriFieldTypeSingle"===a},getDomainValueFromRow:function(a){var b=a.fieldInfo.name,c=a.fieldInfo.domain;a=a.row;return"range"===c.type?a[b]:(b=m.findFirst(c.codedValues,"code",a[b]))?b.name:""},getTypeValueFromRow:function(a){var b=a.layerInfo.types,c=a.fieldInfo,e=a.row;a=b&&b[0];var d;a&&(d=e[c.name],c=m.isNumericFieldType(c.type),c=(a="string"===typeof a.id)&&c?d.toString():d,d=(d=m.findFirst(b,"id",
c))?d.name:null);return d},getSubtypeDomainValue:function(a){var b=a.layerInfo,c=a.fieldInfo.name;a=a.row;var e,d,b=(d=m.findFirst(b.types,"id",a[b.typeIdField]))?d.domains:null;if(!d||!b)return a[c];b[c]&&b[c].codedValues&&(e=this.findFirst(b[c].codedValues,"code",a[c]));return e?e.name:a[c]},mergeDictionaries:function(a,b){if(null===a||null===b)return a;for(var c in b){a[c]||(a[c]={});for(var e in b[c])a[c][e]=b[c][e]}return a},isCyclicalRelationship:function(a){return"esriRelCardinalityOneToOne"===
a.cardinality||"esriRelCardinalityOneToMany"===a.cardinality&&"esriRelRoleDestination"===a.role},formatNumberForLocale:function(a,b){return isNaN(a)||null===a?null:y.format(a,b)},getCombinedDateTime:function(a,b){return new Date(a.getFullYear(),a.getMonth(),a.getDate(),b.getHours(),b.getMinutes(),b.getSeconds())},formatDateForLocale:function(a){var b=a.dateOptions||{},c=a.timestamp,e=a.fieldInfo,d=!1,f=!1;a={};b=(d=e&&e.dateOptions?e.dateOptions:!1)||b;d=d&&this.isValueEmpty(b.dateEnabled)?!0:!!b.dateEnabled;
f=!!b.timeEnabled;this.isValueEmpty(b.datePattern)||(a.datePattern=b.datePattern);!this.isValueEmpty(b.timeEnabled)&&!this.isValueEmpty(b.timePattern)&&(a.timePattern=b.timePattern);a.selector=d&&f?"date and time":d&&!f?"date":!d&&f?"time":"date";return w.format(new Date(c),a)},calculateExtentFromFeatures:function(a){var b=a[0].geometry,c,e,d,f;if(null===b&&1===a.length)return null;for(b=a.length-1;0<=b;b--)null===a[b].geometry&&a.splice(b,1);b=a[0].geometry;c=b.getExtent();d=a.length;null===c&&(c=
new v(b.x,b.y,b.x,b.y,b.spatialReference));for(f=1;f<d;f++)b=a[f].geometry,e=b.getExtent(),null===e&&(e=new v(b.x,b.y,b.x,b.y,b.spatialReference)),c=c.union(e);return c},initFeatureLayer:function(a,b){var c=a._url.path,c=c.substring(0,c.lastIndexOf("/")+1);return new r(c+b,{mode:r.MODE_ONDEMAND,outFields:["*"],visible:!0})},applyEdits:function(a){var b=[],c=new t;if(!a||0>=a.length)return c.reject(),c;l.forEach(a,function(a){a.layer&&b.push(a.layer.applyEdits(a.adds,a.updates,a.deletes))});0<b.length?
x(b).then(c.resolve,c.reject):c.reject();return c},applyEditsFromRow:function(a){var b=a.layer,c=a.row;return this.queryLayerForFeature({layer:b,id:c[a.idProperty]}).then(s.hitch(this,function(a){a=a.features[0];a.attributes=c;return this.applyEdits([{layer:b,updates:[a]}],null)}))},queryLayer:function(a){var b=a.layer;a=a.ids||null;var c=new h;c.where="1\x3d1";c.returnGeometry=!1;c.objectIds=a;return b.queryFeatures(c)},queryLayerForFeature:function(a){return this.queryLayerForFeatures({layer:a.layer,
ids:[a.id]})},queryLayerForFeatures:function(a){var b=a.layer;a=a.ids;var c=new h;c.objectIds=a;c.outFields=["*"];return b.queryFeatures(c,function(a){return a.features})},queryLayerForCount:function(a){var b=a.layer,c=a.layerInfo,e=new h;a=a.where||"1\x3d1";e.returnGeometry=!1;e.returnCountOnly=!0;e.where=a;u.defaults.io.timeout=1E4;return b.queryCount(e).then(function(a){return a}).otherwise(function(){return c.isFeatureCollection?b.graphics.length:2E3}).always(function(a){u.defaults.io.timeout=
6E4;return a})},queryLayerForIds:function(a){var b=a.layer;a=a.idProperty;var c=new h;c.returnGeometry=!1;c.outFields=[a];c.where="1\x3d1";c.returnIdsOnly=!0;return b.queryIds(c)},queryLayerForAttachments:function(a){return q({url:a.layer._url.path+"/queryAttachments",content:{f:"json",objectIds:a.ids},handleAs:"json",callbackParamName:"callback"})},queryLayerForAttachmentById:function(a){return a.layer.queryAttachmentInfos(a.id||0)},addAttachmentToLayer:function(a){return a.layer.addAttachment(a.featureId,
a.formData)},deleteAttachmentFromLayer:function(a){return a.layer.deleteAttachments(a.featureId,[a.attachmentId])},queryLayerForRelatedRecords:function(a){var b=a.layer,c=a.ids,e=a.outFields||["*"],d=a.relationship;a=a.returnCountOnly||!1;var f=new B;f.outFields=e;f.returnGeometry=!1;f.relationshipId=d.id;f.returnCountOnly=a;f.objectIds=c;return b.queryRelatedFeatures(f)},queryLayerForRelatedRecordCount:function(a){return q({url:a.layer._url.path+"/queryRelatedRecords",content:{f:"json",objectIds:a.objectIds.toString(),
outFields:a.outFields,returnGeometry:!1,relationshipId:a.relationship.id,returnCountOnly:!0},handleAs:"json",callbackParamName:"callback"})},getFieldStatistics:function(a){var b=new t,c=a.layer,e=a.idProperty,d=a.where||"1\x3d1",f=a.filterIds,k=a.grid.columns[a.columnId].field;a=[];var g;g=new h;g.outFields=[k];g.outStatistics=[];g.where=d;d=l.map(this.statisticDefinitions,function(a){var b=new z;b.onStatisticField=k;b.displayFieldName=k;b.outStatisticFieldName=a.name;b.statisticType=a.type;return b});
g.outStatistics=d;f&&0<f.length&&(a=f);g.where&&0<a.length&&(g.where="("+g.where+") AND ("+e+" IN ("+a.toString()+"))");(new A(c.url)).execute(g).then(function(a){b.resolve(a)}).otherwise(function(){b.reject()});return b},selectFeaturesById:function(a){var b=a.grid,c=b.layer,b=b.layerInfo,e=a.map,d=a.ids;a=a.id;var f=new h;f.returnGeometry=!!e;f.objectIds=d||[a];b.isFeatureCollection||(f.where="1\x3d1");return c.selectFeatures(f,r.SELECTION_NEW)}};return m});