// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
require({cache:{"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),function(r,e,m,n,p,w,s,u,q,b,h,l,a,y,k,z,g,t,f,C,D,E,x){function A(d){return function(c){u[c?
"set":"remove"](this.domNode,d,c);this._set(d,c)}}a.add("dijit-legacy-requires",!y.isAsync);a.add("dojo-bidi",!1);a("dijit-legacy-requires")&&g(0,function(){r(["dijit/_base/manager"])});var B={};n=w("dijit._WidgetBase",[t,D],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:A("lang"),dir:"",_setDirAttr:A("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(d){this._set("ownerDocument",
d)},attributeMap:{},_blankGif:n.blankGif||r.toUrl("dojo/resources/blank.gif"),textDir:"",_introspect:function(){var d=this.constructor;if(!d._setterAttrs){var c=d.prototype,v=d._setterAttrs=[],d=d._onMap={},a;for(a in c.attributeMap)v.push(a);for(a in c)/^on/.test(a)&&(d[a.substring(2).toLowerCase()]=a),/^_set[A-Z](.*)Attr$/.test(a)&&(a=a.charAt(4).toLowerCase()+a.substr(5,a.length-9),(!c.attributeMap||!(a in c.attributeMap))&&v.push(a))}},postscript:function(d,c){this.create(d,c)},create:function(d,
c){this._introspect();this.srcNodeRef=s.byId(c);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&(this.srcNodeRef.id&&"string"==typeof this.srcNodeRef.id)&&(this.id=this.srcNodeRef.id);d&&(this.params=d,k.mixin(this,d));this.postMixInProperties();this.id||(this.id=x.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=C.body(this.ownerDocument);
x.add(this);this.buildRendering();var a;if(this.domNode){this._applyAttributes();var b=this.srcNodeRef;b&&(b.parentNode&&this.domNode!==b)&&(b.parentNode.replaceChild(this.domNode,b),a=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();a&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var d={},c;for(c in this.params||{})d[c]=this._get(c);e.forEach(this.constructor._setterAttrs,function(c){if(!(c in d)){var a=this._get(c);a&&this.set(c,a)}},this);for(c in d)this.set(c,
d[c])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var d=this.baseClass.split(" ");this.isLeftToRight()||(d=d.concat(e.map(d,function(d){return d+"Rtl"})));q.add(this.domNode,d)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,e.forEach(this.getChildren(),function(d){!d._started&&(!d._destroyed&&k.isFunction(d.startup))&&(d.startup(),d._started=!0)}))},
destroyRecursive:function(d){this._beingDestroyed=!0;this.destroyDescendants(d);this.destroy(d)},destroy:function(d){function c(c){c.destroyRecursive?c.destroyRecursive(d):c.destroy&&c.destroy(d)}this._beingDestroyed=!0;this.uninitialize();e.forEach(this._connects,k.hitch(this,"disconnect"));e.forEach(this._supportingWidgets,c);this.domNode&&e.forEach(x.findWidgets(this.domNode,this.containerNode),c);this.destroyRendering(d);x.remove(this.id);this._destroyed=!0},destroyRendering:function(d){this.bgIframe&&
(this.bgIframe.destroy(d),delete this.bgIframe);this.domNode&&(d?u.remove(this.domNode,"widgetId"):b.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(d||b.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(d){e.forEach(this.getChildren(),function(c){c.destroyRecursive&&c.destroyRecursive(d)})},uninitialize:function(){return!1},_setStyleAttr:function(d){var c=this.domNode;k.isObject(d)?l.set(c,d):c.style.cssText=c.style.cssText?c.style.cssText+("; "+d):d;this._set("style",
d)},_attrToDom:function(d,c,a){a=3<=arguments.length?a:this.attributeMap[d];e.forEach(k.isArray(a)?a:[a],function(a){var v=this[a.node||a||"domNode"];switch(a.type||"attribute"){case "attribute":k.isFunction(c)&&(c=k.hitch(this,c));a=a.attribute?a.attribute:/^on[A-Z][a-zA-Z]*$/.test(d)?d.toLowerCase():d;v.tagName?u.set(v,a,c):v.set(a,c);break;case "innerText":v.innerHTML="";v.appendChild(this.ownerDocument.createTextNode(c));break;case "innerHTML":v.innerHTML=c;break;case "class":q.replace(v,c,this[d]);
break;case "toggleClass":q.toggle(v,a.className||d,c)}},this)},get:function(d){var c=this._getAttrNames(d);return this[c.g]?this[c.g]():this._get(d)},set:function(d,c){if("object"===typeof d){for(var a in d)this.set(a,d[a]);return this}a=this._getAttrNames(d);var b=this[a.s];if(k.isFunction(b))var g=b.apply(this,Array.prototype.slice.call(arguments,1));else{var b=this.focusNode&&!k.isFunction(this.focusNode)?"focusNode":"domNode",f=this[b]&&this[b].tagName,l;if(l=f)if(!(l=B[f])){l=this[b];var h={},
t;for(t in l)h[t.toLowerCase()]=!0;l=B[f]=h}t=l;a=d in this.attributeMap?this.attributeMap[d]:a.s in this?this[a.s]:t&&a.l in t&&"function"!=typeof c||/^aria-|^data-|^role$/.test(d)?b:null;null!=a&&this._attrToDom(d,c,a);this._set(d,c)}return g||this},_attrPairNames:{},_getAttrNames:function(d){var a=this._attrPairNames;if(a[d])return a[d];var b=d.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()});return a[d]={n:d+"Node",s:"_set"+b+"Attr",g:"_get"+b+"Attr",l:b.toLowerCase()}},
_set:function(a,c){var b=this[a];this[a]=c;if(this._created&&!(b===c||b!==b&&c!==c))this._watchCallbacks&&this._watchCallbacks(a,b,c),this.emit("attrmodified-"+a,{detail:{prevValue:b,newValue:c}})},_get:function(a){return this[a]},emit:function(a,c,b){c=c||{};void 0===c.bubbles&&(c.bubbles=!0);void 0===c.cancelable&&(c.cancelable=!0);c.detail||(c.detail={});c.detail.widget=this;var g,l=this["on"+a];l&&(g=l.apply(this,b?b:[c]));this._started&&!this._beingDestroyed&&z.emit(this.domNode,a.toLowerCase(),
c);return g},on:function(a,c){var b=this._onMap(a);return b?m.after(this,b,c,!0):this.own(z(this.domNode,a,c))[0]},_onMap:function(a){var c=this.constructor,b=c._onMap;if(!b){var b=c._onMap={},g;for(g in c.prototype)/^on/.test(g)&&(b[g.replace(/^on/,"").toLowerCase()]=g)}return b["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?x.findWidgets(this.containerNode):[]},getParent:function(){return x.getEnclosingWidget(this.domNode.parentNode)},
connect:function(a,c,b){return this.own(p.connect(a,c,this,b))[0]},disconnect:function(a){a.remove()},subscribe:function(a,c){return this.own(f.subscribe(a,k.hitch(this,c)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir.toLowerCase():h.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=l.get(this.domNode,"display")},placeAt:function(a,c){var g=!a.tagName&&x.byId(a);g&&g.addChild&&(!c||"number"===typeof c)?g.addChild(this,
c):(g=g&&"domNode"in g?g.containerNode&&!/after|before|replace/.test(c||"")?g.containerNode:g.domNode:s.byId(a,this.ownerDocument),b.place(this.domNode,g,c),!this._started&&(this.getParent()||{})._started&&this.startup());return this},defer:function(a,c){var b=setTimeout(k.hitch(this,function(){b&&(b=null,this._destroyed||k.hitch(this,a)())}),c||0);return{remove:function(){b&&(clearTimeout(b),b=null);return null}}}});a("dojo-bidi")&&n.extend(E);return n})},"dijit/Destroyable":function(){define(["dojo/_base/array",
"dojo/aspect","dojo/_base/declare"],function(r,e,m){return m("dijit.Destroyable",null,{destroy:function(e){this._destroyed=!0},own:function(){var n=["destroyRecursive","destroy","remove"];r.forEach(arguments,function(p){function m(){u.remove();r.forEach(q,function(b){b.remove()})}var s,u=e.before(this,"destroy",function(b){p[s](b)}),q=[];p.then?(s="cancel",p.then(m,m)):r.forEach(n,function(b){"function"===typeof p[b]&&(s||(s=b),q.push(e.after(p,b,m,!0)))})},this);return arguments}})})},"dijit/_TemplatedMixin":function(){define("dojo/cache dojo/_base/declare dojo/dom-construct dojo/_base/lang dojo/on dojo/sniff dojo/string ./_AttachMixin".split(" "),
function(r,e,m,n,p,w,s,u){var q=e("dijit._TemplatedMixin",u,{templateString:null,templatePath:null,_skipNodeCache:!1,searchContainerNode:!0,_stringRepl:function(b){var h=this.declaredClass,l=this;return s.substitute(b,this,function(a,b){"!"==b.charAt(0)&&(a=n.getObject(b.substr(1),!1,l));if("undefined"==typeof a)throw Error(h+" template:"+b);return null==a?"":"!"==b.charAt(0)?a:this._escapeValue(""+a)},this)},_escapeValue:function(b){return b.replace(/["'<>&]/g,function(b){return{"\x26":"\x26amp;",
"\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;"}[b]})},buildRendering:function(){if(!this._rendered){this.templateString||(this.templateString=r(this.templatePath,{sanitize:!0}));var b=q.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),h;if(n.isString(b)){if(h=m.toDom(this._stringRepl(b),this.ownerDocument),1!=h.nodeType)throw Error("Invalid template: "+b);}else h=b.cloneNode(!0);this.domNode=h}this.inherited(arguments);this._rendered||this._fillContent(this.srcNodeRef);
this._rendered=!0},_fillContent:function(b){var h=this.containerNode;if(b&&h)for(;b.hasChildNodes();)h.appendChild(b.firstChild)}});q._templateCache={};q.getCachedTemplate=function(b,h,l){var a=q._templateCache,e=b,k=a[e];if(k){try{if(!k.ownerDocument||k.ownerDocument==(l||document))return k}catch(n){}m.destroy(k)}b=s.trim(b);if(h||b.match(/\$\{([^\}]+)\}/g))return a[e]=b;h=m.toDom(b,l);if(1!=h.nodeType)throw Error("Invalid template: "+b);return a[e]=h};w("ie")&&p(window,"unload",function(){var b=
q._templateCache,h;for(h in b){var l=b[h];"object"==typeof l&&m.destroy(l);delete b[h]}});return q})},"dojo/cache":function(){define(["./_base/kernel","./text"],function(r){return r.cache})},"dijit/_AttachMixin":function(){define("require dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/mouse dojo/on dojo/touch ./_WidgetBase".split(" "),function(r,e,m,n,p,w,s,u,q){var b=p.delegate(u,{mouseenter:w.enter,mouseleave:w.leave,keypress:m._keypress}),h;m=n("dijit._AttachMixin",
null,{constructor:function(){this._attachPoints=[];this._attachEvents=[]},buildRendering:function(){this.inherited(arguments);this._attachTemplateNodes(this.domNode);this._beforeFillContent()},_beforeFillContent:function(){},_attachTemplateNodes:function(b){for(var a=b;;)if(1==a.nodeType&&(this._processTemplateNode(a,function(a,b){return a.getAttribute(b)},this._attach)||this.searchContainerNode)&&a.firstChild)a=a.firstChild;else{if(a==b)break;for(;!a.nextSibling;)if(a=a.parentNode,a==b)return;a=
a.nextSibling}},_processTemplateNode:function(b,a,h){var k=!0,e=this.attachScope||this,g=a(b,"dojoAttachPoint")||a(b,"data-dojo-attach-point");if(g)for(var t=g.split(/\s*,\s*/);g=t.shift();)p.isArray(e[g])?e[g].push(b):e[g]=b,k="containerNode"!=g,this._attachPoints.push(g);if(a=a(b,"dojoAttachEvent")||a(b,"data-dojo-attach-event")){g=a.split(/\s*,\s*/);for(t=p.trim;a=g.shift();)if(a){var f=null;-1!=a.indexOf(":")?(f=a.split(":"),a=t(f[0]),f=t(f[1])):a=t(a);f||(f=a);this._attachEvents.push(h(b,a,p.hitch(e,
f)))}}return k},_attach:function(e,a,m){a=a.replace(/^on/,"").toLowerCase();a="dijitclick"==a?h||(h=r("./a11yclick")):b[a]||a;return s(e,a,m)},_detachTemplateNodes:function(){var b=this.attachScope||this;e.forEach(this._attachPoints,function(a){delete b[a]});this._attachPoints=[];e.forEach(this._attachEvents,function(a){a.remove()});this._attachEvents=[]},destroyRendering:function(){this._detachTemplateNodes();this.inherited(arguments)}});p.extend(q,{dojoAttachEvent:"",dojoAttachPoint:""});return m})},
"url:esri/dijit/templates/BasemapToggle.html":'\x3cdiv class\x3d"${theme}" role\x3d"presentation" style\x3d"display:none;"\x3e\r\n    \x3cdiv class\x3d"${_css.container}"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"_toggleNode" title\x3d"${_i18n.widgets.basemapToggle.toggle}" role\x3d"button" class\x3d"${_css.toggleButton}" tabindex\x3d"0"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e',"*noref":1}});
define("esri/dijit/BasemapToggle","require dojo/Evented dojo/_base/declare dojo/_base/lang dojo/has ../kernel dijit/_WidgetBase dijit/a11yclick dijit/_TemplatedMixin dojo/on dojo/text!./templates/BasemapToggle.html dojo/i18n!../nls/jsapi dojo/dom-class dojo/dom-style dojo/dom-construct ../basemaps".split(" "),function(r,e,m,n,p,w,s,u,q,b,h,l,a,y,k,z){r=m("esri.dijit.BasemapToggle",[s,q,e],{templateString:h,options:{theme:"BasemapToggle",map:null,visible:!0,basemap:"hybrid",defaultBasemap:"streets",
basemaps:z},constructor:function(a,b){var f=n.mixin({},this.options,a);this.domNode=b;this._i18n=l;this.set("map",f.map);this.set("theme",f.theme);this.set("visible",f.visible);this.set("basemaps",f.basemaps);this.set("basemap",f.basemap);this.set("defaultBasemap",f.defaultBasemap);this.watch("theme",this._updateThemeWatch);this.watch("visible",this._visible);this._css={container:"basemapContainer",toggleButton:"toggleButton",basemapImage:"basemapImage",basemapImageContainer:"basemapImageContainer",
basemapImageBG:"basemapBG",basemapTitle:"basemapTitle"}},postCreate:function(){this.inherited(arguments);this.own(b(this._toggleNode,u,n.hitch(this,this.toggle)))},startup:function(){this.inherited(arguments);this.map||(this.destroy(),console.log("BasemapToggle::map required"));if(this.map.loaded)this._init();else b.once(this.map,"load",n.hitch(this,function(){this._init()}))},destroy:function(){this.inherited(arguments)},show:function(){this.set("visible",!0)},hide:function(){this.set("visible",
!1)},toggle:function(){var a=this.map.getBasemap();a&&this.set("defaultBasemap",a);var a=this.get("defaultBasemap"),b=this.get("basemap"),f={previousBasemap:a,currentBasemap:b};a!==b?(this.map.setBasemap(b),this.set("basemap",a),this._basemapChange()):f.error=Error("BasemapToggle::Current basemap is same as new basemap");this.emit("toggle",f)},_init:function(){this._visible();this._basemapChange();this.own(b(this.map,"basemap-change",n.hitch(this,function(){this._basemapChange()})));this.set("loaded",
!0);this.emit("load",{})},_getBasemapInfo:function(a){var b=this.get("basemaps");if(b&&b.hasOwnProperty(a))return b[a]},_updateImage:function(){var a=this.get("basemap"),a=this._getBasemapInfo(a),b=a.thumbnailUrl,f;f=""+('\x3cdiv class\x3d"'+this._css.basemapImageContainer+'"\x3e');f+='\x3cdiv class\x3d"'+this._css.basemapImage+'"\x3e\x3cdiv class\x3d"'+this._css.basemapImageBG+'" style\x3d"background-image:url('+b+')" title\x3d"'+a.title+'"\x3e\x3c/div\x3e\x3c/div\x3e';f+='\x3cdiv title\x3d"'+a.title+
'" class\x3d"'+this._css.basemapTitle+'"\x3e'+a.title+"\x3c/div\x3e";f+="\x3cdiv\x3e";k.empty(this._toggleNode);k.place(f,this._toggleNode,"only")},_basemapChange:function(){var b=this.map.getBasemap();b&&this.set("defaultBasemap",b);var b=this.get("defaultBasemap"),e=this.get("basemap");this._updateImage();a.remove(this._toggleNode,b);a.add(this._toggleNode,e)},_updateThemeWatch:function(b,e,f){this.get("loaded")&&(a.remove(this.domNode,e),a.add(this.domNode,f))},_visible:function(){this.get("visible")?
y.set(this.domNode,"display","block"):y.set(this.domNode,"display","none")}});p("extend-esri")&&n.setObject("dijit.BasemapToggle",r,w);return r});