// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
require({cache:{"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),function(m,f,g,s,n,r,p,t,h,b,e,l,a,x,k,w,q,A,B,C,D,E,v){function y(d){return function(c){t[c?
"set":"remove"](this.domNode,d,c);this._set(d,c)}}a.add("dijit-legacy-requires",!x.isAsync);a.add("dojo-bidi",!1);a("dijit-legacy-requires")&&q(0,function(){m(["dijit/_base/manager"])});var z={};s=r("dijit._WidgetBase",[A,D],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:y("lang"),dir:"",_setDirAttr:y("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(d){this._set("ownerDocument",
d)},attributeMap:{},_blankGif:s.blankGif||m.toUrl("dojo/resources/blank.gif"),textDir:"",_introspect:function(){var d=this.constructor;if(!d._setterAttrs){var c=d.prototype,u=d._setterAttrs=[],d=d._onMap={},a;for(a in c.attributeMap)u.push(a);for(a in c)/^on/.test(a)&&(d[a.substring(2).toLowerCase()]=a),/^_set[A-Z](.*)Attr$/.test(a)&&(a=a.charAt(4).toLowerCase()+a.substr(5,a.length-9),(!c.attributeMap||!(a in c.attributeMap))&&u.push(a))}},postscript:function(d,c){this.create(d,c)},create:function(d,
c){this._introspect();this.srcNodeRef=p.byId(c);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&(this.srcNodeRef.id&&"string"==typeof this.srcNodeRef.id)&&(this.id=this.srcNodeRef.id);d&&(this.params=d,k.mixin(this,d));this.postMixInProperties();this.id||(this.id=v.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=C.body(this.ownerDocument);
v.add(this);this.buildRendering();var a;if(this.domNode){this._applyAttributes();var b=this.srcNodeRef;b&&(b.parentNode&&this.domNode!==b)&&(b.parentNode.replaceChild(this.domNode,b),a=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();a&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var d={},c;for(c in this.params||{})d[c]=this._get(c);f.forEach(this.constructor._setterAttrs,function(c){if(!(c in d)){var a=this._get(c);a&&this.set(c,a)}},this);for(c in d)this.set(c,
d[c])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var d=this.baseClass.split(" ");this.isLeftToRight()||(d=d.concat(f.map(d,function(d){return d+"Rtl"})));h.add(this.domNode,d)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,f.forEach(this.getChildren(),function(d){!d._started&&(!d._destroyed&&k.isFunction(d.startup))&&(d.startup(),d._started=!0)}))},
destroyRecursive:function(d){this._beingDestroyed=!0;this.destroyDescendants(d);this.destroy(d)},destroy:function(d){function c(c){c.destroyRecursive?c.destroyRecursive(d):c.destroy&&c.destroy(d)}this._beingDestroyed=!0;this.uninitialize();f.forEach(this._connects,k.hitch(this,"disconnect"));f.forEach(this._supportingWidgets,c);this.domNode&&f.forEach(v.findWidgets(this.domNode,this.containerNode),c);this.destroyRendering(d);v.remove(this.id);this._destroyed=!0},destroyRendering:function(d){this.bgIframe&&
(this.bgIframe.destroy(d),delete this.bgIframe);this.domNode&&(d?t.remove(this.domNode,"widgetId"):b.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(d||b.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(d){f.forEach(this.getChildren(),function(c){c.destroyRecursive&&c.destroyRecursive(d)})},uninitialize:function(){return!1},_setStyleAttr:function(d){var c=this.domNode;k.isObject(d)?l.set(c,d):c.style.cssText=c.style.cssText?c.style.cssText+("; "+d):d;this._set("style",
d)},_attrToDom:function(d,c,a){a=3<=arguments.length?a:this.attributeMap[d];f.forEach(k.isArray(a)?a:[a],function(a){var u=this[a.node||a||"domNode"];switch(a.type||"attribute"){case "attribute":k.isFunction(c)&&(c=k.hitch(this,c));a=a.attribute?a.attribute:/^on[A-Z][a-zA-Z]*$/.test(d)?d.toLowerCase():d;u.tagName?t.set(u,a,c):u.set(a,c);break;case "innerText":u.innerHTML="";u.appendChild(this.ownerDocument.createTextNode(c));break;case "innerHTML":u.innerHTML=c;break;case "class":h.replace(u,c,this[d]);
break;case "toggleClass":h.toggle(u,a.className||d,c)}},this)},get:function(d){var c=this._getAttrNames(d);return this[c.g]?this[c.g]():this._get(d)},set:function(d,c){if("object"===typeof d){for(var a in d)this.set(a,d[a]);return this}a=this._getAttrNames(d);var b=this[a.s];if(k.isFunction(b))var q=b.apply(this,Array.prototype.slice.call(arguments,1));else{var b=this.focusNode&&!k.isFunction(this.focusNode)?"focusNode":"domNode",l=this[b]&&this[b].tagName,e;if(e=l)if(!(e=z[l])){e=this[b];var w={},
g;for(g in e)w[g.toLowerCase()]=!0;e=z[l]=w}g=e;a=d in this.attributeMap?this.attributeMap[d]:a.s in this?this[a.s]:g&&a.l in g&&"function"!=typeof c||/^aria-|^data-|^role$/.test(d)?b:null;null!=a&&this._attrToDom(d,c,a);this._set(d,c)}return q||this},_attrPairNames:{},_getAttrNames:function(d){var a=this._attrPairNames;if(a[d])return a[d];var b=d.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()});return a[d]={n:d+"Node",s:"_set"+b+"Attr",g:"_get"+b+"Attr",l:b.toLowerCase()}},
_set:function(a,c){var b=this[a];this[a]=c;if(this._created&&!(b===c||b!==b&&c!==c))this._watchCallbacks&&this._watchCallbacks(a,b,c),this.emit("attrmodified-"+a,{detail:{prevValue:b,newValue:c}})},_get:function(a){return this[a]},emit:function(a,c,b){c=c||{};void 0===c.bubbles&&(c.bubbles=!0);void 0===c.cancelable&&(c.cancelable=!0);c.detail||(c.detail={});c.detail.widget=this;var e,l=this["on"+a];l&&(e=l.apply(this,b?b:[c]));this._started&&!this._beingDestroyed&&w.emit(this.domNode,a.toLowerCase(),
c);return e},on:function(a,c){var b=this._onMap(a);return b?g.after(this,b,c,!0):this.own(w(this.domNode,a,c))[0]},_onMap:function(a){var c=this.constructor,b=c._onMap;if(!b){var b=c._onMap={},e;for(e in c.prototype)/^on/.test(e)&&(b[e.replace(/^on/,"").toLowerCase()]=e)}return b["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?v.findWidgets(this.containerNode):[]},getParent:function(){return v.getEnclosingWidget(this.domNode.parentNode)},
connect:function(a,c,b){return this.own(n.connect(a,c,this,b))[0]},disconnect:function(a){a.remove()},subscribe:function(a,c){return this.own(B.subscribe(a,k.hitch(this,c)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir.toLowerCase():e.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=l.get(this.domNode,"display")},placeAt:function(a,c){var e=!a.tagName&&v.byId(a);e&&e.addChild&&(!c||"number"===typeof c)?e.addChild(this,
c):(e=e&&"domNode"in e?e.containerNode&&!/after|before|replace/.test(c||"")?e.containerNode:e.domNode:p.byId(a,this.ownerDocument),b.place(this.domNode,e,c),!this._started&&(this.getParent()||{})._started&&this.startup());return this},defer:function(a,c){var b=setTimeout(k.hitch(this,function(){b&&(b=null,this._destroyed||k.hitch(this,a)())}),c||0);return{remove:function(){b&&(clearTimeout(b),b=null);return null}}}});a("dojo-bidi")&&s.extend(E);return s})},"dijit/Destroyable":function(){define(["dojo/_base/array",
"dojo/aspect","dojo/_base/declare"],function(m,f,g){return g("dijit.Destroyable",null,{destroy:function(g){this._destroyed=!0},own:function(){var g=["destroyRecursive","destroy","remove"];m.forEach(arguments,function(n){function r(){t.remove();m.forEach(h,function(b){b.remove()})}var p,t=f.before(this,"destroy",function(b){n[p](b)}),h=[];n.then?(p="cancel",n.then(r,r)):m.forEach(g,function(b){"function"===typeof n[b]&&(p||(p=b),h.push(f.after(n,b,r,!0)))})},this);return arguments}})})},"dijit/_TemplatedMixin":function(){define("dojo/cache dojo/_base/declare dojo/dom-construct dojo/_base/lang dojo/on dojo/sniff dojo/string ./_AttachMixin".split(" "),
function(m,f,g,s,n,r,p,t){var h=f("dijit._TemplatedMixin",t,{templateString:null,templatePath:null,_skipNodeCache:!1,searchContainerNode:!0,_stringRepl:function(b){var e=this.declaredClass,l=this;return p.substitute(b,this,function(a,b){"!"==b.charAt(0)&&(a=s.getObject(b.substr(1),!1,l));if("undefined"==typeof a)throw Error(e+" template:"+b);return null==a?"":"!"==b.charAt(0)?a:this._escapeValue(""+a)},this)},_escapeValue:function(b){return b.replace(/["'<>&]/g,function(b){return{"\x26":"\x26amp;",
"\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;"}[b]})},buildRendering:function(){if(!this._rendered){this.templateString||(this.templateString=m(this.templatePath,{sanitize:!0}));var b=h.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),e;if(s.isString(b)){if(e=g.toDom(this._stringRepl(b),this.ownerDocument),1!=e.nodeType)throw Error("Invalid template: "+b);}else e=b.cloneNode(!0);this.domNode=e}this.inherited(arguments);this._rendered||this._fillContent(this.srcNodeRef);
this._rendered=!0},_fillContent:function(b){var e=this.containerNode;if(b&&e)for(;b.hasChildNodes();)e.appendChild(b.firstChild)}});h._templateCache={};h.getCachedTemplate=function(b,e,l){var a=h._templateCache,f=b,k=a[f];if(k){try{if(!k.ownerDocument||k.ownerDocument==(l||document))return k}catch(w){}g.destroy(k)}b=p.trim(b);if(e||b.match(/\$\{([^\}]+)\}/g))return a[f]=b;e=g.toDom(b,l);if(1!=e.nodeType)throw Error("Invalid template: "+b);return a[f]=e};r("ie")&&n(window,"unload",function(){var b=
h._templateCache,e;for(e in b){var l=b[e];"object"==typeof l&&g.destroy(l);delete b[e]}});return h})},"dojo/cache":function(){define(["./_base/kernel","./text"],function(m){return m.cache})},"dijit/_AttachMixin":function(){define("require dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/mouse dojo/on dojo/touch ./_WidgetBase".split(" "),function(m,f,g,s,n,r,p,t,h){var b=n.delegate(t,{mouseenter:r.enter,mouseleave:r.leave,keypress:g._keypress}),e;g=s("dijit._AttachMixin",
null,{constructor:function(){this._attachPoints=[];this._attachEvents=[]},buildRendering:function(){this.inherited(arguments);this._attachTemplateNodes(this.domNode);this._beforeFillContent()},_beforeFillContent:function(){},_attachTemplateNodes:function(b){for(var a=b;;)if(1==a.nodeType&&(this._processTemplateNode(a,function(a,b){return a.getAttribute(b)},this._attach)||this.searchContainerNode)&&a.firstChild)a=a.firstChild;else{if(a==b)break;for(;!a.nextSibling;)if(a=a.parentNode,a==b)return;a=
a.nextSibling}},_processTemplateNode:function(b,a,e){var k=!0,g=this.attachScope||this,q=a(b,"dojoAttachPoint")||a(b,"data-dojo-attach-point");if(q)for(var f=q.split(/\s*,\s*/);q=f.shift();)n.isArray(g[q])?g[q].push(b):g[q]=b,k="containerNode"!=q,this._attachPoints.push(q);if(a=a(b,"dojoAttachEvent")||a(b,"data-dojo-attach-event")){q=a.split(/\s*,\s*/);for(f=n.trim;a=q.shift();)if(a){var h=null;-1!=a.indexOf(":")?(h=a.split(":"),a=f(h[0]),h=f(h[1])):a=f(a);h||(h=a);this._attachEvents.push(e(b,a,n.hitch(g,
h)))}}return k},_attach:function(g,a,f){a=a.replace(/^on/,"").toLowerCase();a="dijitclick"==a?e||(e=m("./a11yclick")):b[a]||a;return p(g,a,f)},_detachTemplateNodes:function(){var b=this.attachScope||this;f.forEach(this._attachPoints,function(a){delete b[a]});this._attachPoints=[];f.forEach(this._attachEvents,function(a){a.remove()});this._attachEvents=[]},destroyRendering:function(){this._detachTemplateNodes();this.inherited(arguments)}});n.extend(h,{dojoAttachEvent:"",dojoAttachPoint:""});return g})},
"url:esri/dijit/templates/HomeButton.html":'\x3cdiv class\x3d"${theme}" role\x3d"presentation"\x3e\r\n    \x3cdiv class\x3d"${_css.container}"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"_homeNode" title\x3d"${_i18n.widgets.homeButton.home.title}" role\x3d"button" class\x3d"${_css.home}" tabindex\x3d"0"\x3e\x3cspan\x3e${_i18n.widgets.homeButton.home.button}\x3c/span\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e',"*noref":1}});
define("esri/dijit/HomeButton","dojo/Evented dojo/_base/declare dojo/_base/lang dojo/has ../kernel dijit/_WidgetBase dijit/a11yclick dijit/_TemplatedMixin dojo/on dojo/Deferred dojo/text!./templates/HomeButton.html dojo/i18n!../nls/jsapi dojo/dom-class dojo/dom-style".split(" "),function(m,f,g,s,n,r,p,t,h,b,e,l,a,x){m=f("esri.dijit.HomeButton",[r,t,m],{templateString:e,options:{theme:"HomeButton",map:null,extent:null,fit:!1,visible:!0},constructor:function(a,b){var e=g.mixin({},this.options,a);this.domNode=
b;this._i18n=l;this.set("map",e.map);this.set("theme",e.theme);this.set("visible",e.visible);this.set("extent",e.extent);this.set("fit",e.fit);this.watch("theme",this._updateThemeWatch);this.watch("visible",this._visible);this._css={container:"homeContainer",home:"home",loading:"loading"}},postCreate:function(){this.inherited(arguments);this.own(h(this._homeNode,p,g.hitch(this,this.home)))},startup:function(){this.inherited(arguments);this.map||(this.destroy(),console.log("HomeButton::map required"));
if(this.map.loaded)this._init();else h.once(this.map,"load",g.hitch(this,function(){this._init()}))},destroy:function(){this.inherited(arguments)},home:function(){var a=new b,e=this.get("extent");this._showLoading();var f={extent:e};e?this.map.extent!==e?this.map.setExtent(e,this.get("fit")).then(g.hitch(this,function(){this._hideLoading();this.emit("home",f);a.resolve(f)}),g.hitch(this,function(b){b||(b=Error("HomeButton::Error setting map extent"));f.error=b;this.emit("home",f);a.reject(b)})):(this._hideLoading(),
this.emit("home",f),a.resolve(f)):(this._hideLoading(),e=Error("HomeButton::home extent is undefined"),f.error=e,this.emit("home",f),a.reject(e));return a.promise},show:function(){this.set("visible",!0)},hide:function(){this.set("visible",!1)},_init:function(){this._visible();this.get("extent")||this.set("extent",this.map.extent);this.set("loaded",!0);this.emit("load",{})},_showLoading:function(){a.add(this._homeNode,this._css.loading)},_hideLoading:function(){a.remove(this._homeNode,this._css.loading)},
_updateThemeWatch:function(b,e,f){a.remove(this.domNode,e);a.add(this.domNode,f)},_visible:function(){this.get("visible")?x.set(this.domNode,"display","block"):x.set(this.domNode,"display","none")}});s("extend-esri")&&g.setObject("dijit.HomeButton",m,n);return m});