// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
require({cache:{"dojo/debounce":function(){define([],function(){return function(h,n){var k;return function(){k&&clearTimeout(k);var e=this,l=arguments;k=setTimeout(function(){h.apply(e,l)},n)}}})},"dojo/DeferredList":function(){define(["./_base/kernel","./_base/Deferred","./_base/array"],function(h,n,k){h.DeferredList=function(e,l,f,m,d){var c=[];n.call(this);var h=this;0===e.length&&!l&&this.resolve([0,[]]);var z=0;k.forEach(e,function(d,k){function a(a,d){c[k]=[a,d];z++;z===e.length&&h.resolve(c)}
d.then(function(c){l?h.resolve([k,c]):a(!0,c)},function(c){f?h.reject(c):a(!1,c);if(m)return null;throw c;})})};h.DeferredList.prototype=new n;h.DeferredList.prototype.gatherResults=function(e){e=new h.DeferredList(e,!1,!0,!1);e.addCallback(function(e){var f=[];k.forEach(e,function(e){f.push(e[1])});return f});return e};return h.DeferredList})},"dijit/_Widget":function(){define("dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/has dojo/_base/kernel dojo/_base/lang dojo/query dojo/ready ./registry ./_WidgetBase ./_OnDijitClickMixin ./_FocusMixin dojo/uacss ./hccss".split(" "),
function(h,n,k,e,l,f,m,d,c,K,z,t,r){function a(){}function s(c){return function(d,q,v,e){return d&&"string"==typeof q&&d[q]==a?d.on(q.substring(2).toLowerCase(),m.hitch(v,e)):c.apply(k,arguments)}}h.around(k,"connect",s);f.connect&&h.around(f,"connect",s);h=e("dijit._Widget",[z,t,r],{onClick:a,onDblClick:a,onKeyDown:a,onKeyPress:a,onKeyUp:a,onMouseDown:a,onMouseMove:a,onMouseOut:a,onMouseOver:a,onMouseLeave:a,onMouseEnter:a,onMouseUp:a,constructor:function(c){this._toConnect={};for(var d in c)this[d]===
a&&(this._toConnect[d.replace(/^on/,"").toLowerCase()]=c[d],delete c[d])},postCreate:function(){this.inherited(arguments);for(var a in this._toConnect)this.on(a,this._toConnect[a]);delete this._toConnect},on:function(c,d){return this[this._onMap(c)]===a?k.connect(this.domNode,c.toLowerCase(),this,d):this.inherited(arguments)},_setFocusedAttr:function(a){this._focused=a;this._set("focused",a)},setAttribute:function(a,c){f.deprecated(this.declaredClass+"::setAttribute(attr, value) is deprecated. Use set() instead.",
"","2.0");this.set(a,c)},attr:function(a,c){return 2<=arguments.length||"object"===typeof a?this.set.apply(this,arguments):this.get(a)},getDescendants:function(){f.deprecated(this.declaredClass+"::getDescendants() is deprecated. Use getChildren() instead.","","2.0");return this.containerNode?d("[widgetId]",this.containerNode).map(K.byNode):[]},_onShow:function(){this.onShow()},onShow:function(){},onHide:function(){},onClose:function(){return!0}});l("dijit-legacy-requires")&&c(0,function(){require(["dijit/_base"])});
return h})},"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),function(h,n,k,e,l,f,m,d,c,K,z,t,r,a,s,A,E,q,v,w,M,Q,F){function H(a){return function(c){d[c?
"set":"remove"](this.domNode,a,c);this._set(a,c)}}r.add("dijit-legacy-requires",!a.isAsync);r.add("dojo-bidi",!1);r("dijit-legacy-requires")&&E(0,function(){h(["dijit/_base/manager"])});var C={};e=f("dijit._WidgetBase",[q,M],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:H("lang"),dir:"",_setDirAttr:H("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(a){this._set("ownerDocument",
a)},attributeMap:{},_blankGif:e.blankGif||h.toUrl("dojo/resources/blank.gif"),textDir:"",_introspect:function(){var a=this.constructor;if(!a._setterAttrs){var c=a.prototype,d=a._setterAttrs=[],a=a._onMap={},q;for(q in c.attributeMap)d.push(q);for(q in c)/^on/.test(q)&&(a[q.substring(2).toLowerCase()]=q),/^_set[A-Z](.*)Attr$/.test(q)&&(q=q.charAt(4).toLowerCase()+q.substr(5,q.length-9),(!c.attributeMap||!(q in c.attributeMap))&&d.push(q))}},postscript:function(a,c){this.create(a,c)},create:function(a,
c){this._introspect();this.srcNodeRef=m.byId(c);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&(this.srcNodeRef.id&&"string"==typeof this.srcNodeRef.id)&&(this.id=this.srcNodeRef.id);a&&(this.params=a,s.mixin(this,a));this.postMixInProperties();this.id||(this.id=F.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=w.body(this.ownerDocument);
F.add(this);this.buildRendering();var q;if(this.domNode){this._applyAttributes();var d=this.srcNodeRef;d&&(d.parentNode&&this.domNode!==d)&&(d.parentNode.replaceChild(this.domNode,d),q=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();q&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var a={},c;for(c in this.params||{})a[c]=this._get(c);n.forEach(this.constructor._setterAttrs,function(c){if(!(c in a)){var d=this._get(c);d&&this.set(c,d)}},this);for(c in a)this.set(c,
a[c])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var a=this.baseClass.split(" ");this.isLeftToRight()||(a=a.concat(n.map(a,function(a){return a+"Rtl"})));c.add(this.domNode,a)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,n.forEach(this.getChildren(),function(a){!a._started&&(!a._destroyed&&s.isFunction(a.startup))&&(a.startup(),a._started=!0)}))},
destroyRecursive:function(a){this._beingDestroyed=!0;this.destroyDescendants(a);this.destroy(a)},destroy:function(a){function c(d){d.destroyRecursive?d.destroyRecursive(a):d.destroy&&d.destroy(a)}this._beingDestroyed=!0;this.uninitialize();n.forEach(this._connects,s.hitch(this,"disconnect"));n.forEach(this._supportingWidgets,c);this.domNode&&n.forEach(F.findWidgets(this.domNode,this.containerNode),c);this.destroyRendering(a);F.remove(this.id);this._destroyed=!0},destroyRendering:function(a){this.bgIframe&&
(this.bgIframe.destroy(a),delete this.bgIframe);this.domNode&&(a?d.remove(this.domNode,"widgetId"):K.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(a||K.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){n.forEach(this.getChildren(),function(c){c.destroyRecursive&&c.destroyRecursive(a)})},uninitialize:function(){return!1},_setStyleAttr:function(a){var c=this.domNode;s.isObject(a)?t.set(c,a):c.style.cssText=c.style.cssText?c.style.cssText+("; "+a):a;this._set("style",
a)},_attrToDom:function(a,q,e){e=3<=arguments.length?e:this.attributeMap[a];n.forEach(s.isArray(e)?e:[e],function(e){var v=this[e.node||e||"domNode"];switch(e.type||"attribute"){case "attribute":s.isFunction(q)&&(q=s.hitch(this,q));e=e.attribute?e.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?a.toLowerCase():a;v.tagName?d.set(v,e,q):v.set(e,q);break;case "innerText":v.innerHTML="";v.appendChild(this.ownerDocument.createTextNode(q));break;case "innerHTML":v.innerHTML=q;break;case "class":c.replace(v,q,this[a]);
break;case "toggleClass":c.toggle(v,e.className||a,q)}},this)},get:function(a){var c=this._getAttrNames(a);return this[c.g]?this[c.g]():this._get(a)},set:function(a,c){if("object"===typeof a){for(var d in a)this.set(d,a[d]);return this}d=this._getAttrNames(a);var q=this[d.s];if(s.isFunction(q))var e=q.apply(this,Array.prototype.slice.call(arguments,1));else{var q=this.focusNode&&!s.isFunction(this.focusNode)?"focusNode":"domNode",v=this[q]&&this[q].tagName,m;if(m=v)if(!(m=C[v])){m=this[q];var l={},
f;for(f in m)l[f.toLowerCase()]=!0;m=C[v]=l}f=m;d=a in this.attributeMap?this.attributeMap[a]:d.s in this?this[d.s]:f&&d.l in f&&"function"!=typeof c||/^aria-|^data-|^role$/.test(a)?q:null;null!=d&&this._attrToDom(a,c,d);this._set(a,c)}return e||this},_attrPairNames:{},_getAttrNames:function(a){var c=this._attrPairNames;if(c[a])return c[a];var d=a.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()});return c[a]={n:a+"Node",s:"_set"+d+"Attr",g:"_get"+d+"Attr",l:d.toLowerCase()}},
_set:function(a,c){var d=this[a];this[a]=c;if(this._created&&!(d===c||d!==d&&c!==c))this._watchCallbacks&&this._watchCallbacks(a,d,c),this.emit("attrmodified-"+a,{detail:{prevValue:d,newValue:c}})},_get:function(a){return this[a]},emit:function(a,c,d){c=c||{};void 0===c.bubbles&&(c.bubbles=!0);void 0===c.cancelable&&(c.cancelable=!0);c.detail||(c.detail={});c.detail.widget=this;var q,e=this["on"+a];e&&(q=e.apply(this,d?d:[c]));this._started&&!this._beingDestroyed&&A.emit(this.domNode,a.toLowerCase(),
c);return q},on:function(a,c){var d=this._onMap(a);return d?k.after(this,d,c,!0):this.own(A(this.domNode,a,c))[0]},_onMap:function(a){var c=this.constructor,d=c._onMap;if(!d){var d=c._onMap={},q;for(q in c.prototype)/^on/.test(q)&&(d[q.replace(/^on/,"").toLowerCase()]=q)}return d["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?F.findWidgets(this.containerNode):[]},getParent:function(){return F.getEnclosingWidget(this.domNode.parentNode)},
connect:function(a,c,d){return this.own(l.connect(a,c,this,d))[0]},disconnect:function(a){a.remove()},subscribe:function(a,c){return this.own(v.subscribe(a,s.hitch(this,c)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir.toLowerCase():z.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=t.get(this.domNode,"display")},placeAt:function(a,c){var d=!a.tagName&&F.byId(a);d&&d.addChild&&(!c||"number"===typeof c)?d.addChild(this,
c):(d=d&&"domNode"in d?d.containerNode&&!/after|before|replace/.test(c||"")?d.containerNode:d.domNode:m.byId(a,this.ownerDocument),K.place(this.domNode,d,c),!this._started&&(this.getParent()||{})._started&&this.startup());return this},defer:function(a,c){var d=setTimeout(s.hitch(this,function(){d&&(d=null,this._destroyed||s.hitch(this,a)())}),c||0);return{remove:function(){d&&(clearTimeout(d),d=null);return null}}}});r("dojo-bidi")&&e.extend(Q);return e})},"dijit/Destroyable":function(){define(["dojo/_base/array",
"dojo/aspect","dojo/_base/declare"],function(h,n,k){return k("dijit.Destroyable",null,{destroy:function(e){this._destroyed=!0},own:function(){var e=["destroyRecursive","destroy","remove"];h.forEach(arguments,function(l){function f(){d.remove();h.forEach(c,function(c){c.remove()})}var m,d=n.before(this,"destroy",function(c){l[m](c)}),c=[];l.then?(m="cancel",l.then(f,f)):h.forEach(e,function(d){"function"===typeof l[d]&&(m||(m=d),c.push(n.after(l,d,f,!0)))})},this);return arguments}})})},"dijit/_OnDijitClickMixin":function(){define("dojo/on dojo/_base/array dojo/keys dojo/_base/declare dojo/has ./a11yclick".split(" "),
function(h,n,k,e,l,f){h=e("dijit._OnDijitClickMixin",null,{connect:function(e,d,c){return this.inherited(arguments,[e,"ondijitclick"==d?f:d,c])}});h.a11yclick=f;return h})},"dijit/_FocusMixin":function(){define(["./focus","./_WidgetBase","dojo/_base/declare","dojo/_base/lang"],function(h,n,k,e){e.extend(n,{focused:!1,onFocus:function(){},onBlur:function(){},_onFocus:function(){this.onFocus()},_onBlur:function(){this.onBlur()}});return k("dijit._FocusMixin",null,{_focusManager:h})})},"dijit/hccss":function(){define(["dojo/dom-class",
"dojo/hccss","dojo/domReady","dojo/_base/window"],function(h,n,k,e){k(function(){n("highcontrast")&&h.add(e.body(),"dijit_a11y")});return n})},"dojo/hccss":function(){define("require ./_base/config ./dom-class ./dom-style ./has ./domReady ./_base/window".split(" "),function(h,n,k,e,l,f,m){l.add("highcontrast",function(){var d=m.doc.createElement("div");try{d.style.cssText='border: 1px solid; border-color:red green; position: absolute; height: 5px; top: -999px;background-image: url("'+(n.blankGif||
h.toUrl("./resources/blank.gif"))+'");';m.body().appendChild(d);var c=e.getComputedStyle(d),f=c.backgroundImage;return c.borderTopColor==c.borderRightColor||f&&("none"==f||"url(invalid-url:)"==f)}catch(k){return console.warn("hccss: exception detecting high-contrast mode, document is likely hidden: "+k.toString()),!1}finally{8>=l("ie")?d.outerHTML="":m.body().removeChild(d)}});f(function(){l("highcontrast")&&k.add(m.body(),"dj_a11y")});return l})},"dojox/html/entities":function(){define(["dojo/_base/lang"],
function(h){var n=h.getObject("dojox.html.entities",!0),k=function(e,f){var m,d;if(f._encCache&&f._encCache.regexp&&f._encCache.mapper&&f.length==f._encCache.length)m=f._encCache.mapper,d=f._encCache.regexp;else{m={};d=["["];var c;for(c=0;c<f.length;c++)m[f[c][0]]="\x26"+f[c][1]+";",d.push(f[c][0]);d.push("]");d=RegExp(d.join(""),"g");f._encCache={mapper:m,regexp:d,length:f.length}}return e=e.replace(d,function(c){return m[c]})},e=function(e,f){var m,d;if(f._decCache&&f._decCache.regexp&&f._decCache.mapper&&
f.length==f._decCache.length)m=f._decCache.mapper,d=f._decCache.regexp;else{m={};d=["("];var c;for(c=0;c<f.length;c++){var k="\x26"+f[c][1]+";";c&&d.push("|");m[k]=f[c][0];d.push(k)}d.push(")");d=RegExp(d.join(""),"g");f._decCache={mapper:m,regexp:d,length:f.length}}return e=e.replace(d,function(c){return m[c]})};n.html=[["\x26","amp"],['"',"quot"],["\x3c","lt"],["\x3e","gt"],["\u00a0","nbsp"]];n.latin=[["\u00a1","iexcl"],["\u00a2","cent"],["\u00a3","pound"],["\u20ac","euro"],["\u00a4","curren"],
["\u00a5","yen"],["\u00a6","brvbar"],["\u00a7","sect"],["\u00a8","uml"],["\u00a9","copy"],["\u00aa","ordf"],["\u00ab","laquo"],["\u00ac","not"],["\u00ad","shy"],["\u00ae","reg"],["\u00af","macr"],["\u00b0","deg"],["\u00b1","plusmn"],["\u00b2","sup2"],["\u00b3","sup3"],["\u00b4","acute"],["\u00b5","micro"],["\u00b6","para"],["\u00b7","middot"],["\u00b8","cedil"],["\u00b9","sup1"],["\u00ba","ordm"],["\u00bb","raquo"],["\u00bc","frac14"],["\u00bd","frac12"],["\u00be","frac34"],["\u00bf","iquest"],["\u00c0",
"Agrave"],["\u00c1","Aacute"],["\u00c2","Acirc"],["\u00c3","Atilde"],["\u00c4","Auml"],["\u00c5","Aring"],["\u00c6","AElig"],["\u00c7","Ccedil"],["\u00c8","Egrave"],["\u00c9","Eacute"],["\u00ca","Ecirc"],["\u00cb","Euml"],["\u00cc","Igrave"],["\u00cd","Iacute"],["\u00ce","Icirc"],["\u00cf","Iuml"],["\u00d0","ETH"],["\u00d1","Ntilde"],["\u00d2","Ograve"],["\u00d3","Oacute"],["\u00d4","Ocirc"],["\u00d5","Otilde"],["\u00d6","Ouml"],["\u00d7","times"],["\u00d8","Oslash"],["\u00d9","Ugrave"],["\u00da",
"Uacute"],["\u00db","Ucirc"],["\u00dc","Uuml"],["\u00dd","Yacute"],["\u00de","THORN"],["\u00df","szlig"],["\u00e0","agrave"],["\u00e1","aacute"],["\u00e2","acirc"],["\u00e3","atilde"],["\u00e4","auml"],["\u00e5","aring"],["\u00e6","aelig"],["\u00e7","ccedil"],["\u00e8","egrave"],["\u00e9","eacute"],["\u00ea","ecirc"],["\u00eb","euml"],["\u00ec","igrave"],["\u00ed","iacute"],["\u00ee","icirc"],["\u00ef","iuml"],["\u00f0","eth"],["\u00f1","ntilde"],["\u00f2","ograve"],["\u00f3","oacute"],["\u00f4",
"ocirc"],["\u00f5","otilde"],["\u00f6","ouml"],["\u00f7","divide"],["\u00f8","oslash"],["\u00f9","ugrave"],["\u00fa","uacute"],["\u00fb","ucirc"],["\u00fc","uuml"],["\u00fd","yacute"],["\u00fe","thorn"],["\u00ff","yuml"],["\u0192","fnof"],["\u0391","Alpha"],["\u0392","Beta"],["\u0393","Gamma"],["\u0394","Delta"],["\u0395","Epsilon"],["\u0396","Zeta"],["\u0397","Eta"],["\u0398","Theta"],["\u0399","Iota"],["\u039a","Kappa"],["\u039b","Lambda"],["\u039c","Mu"],["\u039d","Nu"],["\u039e","Xi"],["\u039f",
"Omicron"],["\u03a0","Pi"],["\u03a1","Rho"],["\u03a3","Sigma"],["\u03a4","Tau"],["\u03a5","Upsilon"],["\u03a6","Phi"],["\u03a7","Chi"],["\u03a8","Psi"],["\u03a9","Omega"],["\u03b1","alpha"],["\u03b2","beta"],["\u03b3","gamma"],["\u03b4","delta"],["\u03b5","epsilon"],["\u03b6","zeta"],["\u03b7","eta"],["\u03b8","theta"],["\u03b9","iota"],["\u03ba","kappa"],["\u03bb","lambda"],["\u03bc","mu"],["\u03bd","nu"],["\u03be","xi"],["\u03bf","omicron"],["\u03c0","pi"],["\u03c1","rho"],["\u03c2","sigmaf"],["\u03c3",
"sigma"],["\u03c4","tau"],["\u03c5","upsilon"],["\u03c6","phi"],["\u03c7","chi"],["\u03c8","psi"],["\u03c9","omega"],["\u03d1","thetasym"],["\u03d2","upsih"],["\u03d6","piv"],["\u2022","bull"],["\u2026","hellip"],["\u2032","prime"],["\u2033","Prime"],["\u203e","oline"],["\u2044","frasl"],["\u2118","weierp"],["\u2111","image"],["\u211c","real"],["\u2122","trade"],["\u2135","alefsym"],["\u2190","larr"],["\u2191","uarr"],["\u2192","rarr"],["\u2193","darr"],["\u2194","harr"],["\u21b5","crarr"],["\u21d0",
"lArr"],["\u21d1","uArr"],["\u21d2","rArr"],["\u21d3","dArr"],["\u21d4","hArr"],["\u2200","forall"],["\u2202","part"],["\u2203","exist"],["\u2205","empty"],["\u2207","nabla"],["\u2208","isin"],["\u2209","notin"],["\u220b","ni"],["\u220f","prod"],["\u2211","sum"],["\u2212","minus"],["\u2217","lowast"],["\u221a","radic"],["\u221d","prop"],["\u221e","infin"],["\u2220","ang"],["\u2227","and"],["\u2228","or"],["\u2229","cap"],["\u222a","cup"],["\u222b","int"],["\u2234","there4"],["\u223c","sim"],["\u2245",
"cong"],["\u2248","asymp"],["\u2260","ne"],["\u2261","equiv"],["\u2264","le"],["\u2265","ge"],["\u2282","sub"],["\u2283","sup"],["\u2284","nsub"],["\u2286","sube"],["\u2287","supe"],["\u2295","oplus"],["\u2297","otimes"],["\u22a5","perp"],["\u22c5","sdot"],["\u2308","lceil"],["\u2309","rceil"],["\u230a","lfloor"],["\u230b","rfloor"],["\u2329","lang"],["\u232a","rang"],["\u25ca","loz"],["\u2660","spades"],["\u2663","clubs"],["\u2665","hearts"],["\u2666","diams"],["\u0152","OElig"],["\u0153","oelig"],
["\u0160","Scaron"],["\u0161","scaron"],["\u0178","Yuml"],["\u02c6","circ"],["\u02dc","tilde"],["\u2002","ensp"],["\u2003","emsp"],["\u2009","thinsp"],["\u200c","zwnj"],["\u200d","zwj"],["\u200e","lrm"],["\u200f","rlm"],["\u2013","ndash"],["\u2014","mdash"],["\u2018","lsquo"],["\u2019","rsquo"],["\u201a","sbquo"],["\u201c","ldquo"],["\u201d","rdquo"],["\u201e","bdquo"],["\u2020","dagger"],["\u2021","Dagger"],["\u2030","permil"],["\u2039","lsaquo"],["\u203a","rsaquo"]];n.encode=function(e,f){e&&(f?
e=k(e,f):(e=k(e,n.html),e=k(e,n.latin)));return e};n.decode=function(k,f){k&&(f?k=e(k,f):(k=e(k,n.html),k=e(k,n.latin)));return k};return n})},"esri/numberUtils":function(){define(["dojo/has","dojo/number","dojo/i18n!dojo/cldr/nls/number","./kernel"],function(h,n,k,e){var l=function(e,d){return e-d},f={_reNumber:/^-?(\d+)(\.(\d+))?$/i,getDigits:function(e){var d=String(e),c=d.match(f._reNumber);e={integer:0,fractional:0};c&&c[1]?(e.integer=c[1].split("").length,e.fractional=c[3]?c[3].split("").length:
0):-1<d.toLowerCase().indexOf("e")&&(c=d.split("e"),d=c[0],c=c[1],d&&c&&(d=Number(d),c=Number(c),(e=0<c)||(c=Math.abs(c)),d=f.getDigits(d),e?(d.integer+=c,d.fractional=c>d.fractional?0:d.fractional-c):(d.fractional+=c,d.integer=c>d.integer?1:d.integer-c),e=d));return e},getFixedNumbers:function(e,d){var c,f;c=Number(e.toFixed(d));c<e?f=c+1/Math.pow(10,d):(f=c,c-=1/Math.pow(10,d));c=Number(c.toFixed(d));f=Number(f.toFixed(d));return[c,f]},getPctChange:function(e,d,c,f){var k={prev:null,next:null},
h;null!=c&&(h=e-c,c=d-c-h,k.prev=Math.floor(Math.abs(100*c/h)));null!=f&&(h=f-e,c=f-d-h,k.next=Math.floor(Math.abs(100*c/h)));return k},round:function(e,d){var c=e.slice(0),k,h,n,r,a,s,A,E,q,v=!d||null==d.tolerance?2:d.tolerance,w=d&&d.indexes,M=!d||null==d.strictBounds?!1:d.strictBounds;if(w)w.sort(l);else{w=[];for(s=0;s<c.length;s++)w.push(s)}for(s=0;s<w.length;s++)if(q=w[s],k=c[q],h=0===q?null:c[q-1],n=q===c.length-1?null:c[q+1],r=f.getDigits(k),r=r.fractional){A=0;for(E=!1;A<=r&&!E;)a=f.getFixedNumbers(k,
A),a=M&&0===s?a[1]:a[0],E=f.hasMinimalChange(k,a,h,n,v),A++;E&&(c[q]=a)}return c},hasMinimalChange:function(e,d,c,k,h){e=f.getPctChange(e,d,c,k);d=null==e.prev||e.prev<=h;c=null==e.next||e.next<=h;return d&&c||e.prev+e.next<=2*h},_reAllZeros:RegExp("\\"+k.decimal+"0+$","g"),_reSomeZeros:RegExp("(\\d)0*$","g"),format:function(e,d){d=d||{places:20,round:-1};var c=n.format(e,d);c&&(c=c.replace(f._reSomeZeros,"$1").replace(f._reAllZeros,""));return c}};h("extend-esri")&&(e.numberUtils=f);return f})},
"esri/renderers/utils":function(){define("dojo/_base/lang dojo/_base/array dojo/has dojo/date/locale ../kernel ../numberUtils ../Color dojo/i18n!../nls/jsapi dojo/i18n!dojo/cldr/nls/gregorian".split(" "),function(h,n,k,e,l,f,m,d,c){function K(a){return a&&n.map(a,function(a){return new m(a)})}function z(a,c,d){var e="";0===c?e=r.lt+" ":c===d&&(e=r.gt+" ");return e+a}var t={},r={lte:"\x3c\x3d",gte:"\x3e\x3d",lt:"\x3c",gt:"\x3e",pct:"%"},a={millisecond:0,second:1,minute:2,hour:3,day:4,month:5,year:6},
s={millisecond:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"medium"}},second:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"medium"}},minute:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"short"}},hour:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"short"}},day:{selector:"date",dateOptions:{formatLength:"long"}},month:{selector:"date",dateOptions:{formatLength:"long"}},year:{selector:"date",dateOptions:{selector:"year"}}},A={formatLength:"short",
fullYear:!0},E={formatLength:"short"};h.mixin(t,{timelineDateFormatOptions:{selector:"date",dateOptions:{formatLength:"short",fullYear:!0}},formatDate:function(a,d){var f,k=[];null!=a&&!(a instanceof Date)&&(a=new Date(a));d=d||{};d=h.mixin({},d);var m=d.selector?d.selector.toLowerCase():null;f=!m||-1<m.indexOf("time");m=!m||-1<m.indexOf("date");f&&(d.timeOptions=d.timeOptions||E,d.timeOptions&&(d.timeOptions=h.mixin({},d.timeOptions),d.timeOptions.selector=d.timeOptions.selector||"time",k.push(d.timeOptions)));
m&&(d.dateOptions=d.dateOptions||A,d.dateOptions&&(d.dateOptions=h.mixin({},d.dateOptions),d.dateOptions.selector=d.dateOptions.selector||"date",k.push(d.dateOptions)));k&&k.length?(k=n.map(k,function(c){return e.format(a,c)}),f=1==k.length?k[0]:c["dateTimeFormat-medium"].replace(/\'/g,"").replace(/\{(\d+)\}/g,function(a,c){return k[c]})):f=e.format(a);return f},createColorStops:function(a){var c=a.values,d=a.colors,e=a.labelIndexes,k=a.isDate,h=a.dateFormatOptions;a=[];return a=n.map(c,function(a,
q){var m=null;if(!e||-1<n.indexOf(e,q)){var l;(l=k?t.formatDate(a,h):f.format(a))&&(m=z(l,q,c.length-1))}return{value:a,color:d[q],label:m}})},updateColorStops:function(a){var c=a.stops,d=a.changes,e=a.isDate,k=a.dateFormatOptions,h=[],m,l=n.map(c,function(a){return a.value});n.forEach(d,function(a){h.push(a.index);l[a.index]=a.value});m=f.round(l,{indexes:h});n.forEach(c,function(a,d){a.value=l[d];if(null!=a.label){var q,h=null;(q=e?t.formatDate(m[d],k):f.format(m[d]))&&(h=z(q,d,c.length-1));a.label=
h}})},createClassBreakLabel:function(a){var c=a.minValue,e=a.maxValue,k=a.isFirstBreak?"":r.gt+" ";a="percent-of-total"===a.normalizationType?r.pct:"";c=null==c?"":f.format(c);e=null==e?"":f.format(e);return k+c+a+" "+d.smartMapping.minToMax+" "+e+a},setLabelsForClassBreaks:function(a){var c=a.classBreaks,d=a.classificationMethod,e=a.normalizationType,k=[];c&&c.length&&("standard-deviation"===d?console.log("setLabelsForClassBreaks: cannot set labels for class breaks generated using 'standard-deviation' method."):
a.round?(k.push(c[0].minValue),n.forEach(c,function(a){k.push(a.maxValue)}),k=f.round(k),n.forEach(c,function(a,c){a.label=t.createClassBreakLabel({minValue:0===c?k[0]:k[c],maxValue:k[c+1],isFirstBreak:0===c,normalizationType:e})})):n.forEach(c,function(a,c){a.label=t.createClassBreakLabel({minValue:a.minValue,maxValue:a.maxValue,isFirstBreak:0===c,normalizationType:e})}))},updateClassBreak:function(a){var c=a.classBreaks,d=a.normalizationType,e=a.change,k=e.index,e=e.value,f=-1,h=-1,m=c.length;"standard-deviation"===
a.classificationMethod?console.log("updateClassBreak: cannot update labels for class breaks generated using 'standard-deviation' method."):(0===k?f=k:k===m?h=k-1:(h=k-1,f=k),-1<f&&f<m&&(a=c[f],a.minValue=e,a.label=t.createClassBreakLabel({minValue:a.minValue,maxValue:a.maxValue,isFirstBreak:0===f,normalizationType:d})),-1<h&&h<m&&(a=c[h],a.maxValue=e,a.label=t.createClassBreakLabel({minValue:a.minValue,maxValue:a.maxValue,isFirstBreak:0===h,normalizationType:d})))},calculateDateFormatInterval:function(c){var d,
e,k=c.length,f,h,m,l,s,r,t=Infinity,z;c=n.map(c,function(a){return new Date(a)});for(d=0;d<k-1;d++){f=c[d];m=[];s=Infinity;r="";for(e=d+1;e<k;e++)h=c[e],h=f.getFullYear()!==h.getFullYear()&&"year"||f.getMonth()!==h.getMonth()&&"month"||f.getDate()!==h.getDate()&&"day"||f.getHours()!==h.getHours()&&"hour"||f.getMinutes()!==h.getMinutes()&&"minute"||f.getSeconds()!==h.getSeconds()&&"second"||"millisecond",l=a[h],l<s&&(s=l,r=h),m.push(h);s<t&&(t=s,z=r)}return z},createUniqueValueLabel:function(a){var c=
a.value,d=a.fieldInfo,e=a.domain;a=a.dateFormatInterval;var k=String(c);(e=e&&e.codedValues?e.getName(c):null)?k=e:"number"===typeof c&&(k=d&&"esriFieldTypeDate"===d.type?t.formatDate(c,a&&s[a]):f.format(c));return k},cloneColorInfo:function(a){var c;a&&(c=h.mixin({},a),c.colors=K(c.colors),c.stops=c.stops&&n.map(c.stops,function(a){a=h.mixin({},a);a.color&&(a.color=new m(a.color));return a}),c.legendOptions&&(c.legendOptions=h.mixin({},c.legendOptions)));return c},cloneOpacityInfo:function(a){var c;
if(a){c=h.mixin({},a);if(a=c.opacityValues)c.opacityValues=a.slice(0);if(a=c.stops)c.stops=n.map(a,function(a){return h.mixin({},a)});if(a=c.legendOptions)c.legendOptions=h.mixin({},a)}return c},cloneSizeInfo:function(a){var c;if(a){c=h.mixin({},a);c.stops&&(c.stops=n.map(c.stops,function(a){return h.mixin({},a)}));if((a=c.minSize)&&"object"===typeof a)c.minSize=t.cloneSizeInfo(a);if((a=c.maxSize)&&"object"===typeof a)c.maxSize=t.cloneSizeInfo(a);if(a=c.legendOptions)if(c.legendOptions=h.mixin({},
a),a=a.customValues)c.legendOptions.customValues=a.slice(0)}return c}});k("extend-esri")&&h.setObject("renderer.utils",t,l);return t})},"esri/dijit/_EventedWidget":function(){define("dojo/_base/declare dojo/_base/lang dojo/aspect dojo/on ../Evented dijit/_WidgetBase".split(" "),function(h,n,k,e,l,f){return h([f,l],{_onMap:function(e){var d=this.constructor._onMap,c;if(!d||!d.FINAL)delete this.constructor._onMap,d=this.registerConnectEvents(),d.FINAL=!0;e=e.toLowerCase();d[e]?c=this[d[e].method]:(e=
this._onCamelCase(e),this[e]&&(c=e));return c},on:function(k,d){var c=this._onMap(k),f=k.replace(/\-/g,""),h="on"+f in this.domNode;return c||!h?this.inherited(arguments):this.own(e(this.domNode,f,d))[0]},emit:function(e,d,c){var k,f,h,l=e.toLowerCase(),a=this.constructor._onMap||this.registerConnectEvents();f=this[this._onMap(l)];d=d||{};d.target||(d.target=this);f&&(a&&a[l])&&(this._onObj2Arr(function(){k=Array.prototype.slice.call(arguments)},a[l].argKeys)(d),h=n.mixin({},arguments),h[2]=k,h[0]=
a[l].name.replace(/^on/,""));return this.inherited(h||arguments)}})})},"*noref":1}});
define("esri/dijit/Legend","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/json dojo/_base/Color dojo/debounce dojo/has dojo/sniff dojo/DeferredList dojo/json dojo/dom dojo/dom-construct dojo/dom-style dojo/dom-class dijit/_Widget dojox/gfx dojox/gfx/matrix dojox/html/entities ../kernel ../config ../request ../lang ../numberUtils ../renderers/utils ../renderers/SimpleRenderer ../renderers/UniqueValueRenderer ../renderers/ClassBreaksRenderer ../renderers/ScaleDependentRenderer ../renderers/DotDensityRenderer ../renderers/TemporalRenderer ../renderers/VectorFieldRenderer ../renderers/HeatmapRenderer ../symbols/PictureFillSymbol ../symbols/SimpleLineSymbol ../symbols/jsonUtils ./_EventedWidget dojo/i18n!../nls/jsapi".split(" "),function(h,
n,k,e,l,f,m,d,c,K,z,t,r,a,s,A,E,q,v,w,M,Q,F,H,C,R,N,S,O,W,X,Y,U,Z,$,aa,T,ba,V){var L=n([ba,E],{declaredClass:"esri.dijit.Legend",widgetsInTemplate:!1,layers:null,alignRight:!1,hoverLabelShowing:!1,dotDensitySwatchSize:26,dotCoverage:75,gradientHeight:30,transparencyRampColor:new m([64,64,64]),defaultText:"Aa",sizeRampLightColor:new m([255,255,255]),sizeRampDarkColor:new m([128,128,128]),layerConnects:[],gradientWidth:34,colorRampBorder:"1px solid",_specialChars:{lt:"\x3c",gt:"\x3e"},_ieTimer:100,
_isRightToLeft:!1,_align:null,_legendAlign:null,constructor:function(b,a){k.mixin(this,V.widgets.legend);this._i18n=V.widgets.legend;b=b||{};b.map?a?(this.map=b.map,this.layerInfos=b.layerInfos,this._respectCurrentMapScale=!1===b.respectCurrentMapScale?!1:!0,this._respectVisibility=!1===b.respectVisibility?!1:!0,this.arrangement=b.arrangement===L.ALIGN_RIGHT?L.ALIGN_RIGHT:L.ALIGN_LEFT,this.arrangement===L.ALIGN_RIGHT&&(this.alignRight=!0),this.autoUpdate=!1===b.autoUpdate?!1:!0,this._surfaceItems=
[],this.hideLayersInLegend={},this.refresh=d(this.refresh,0)):console.error("esri.dijit.Legend: must specify a container for the legend"):console.error("esri.dijit.Legend: unable to find the 'map' property in parameters")},postMixInProperties:function(){this.inherited(arguments);var b=["ar","he"],a,c;for(a=0;a<b.length;a+=1)c=b[a],h.locale&&-1!==h.locale.indexOf(c)&&(-1!==h.locale.indexOf("-")?-1!==h.locale.indexOf(c+"-")&&(this._isRightToLeft=!0):this._isRightToLeft=!0);this._isRightToLeft?(this._align=
this.alignRight?"left":"right",this._legendAlign=this.alignRight?"esriLegendLeft":"esriLegendRight"):(this._align=this.alignRight?"right":"left",this._legendAlign=this.alignRight?"esriLegendRight":"esriLegendLeft")},startup:function(){this.inherited(arguments);this._initialize();9>c("ie")&&(this._repaintItems=k.hitch(this,this._repaintItems),setTimeout(this._repaintItems,this._ieTimer))},destroy:function(){this._deactivate();this._removeHoverHandlers();this.inherited(arguments)},refresh:function(b){if(this.domNode){b?
(this.layerInfos=b,this.layers=[],e.forEach(this.layerInfos,function(b){this._isSupportedLayerType(b.layer)&&(b.title&&(b.layer._titleForLegend=b.title),b.layer._hideDefaultSymbol=!1===b.defaultSymbol?!0:!1,b.hideLayers?(this.hideLayersInLegend[b.layer.id]=b.hideLayers,this._addSubLayersToHide(b)):this.hideLayersInLegend[b.layer.id]=[],b.hoverLabel&&(b.layer._hoverLabel=b.hoverLabel),b.hoverLabels&&(b.layer._hoverLabels=b.hoverLabels),this.layers.push(b.layer))},this)):this.useAllMapLayers&&(this.layers=
this.layerInfos=null);for(b=this.domNode.children.length-1;0<=b;b--)a.destroy(this.domNode.children[b]);this._removeHoverHandlers();this.startup()}},_legendUrl:"http://utility.arcgis.com/sharing/tools/legend",_initialize:function(){this.layerInfos&&(this.layers=[],e.forEach(this.layerInfos,function(b){this._isSupportedLayerType(b.layer)&&(b.title&&(b.layer._titleForLegend=b.title),b.layer._hideDefaultSymbol=!1===b.defaultSymbol?!0:!1,b.hideLayers?(this.hideLayersInLegend[b.layer.id]=b.hideLayers,
this._addSubLayersToHide(b)):this.hideLayersInLegend[b.layer.id]=[],b.hoverLabel&&(b.layer._hoverLabel=b.hoverLabel),b.hoverLabels&&(b.layer._hoverLabels=b.hoverLabels),this.layers.push(b.layer))},this));this.useAllMapLayers=!1;if(!this.layers){this.useAllMapLayers=!0;this.layers=[];var b=[],a=[];e.forEach(this.map.layerIds,function(c){c=this.map.getLayer(c);var d;this._isSupportedLayerType(c)&&(c.arcgisProps&&c.arcgisProps.title&&(c._titleForLegend=c.arcgisProps.title),this.layers.push(c));"esri.layers.KMLLayer"==
c.declaredClass&&(d=c.getLayers(),e.forEach(d,function(a){b.push(a.id)},this));"esri.layers.GeoRSSLayer"==c.declaredClass&&(d=c.getFeatureLayers(),e.forEach(d,function(b){a.push(b.id)},this))},this);e.forEach(this.map.graphicsLayerIds,function(c){var d=this.map.getLayer(c);-1==e.indexOf(b,c)&&-1==e.indexOf(a,c)&&(this._isSupportedLayerType(d)&&d._params&&d._params.drawMode)&&(d.arcgisProps&&d.arcgisProps.title&&(d._titleForLegend=d.arcgisProps.title),this.layers.push(d))},this)}this._createLegend()},
_activate:function(){this._deactivate();this.autoUpdate&&(this._respectCurrentMapScale&&(this._ozeConnect=l.connect(this.map,"onZoomEnd",this,"_refreshLayers")),this.useAllMapLayers&&(this._olaConnect=l.connect(this.map,"onLayerAdd",this,"_updateAllMapLayers"),this._olrConnect=l.connect(this.map,"onLayerRemove",this,"_updateAllMapLayers"),this._olroConnect=l.connect(this.map,"onLayersReordered",this,"_updateAllMapLayers")),e.forEach(this.layers,function(b){var a={};a.ovcConnect=l.connect(b,"onVisibilityChange",
this,"_refreshLayers");a.oocConnect=l.connect(b,"onOpacityChange",this,"_refreshLayers");a.oscConnect=l.connect(b,"onScaleRangeChange",this,"_refreshLayers");"esri.layers.ArcGISDynamicMapServiceLayer"===b.declaredClass&&b.supportsDynamicLayers&&(a.odcConnect=l.connect(b,"_onDynamicLayersChange",k.hitch(this,"_updateDynamicLayers",b)));"esri.layers.ArcGISImageServiceLayer"===b.declaredClass&&(a.oirConnect=l.connect(b,"onRenderingChange",k.partial(this._updateImageServiceLayers,this,b)));"esri.layers.ArcGISImageServiceVectorLayer"===
b.declaredClass&&(a.oivrConnect=l.connect(b,"onRendererChange",k.hitch(this,"_refreshLayers")));this.layerConnects[b.id]=a},this))},_deactivate:function(){this._ozeConnect&&l.disconnect(this._ozeConnect);this._olaConnect&&l.disconnect(this._olaConnect);this._olroConnect&&l.disconnect(this._olroConnect);this._olrConnect&&l.disconnect(this._olrConnect);e.forEach(this.layers,function(b){b=this.layerConnects[b.id]||{};b.ovcConnect&&l.disconnect(b.ovcConnect);b.oocConnect&&l.disconnect(b.oocConnect);b.oscConnect&&
l.disconnect(b.oscConnect);b.odcConnect&&l.disconnect(b.odcConnect);b.oirConnect&&l.disconnect(b.oirConnect);b.oivrConnect&&l.disconnect(b.oivrConnect)},this);this.layerConnects=[]},_updateDynamicLayers:function(b){delete b.legendResponse;this._refreshLayers()},_updateImageServiceLayers:function(b,a){delete a.legendResponse;b._refreshLayers()},_refreshLayers:function(){this.refresh()},_updateAllMapLayers:function(){this.layers=[];e.forEach(this.map.layerIds,function(b){b=this.map.getLayer(b);this._isSupportedLayerType(b)&&
this.layers.push(b)},this);e.forEach(this.map.graphicsLayerIds,function(b){b=this.map.getLayer(b);this._isSupportedLayerType(b)&&(b._params&&b._params.drawMode)&&this.layers.push(b)},this);this.refresh()},_createLegend:function(){var b=!1,G=!1;s.set(this.domNode,"position","relative");a.create("div",{id:this.id+"_msg",className:"esriLegendMsg",innerHTML:this.NLS_creatingLegend+"..."},this.domNode);var c=[];e.forEach(this.layers,function(g){if("esri.layers.KMLLayer"==g.declaredClass||"esri.layers.GeoRSSLayer"==
g.declaredClass){var d;g.loaded?("esri.layers.KMLLayer"==g.declaredClass?d=g.getLayers():"esri.layers.GeoRSSLayer"==g.declaredClass&&(d=g.getFeatureLayers(),this.hideLayersInLegend[g.id]&&(d=e.filter(d,function(b){return-1==e.indexOf(this.hideLayersInLegend[g.id],b.id)},this))),e.forEach(d,function(b){"esri.layers.FeatureLayer"==b.declaredClass&&g._titleForLegend&&(b._titleForLegend=g._titleForLegend+" - ","esriGeometryPoint"==b.geometryType?b._titleForLegend+=this.NLS_points:"esriGeometryPolyline"==
b.geometryType?b._titleForLegend+=this.NLS_lines:"esriGeometryPolygon"==b.geometryType&&(b._titleForLegend+=this.NLS_polygons),c.push(b))},this)):l.connect(g,"onLoad",k.hitch(this,function(){this.refresh(this.layerInfos)}))}else if("esri.layers.WMSLayer"===g.declaredClass)if(g.loaded){if((!this._respectVisibility||this._respectVisibility&&g.visible)&&0<g.layerInfos.length&&e.some(g.layerInfos,function(b){return b.legendURL})){var B=!1;e.forEach(g.layerInfos,function(c){if(c.legendURL&&-1<e.indexOf(g.visibleLayers,
c.name)){B||(a.create("div",{innerHTML:"\x3cspan class\x3d'esriLegendServiceLabel'\x3e"+(g._titleForLegend||g.name||g.id)+"\x3c/span\x3e"},this.domNode),B=!0);var G;c=c.legendURL;if(g.customParameters||g.customLayerParameters){var d=k.clone(g.customParameters||{});k.mixin(d,g.customLayerParameters||{});for(G in d)c+=(-1===c.indexOf("?")?"?":"\x26")+G+"\x3d"+d[G]}a.create("div",{innerHTML:"\x3cimg src\x3d'"+c+"'/\x3e"},this.domNode);b=!0}},this)}}else l.connect(g,"onLoad",k.hitch(this,function(){this.refresh(this.layerInfos)}));
else"esri.layers.WFSLayer"===g.declaredClass&&!g.renderer?(d=a.create("div",{id:this.id+"_"+g.id,"class":"esriLegendService"}),a.create("span",{innerHTML:this._getServiceTitle(g),"class":"esriLegendServiceLabel"},a.create("td",{align:this._align},a.create("tr",{},a.create("tbody",{},a.create("table",{width:"95%"},d))))),a.place(d,this.id,"first"),tableNode=a.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d),tableBody=a.create("tbody",{},tableNode),"esriGeometryComplex"===
g.geometryType?(this._buildRow_Renderer(g,g._pointSymbol,null,this.NLS_points,null,tableBody),this._buildRow_Renderer(g,g._lineSymbol,null,this.NLS_lines,null,tableBody),this._buildRow_Renderer(g,g._polygonSymbol,null,this.NLS_areas,null,tableBody)):"esriGeometryPoint"===g.geometryType?this._buildRow_Renderer(g,g._pointSymbol,null,"",null,tableBody):"esriGeometryPolyline"===g.geometryType?this._buildRow_Renderer(g,g._lineSymbol,null,"",null,tableBody):"esriGeometryPolygon"===g.geometryType&&this._buildRow_Renderer(g,
g._polygonSymbol,null,"",null,tableBody),G=!0):c.push(g)},this);var d=[];e.forEach(c,function(b){if(b.loaded){if((!this._respectVisibility||this._respectVisibility&&b.visible)&&(b.layerInfos||b.renderer||"esri.layers.ArcGISImageServiceLayer"==b.declaredClass)){var c=a.create("div",{id:this.id+"_"+b.id,style:{display:"none"},"class":"esriLegendService"});a.create("span",{innerHTML:this._getServiceTitle(b),"class":"esriLegendServiceLabel"},a.create("td",{align:this._align},a.create("tr",{},a.create("tbody",
{},a.create("table",{width:"95%"},c)))));a.place(c,this.id,"first");b.legendResponse||b.renderer?this._createLegendForLayer(b):d.push(this._legendRequest(b))}}else var G=l.connect(b,"onLoad",this,function(b){l.disconnect(G);G=null;this.refresh()})},this);0===d.length&&!b&&!G?(r.byId(this.id+"_msg").innerHTML=this.NLS_noLegend,this._activate()):(new z(d)).addCallback(k.hitch(this,function(a){!b&&!G?r.byId(this.id+"_msg").innerHTML=this.NLS_noLegend:r.byId(this.id+"_msg").innerHTML="";this._activate()}))},
_createLegendForLayer:function(b){if(b.legendResponse||b.renderer){var a=!1;if(b.legendResponse){var c=b.dynamicLayerInfos||b.layerInfos;c&&c.length?e.forEach(c,function(c,d){if(!this.hideLayersInLegend[b.id]||-1===e.indexOf(this.hideLayersInLegend[b.id],c.id)){var I=this._buildLegendItems(b,c,d);a=a||I}},this):"esri.layers.ArcGISImageServiceLayer"==b.declaredClass&&(a=this._buildLegendItems(b,{id:0,name:null,title:b.name,subLayerIds:null,parentLayerId:-1},0))}else b.renderer&&(c=b.url?b.url.substring(b.url.lastIndexOf("/")+
1,b.url.length):"fc_"+b.id,a=this._buildLegendItems(b,{id:c,name:null,subLayerIds:null,parentLayerId:-1},0));a&&(s.set(r.byId(this.id+"_"+b.id),"display","block"),s.set(r.byId(this.id+"_msg"),"display","none"))}},_legendRequest:function(b){if(b.loaded)return 10.01<=b.version?this._legendRequestServer(b):this._legendRequestTools(b);l.connect(b,"onLoad",k.hitch(this,"_legendRequest"))},_legendRequestServer:function(b){var a=b.url,c=a.indexOf("?"),a=-1<c?a.substring(0,c)+"/legend"+a.substring(c):a+"/legend";
(c=b._getToken())&&(a+="?token\x3d"+c);var d=k.hitch(this,"_processLegendResponse"),g={f:"json"};b._params.dynamicLayers&&(g.dynamicLayers=t.stringify(this._createDynamicLayers(b)),"[{}]"===g.dynamicLayers&&(g.dynamicLayers="[]"));b._params.bandIds&&(g.bandIds=b._params.bandIds);b._params.renderingRule?g.renderingRule=b._params.renderingRule:b.rasterFunctionInfos&&0<b.rasterFunctionInfos.length&&e.forEach(b.rasterFunctionInfos,function(b){b&&(b.name&&"none"===b.name.toLowerCase())&&(g.renderingRule=
t.stringify({rasterFunction:b.name}))});return F({url:a,content:g,callbackParamName:"callback",load:function(a,c){d(b,a,c)},error:Q.defaults.io.errorHandler})},_legendRequestTools:function(b){var a=b.url.toLowerCase().indexOf("/rest/"),a=b.url.substring(0,a)+b.url.substring(a+5,b.url.length),a=this._legendUrl+"?soapUrl\x3d"+window.escape(a);if(!c("ie")||8<c("ie"))a+="\x26returnbytes\x3dtrue";var d=k.hitch(this,"_processLegendResponse");return F({url:a,content:{f:"json"},callbackParamName:"callback",
load:function(a,c){d(b,a,c)},error:Q.defaults.io.errorHandler})},_processLegendResponse:function(b,c){c&&c.layers?(b.legendResponse=c,r.byId(this.id+"_"+b.id)&&a.empty(r.byId(this.id+"_"+b.id)),a.create("span",{innerHTML:this._getServiceTitle(b),"class":"esriLegendServiceLabel"},a.create("td",{align:this._align},a.create("tr",{},a.create("tbody",{},a.create("table",{width:"95%"},r.byId(this.id+"_"+b.id)))))),this._createLegendForLayer(b)):console.log("Legend could not get generated for "+b.url+": "+
f.toJson(c))},_buildLegendItems:function(b,c,d){var B=!1,g=r.byId(this.id+"_"+b.id),u=c.parentLayerId;if(c.subLayerIds)b=a.create("div",{id:this.id+"_"+b.id+"_"+c.id+"_group",style:{display:"none"},"class":-1==u?0<d?"esriLegendGroupLayer":"":this._legendAlign},-1==u?g:r.byId(this.id+"_"+b.id+"_"+u+"_group")),a.create("td",{innerHTML:w.encode(c.name),align:this._align},a.create("tr",{},a.create("tbody",{},a.create("table",{width:"95%","class":"esriLegendLayerLabel"},b))));else{if(this._respectVisibility&&
b.visibleLayers)if(d=b.dynamicLayerInfos||b.layerInfos)if(b._params&&b._params.layers){if(-1===e.indexOf(b.visibleLayers,c.id))return B}else{if(d=this._getReallyVisibleLayers(d,b.visibleLayers),-1===e.indexOf(d,c.id))return B}else if(-1===e.indexOf(b.visibleLayers,c.id))return B;g=a.create("div",{id:this.id+"_"+b.id+"_"+c.id,style:{display:"none"},"class":-1<u?this._legendAlign:""},-1==u?g:r.byId(this.id+"_"+b.id+"_"+u+"_group"));a.create("td",{innerHTML:w.encode(c.name)||"",align:this._align},a.create("tr",
{},a.create("tbody",{},a.create("table",{width:"95%","class":"esriLegendLayerLabel"},g))));b.legendResponse?B=B||this._buildLegendItems_Tools(b,c,g):b.renderer&&(B=B||this._buildLegendItems_Renderer(b,c,g))}return B},_getReallyVisibleLayers:function(b,a){if(!b||!a||!a.length)return[];var c=[],d=[],g;for(g=0;g<b.length;g++)if(b[g].subLayerIds){if(-1===e.indexOf(a,b[g].id)||-1<e.indexOf(d,b[g].id))d=d.concat(b[g].subLayerIds)}else-1<e.indexOf(a,b[g].id)&&-1===e.indexOf(d,b[g].id)&&c.push(b[g].id);return c},
_buildLegendItems_Tools:function(b,c,d){var B=c.parentLayerId,g=this.map.getScale(),u=!1,k=function(b,a){var c,d;for(c=0;c<b.length;c++)if(a.dynamicLayerInfos)for(d=0;d<a.dynamicLayerInfos[d].length;d++){if(a.dynamicLayerInfos[d].mapLayerId==b[c].layerId)return b[c]}else if(a.id==b[c].layerId)return b[c];return{}};if(!this._respectCurrentMapScale||this._respectCurrentMapScale&&this._isLayerInScale(b,c,g)){var f=!0;if(this._respectCurrentMapScale&&("esri.layers.ArcGISDynamicMapServiceLayer"===b.declaredClass||
"esri.layers.ArcGISMapServiceLayer"===b.declaredClass)){var h=this._getEffectiveScale(b,c);if(h.minScale&&h.minScale<g||h.maxScale&&h.maxScale>g)f=!1}if(f){var g=k(b.legendResponse.layers,c),x=g.legendType,p=g.layerType,l=g.legend;if(l){"esri.layers.ArcGISImageServiceLayer"!==b.declaredClass&&this._sanitizeLegendResponse(b,g,c);d=a.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d);var m=a.create("tbody",{},d);(b._hoverLabel||b._hoverLabels)&&this._createHoverAction(d,
b,c);e.forEach(l,function(a){if(!(10.1<=b.version&&!a.values&&1<l.length&&(b._hideDefaultSymbol||"\x3call other values\x3e"===a.label||!a.label&&!("esri.layers.ArcGISImageServiceLayer"===b.declaredClass&&10.3<=b.version||"Raster Layer"===p))))if(a.url&&0===a.url.indexOf("http")||a.imageData&&0<a.imageData.length)u=!0,this._buildRow_Tools(a,m,b,c.id,x)},this)}}}u&&(s.set(r.byId(this.id+"_"+b.id+"_"+c.id),"display","block"),-1<B&&(s.set(r.byId(this.id+"_"+b.id+"_"+B+"_group"),"display","block"),this._findParentGroup(b.id,
b,B)));return u},_sanitizeLegendResponse:function(b,a,c){var d=a.legend;if(10.1<=b.version&&1<d.length&&!a._sanitized){b=k.getObject("layerDefinition.drawingInfo.renderer",!1,c);var g,u;b||(b=k.getObject("drawingInfo.renderer",!1,c));e.some(d,function(b){if(b.values)return!0})&&e.some(d,function(b,a){b.values||(u=a,g=b);return!!g});b?"uniqueValue"===b.type?g&&(d.splice(u,1),d.push(g)):"classBreaks"===b.type&&(g&&d.splice(u,1),d.reverse(),g&&d.push(g)):g&&(d.splice(u,1),d.push(g));a._sanitized=!0}},
_buildRow_Tools:function(b,d,I,e,g){var u=a.create("tr",{},d),k;this.alignRight?(d=a.create("td",{align:this._isRightToLeft?"left":"right"},u),k=a.create("td",{align:this._isRightToLeft?"left":"right",width:35},u)):(k=a.create("td",{width:35,align:"center"},u),d=a.create("td",{},u));u=b.url;(!c("ie")||9<=c("ie")||9>c("ie")&&"esri.layers.ArcGISImageServiceLayer"===I.declaredClass)&&b.imageData&&0<b.imageData.length?u="data:image/png;base64,"+b.imageData:0!==b.url.indexOf("http")&&(u=I.url+"/"+e+"/images/"+
b.url,(e=I._getToken())&&(u+="?token\x3d"+e));e=a.create("img",{src:u,border:0,style:"opacity:"+I.opacity},k);b=a.create("td",{innerHTML:w.encode(b.label),align:this._align},a.create("tr",{},a.create("tbody",{},a.create("table",{width:"95%",dir:"ltr"},d))));g&&("Stretched"===g&&10.3<=I.version&&"esri.layers.ArcGISImageServiceLayer"===I.declaredClass)&&(b.style.verticalAlign="top",b.style.lineHeight="1",e.style.marginBottom="-1px",e.style.display="block",d.style.verticalAlign="top");9>c("ie")&&(e.style.filter=
"alpha(opacity\x3d"+100*I.opacity+")")},_getVariable:function(b,a,c){var d;b&&(d=(b=b.getVisualVariablesForType(a,c))&&b[0]);return d},_getVariables:function(b,a,c){b=[this._getVariable(b,"colorInfo",!1),this._getVariable(b,"opacityInfo",!1),this._getVariable(b,"sizeInfo",!1)];return a?e.filter(b,function(b){return!(!b||!(b.field===a&&b.normalizationField==c))}):b},_getFieldAlias:function(b,a){var c=a.infoTemplate,c=c&&c.getFieldInfo&&c.getFieldInfo(b),d=k.isFunction(b)?null:a.getField(b),g=c||d,
e="";g&&(e=c&&c.label||d&&d.alias||g.name||g.fieldName);return e},_getRampTitle:function(b,a){var c,d=b.field,g=b.normalizationField,e=!1,f=!1,h=!1,y,d=k.isFunction(d)?null:d,g=k.isFunction(g)?null:g;if(b.legendOptions&&b.legendOptions.title)c=b.legendOptions.title;else{if(a.renderer.authoringInfo&&a.renderer.authoringInfo.visualVariables){var x=a.renderer.authoringInfo.visualVariables;for(y=0;y<x.length;y++){var p=x[y];if("colorInfo"===p.type&&"ratio"===p.style){e=!0;break}else if("colorInfo"===
p.type&&"percent"===p.style){f=!0;break}else if("colorInfo"===p.type&&"percentTotal"===p.style){h=!0;break}}}(e=h&&"showRatioPercentTotal"||f&&"showRatioPercent"||e&&"showRatio"||g&&"showNormField"||d&&"showField"||null)&&(c=H.substitute({field:d&&this._getFieldAlias(d,a),normField:g&&this._getFieldAlias(g,a)},this._i18n[e]))}return c},_getRendererTitle:function(b,a){var c;if(b){var d,g,e;b instanceof O&&(d=b.attributeField,g=b.normalizationField,e="percent-of-total"===b.normalizationType);d=k.isFunction(d)?
null:d;g=k.isFunction(g)?null:g;b.legendOptions&&b.legendOptions.title?c=b.legendOptions.title:(e=g&&"showNormField"||(e?"showNormPct":null)||d&&"showField"||null)&&(c=H.substitute({field:d&&this._getFieldAlias(d,a),normField:g&&this._getFieldAlias(g,a)},this._i18n[e]))}return c},_buildLegendItems_Renderer:function(b,c,d){var B=c.parentLayerId,g=this.map,u=g.getScale(),f,h=!1;if(!this._respectCurrentMapScale||this._isLayerInScale(b,c,u)){var y,x,p="esri.layers.ArcGISImageServiceVectorLayer"===b.declaredClass?
b.renderer.renderer:b.renderer,l,m,q,n,t;if(p instanceof W&&(p=(p="zoom"===p.rangeType?p.getRendererInfoByZoom(g.getZoom()):p.getRendererInfoByScale(u))&&p.renderer,!p))return!1;var D=this._getVariables(p),v=e.filter(D,function(b){return!!b}).length,u=D[0],g=D[1],D=D[2],z,C;u&&(l=this._getMedianColor(p,u),u.field&&(q=k.isFunction(u.field)?null:b.getField(u.field)));g&&g.field&&(t=k.isFunction(g.field)?null:b.getField(g.field));D&&D.field&&(n=k.isFunction(D.field)?null:b.getField(D.field));if(p instanceof
Z)f=h=!0,this._showHeatRamp(b,c,p,d);else if(p instanceof X)f=h=!0,this._showDotDensityLegend(b,c,p,d);else if(p instanceof Y)f=h=!0,x=a.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d),y=a.create("tbody",{},x),(b._hoverLabel||b._hoverLabels)&&this._createHoverAction(x,b,c),p.latestObservationRenderer&&p.latestObservationRenderer instanceof N&&this._buildRow_Renderer(b,p.latestObservationRenderer.symbol,l,w.encode(p.latestObservationRenderer.label)||this.NLS_currentObservations,
null,y),p.observationRenderer&&p.observationRenderer instanceof N&&this._buildRow_Renderer(b,p.observationRenderer.symbol,l,w.encode(p.observationRenderer.label)||this.NLS_previousObservations,null,y);else if(p instanceof S){if(p.infos&&0<p.infos.length){f=h=!0;x=a.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d);y=a.create("tbody",{},x);(b._hoverLabel||b._hoverLabels)&&this._createHoverAction(x,b,c);p.attributeField&&D&&this._addSubHeader(y,this._getFieldAlias(p.attributeField,
b));var A=[];e.forEach(p.infos,function(a){var c=null;b._editable&&b.types&&(c=this._getTemplateFromTypes(b.types,a.value));var d=a.label;null==d&&(d=a.value);-1===e.indexOf(A,d)&&(A.push(d),this._buildRow_Renderer(b,a.symbol,l,w.encode(d),c,y))},this)}C=this._displayDefaultSymbol(b,p,d)}else if(p instanceof O){if(p.infos&&0<p.infos.length||"esri.layers.ArcGISImageServiceVectorLayer"===b.declaredClass){f=h=!0;z=this._isUnclassedRenderer(p);!u&&1===p.infos.length&&(m=(m=p.infos[0])&&m.symbol);z||(x=
a.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d),y=a.create("tbody",{},x),v=this._getRendererTitle(p,b),this._buildRow_Renderer(b,null,l,w.encode(v),null,y));x=a.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d);y=a.create("tbody",{},x);(b._hoverLabel||b._hoverLabels)&&this._createHoverAction(x,b,c);if(!z||!D)v=p.infos.slice(0).reverse(),e.forEach(v,function(a){var c=a.label;null==c&&!z&&(c=a.minValue+" - "+a.maxValue);this._buildRow_Renderer(b,
a.symbol,l,w.encode(c),null,y)},this);if("esri.layers.ArcGISImageServiceVectorLayer"===b.declaredClass&&(b.renderer.style===U.STYLE_SCALAR||b.renderer.style===U.STYLE_SINGLE_ARROW))this._buildRow_Renderer(b,p.defaultSymbol,null,"",null,y),b._hideDefaultSymbol=!0}z||(C=this._displayDefaultSymbol(b,p,d))}else p instanceof N&&(f=h=!0,x=a.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d),y=a.create("tbody",{},x),(b._hoverLabel||b._hoverLabels)&&this._createHoverAction(x,
b,c),m=null,b._editable&&(b.templates&&0<b.templates.length)&&(m=b.templates[0]),x=1<v?null:q||t||n,this._buildRow_Renderer(b,p.symbol,l,w.encode(x?this._getRampTitle(1<v?null:u||g||D,b):p.label),m,y),m=u?null:p.symbol,x&&(q=t=n=null));if(f){if(u&&(u.field||u.valueExpression))this._showGradientRamp(b,c,p,null,d,u,q,null,D?!0:!1);if(D&&(D.field||D.valueExpression))f=u||p instanceof S?!1:!0,this._showSizeLegend(b,c,p,D,l,d,n,null,f);if(g&&(g.field||g.valueExpression))n=m&&!m.url&&m.color?m.color:this.transparencyRampColor,
this._showGradientRamp(b,c,p,n,d,g,t,null,!1)}C||(C=this._displayDefaultSymbol(b,p,d));h=h||C}h&&(s.set(r.byId(this.id+"_"+b.id+"_"+c.id),"display","block"),-1<B&&(s.set(r.byId(this.id+"_"+b.id+"_"+B+"_group"),"display","block"),this._findParentGroup(b.id,B)));return h},_isUnclassedRenderer:function(b,a){var c;if(b instanceof O&&b.infos&&1===b.infos.length){c=b.attributeField;var d=b.normalizationField;c=a?c===a:!!this._getVariables(b,c,d).length}return c},_displayDefaultSymbol:function(b,c,d){var e;
!b._hideDefaultSymbol&&c.defaultSymbol&&(e=!0,d=a.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d),d=a.create("tbody",{},d),this._buildRow_Renderer(b,c.defaultSymbol,null,w.encode(c.defaultLabel)||"others",null,d));return e},_showGradientRamp:function(b,c,d,e,g,f,h,l,y){y=a.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"+(!y?" esriLegendSubFragment":"")},g);g=a.create("tbody",{},y);(b._hoverLabel||b._hoverLabels||l)&&this._createHoverAction(y,
b,c,l);(h||f.valueExpression)&&this._addSubHeader(g,this._getRampTitle(f,b));c=f.field;var m;c&&(m=k.isFunction(c)?null:b.getField(c));(f=this._getRampStops(d,f,e,m&&"esriFieldTypeDate"===m.type))&&f.length&&this._drawGradientRamp(g,f,!0,b,this._getRampBorderColor(d),!!e)},_getMedianColor:function(b,a){var c,d;a.colors?(c=a.minDataValue,d=a.maxDataValue):a.stops&&(c=a.stops[0].value,d=a.stops[a.stops.length-1].value);return b.getColor(c+(d-c)/2,{colorInfo:a})},_getRampStops:function(b,a,c,d){var g,
f,k,h,l=!1;a.colors||a.opacityValues?(f=a.maxDataValue-a.minDataValue,g=e.map([0,0.25,0.5,0.75,1],function(b){k=a.minDataValue+b*f;return Number(k.toFixed(6))}),this._checkPrecision(0,4,g)):a.stops&&(g=e.map(a.stops,function(b){return b.value}),(l=e.some(a.stops,function(b){return!!b.label}))&&(h=e.map(a.stops,function(b){return b.label})));var x=g[0],p,q;f=g[g.length-1]-x;return e.map(g,function(e,k){c?(p=new m(c.toRgba()),q=b.getOpacity(e,{opacityInfo:a}),null!=q&&(p.a=q)):p=b.getColor(e,{colorInfo:a});
var P="";if(l)P=h[k];else{var P=d?R.formatDate(e,R.timelineDateFormatOptions):C.format(e),n="";0===k?n=this._specialChars.lt+" ":k===g.length-1&&(n=this._specialChars.gt+" ");P=n+P}return{value:e,color:p,offset:1-(e-x)/f,label:P}},this).reverse()},_checkPrecision:function(b,a,c){var d=b+(a-b)/2,g=c[b],e=c[d],f=c[a],k=Math.floor(g),h=Math.floor(e),l=Math.floor(f);k===g&&(l===f&&h!==e&&k!==h&&l!==h)&&(c[d]=h);b+1!==d&&this._checkPrecision(b,d,c);d+1!==a&&this._checkPrecision(d,a,c)},_getRampBorderColor:function(b){var a;
if(b instanceof N)a=b.symbol;else if(b instanceof S||b instanceof O)a=b.infos[0].symbol;return(b=a&&-1===a.type.indexOf("linesymbol")?a.getStroke():null)&&b.color},_drawGradientRamp:function(b,d,f,k,g,h){var l=a.create("tr",{},b),J,y,x,p,n,r=d.length-1,t;p=0;this.alignRight?(b=a.create("td",{align:this._isRightToLeft?"left":"right"},l),J=a.create("td",{align:this._isRightToLeft?"left":"right",width:this.gradientWidth},l)):(J=a.create("td",{width:this.gradientWidth,align:"center"},l),b=a.create("td",
{},l));l=g&&0<g.a&&!(240<=g.r&&240<=g.g&&240<=g.b);y=a.create("div",{"class":l?"":"esriLegendBorderLessColorRamp",style:"position: relative; width:"+this.gradientWidth+"px;"},J);J=a.create("div",{"class":"esriLegendColorRamp"+(h?" esriLegendTransparencyRamp":"")},y);h=s.get(J,"width");l&&(g=9>c("ie")?g.toHex():"rgba("+g.toRgba().join(",")+")",s.set(J,"border",this.colorRampBorder+" "+g));f?(g=this.gradientHeight*r,s.set(J,"height",g+"px")):g=s.get(J,"height");s.set(y,"height",g+"px");l=q.createSurface(J,
h,g);9>c("ie")&&(p=l.getEventSource(),s.set(p,"position","relative"),s.set(p.parentNode,"position","relative"),p=1);try{f&&e.forEach(d,function(b,a){b.offset=a/r}),n=l.createRect({x:-p,y:-p,width:h+p,height:g+p}),n.setFill({type:"linear",x1:0,y1:0,x2:0,y2:g,colors:d}).setStroke(null),l.createRect({width:h,height:g}).setFill(new m([255,255,255,1-k.opacity])).setStroke(null),this._surfaceItems.push(l)}catch(v){l.clear(),l.destroy()}e.forEach(d,function(b,c){if(b.label){t="top:"+100*b.offset+"%;";var g=
"";0===c&&(g+=" esriLegendColorRampTickFirst");c===d.length-1&&(g+=" esriLegendColorRampTickLast");a.create("div",{"class":"esriLegendColorRampTick"+g,innerHTML:"\x26nbsp;",style:t},y)}});x=a.create("div",{"class":"esriLegendColorRampLabels",style:{height:g+this.gradientHeight+"px"}},b);f?e.forEach(d,function(b){a.create("div",{"class":"esriLegendColorRampLabel",innerHTML:w.encode(b.label)||"\x26nbsp;"},x)}):(a.create("div",{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.high},x),a.create("div",
{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.low,style:"top: "+(g+this.gradientHeight-2*this.gradientHeight)+"px;"},x))},_showHeatRamp:function(b,c,d,e,g){var f,k=d.field;f=a.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},e);e=a.create("tbody",{},f);(b._hoverLabel||b._hoverLabels||g)&&this._createHoverAction(f,b,c,g);(k=k&&b.getField(k))&&this._addSubHeader(e,this._getFieldAlias(k.name,b));c=this._getHeatmapStops(d);c.length&&this._drawGradientRamp(e,
c,!1,b)},_getHeatmapStops:function(b){var a=b.colorStops;b=b.colors;var c,d,g,f;if(a&&a[0])if(c=a.length-1,b=a[0]&&null!=a[0].ratio){if((b=a[c])&&1!==b.ratio)a=a.slice(0),a.push({ratio:1,color:b.color}),c++}else d=a[0].value,g=a[c].value-d,a=e.map(a,function(b){return{color:b.color,ratio:(b.value-d)/g}});else b&&b[0]&&(c=b.length-1,f=1/(b.length-1),a=e.map(b,function(b,a){return{color:b,ratio:a*f}}));a=e.map(a,function(b,a){var d="";0===a?d="Low":a===c&&(d="High");return{color:b.color,label:d,offset:1-
b.ratio}});return a.reverse()},_showDotDensityLegend:function(b,c,d,f){var g=d.legendOptions,h,l,m,q,n,p,s,r=this.dotDensitySwatchSize,t=Math.round(r/2);g&&(l=g.backgroundColor,m=g.outline,q=g.valueUnit,n=g.dotCoverage);n=(n||this.dotCoverage)/100;s=Math.round(r*r/Math.pow(d.dotSize,2)*n);f=a.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},f);p=a.create("tbody",{},f);(b._hoverLabel||b._hoverLabels)&&this._createHoverAction(f,b,c);this._addSubHeader(p,H.substitute({value:d.dotValue,
unit:q||""},this.NLS_dotValue));e.forEach(d.fields,function(a){a=k.mixin({},a);a.numPoints=s;h=new $(d._generateImageSrc(r,r,[a],{x:0,y:0},{x:r,y:r},l),m||d.outline,r,r);a=b.getField(a.name)||a;this._buildRow_Renderer(b,h,null,w.encode(this._getFieldAlias(a.name,b)),null,p,{type:"path",path:"M "+-t+","+-t+" L "+t+","+-t+" L "+t+","+t+" L "+-t+","+t+" L "+-t+","+-t+" E"})},this)},_showSizeLegend:function(b,c,d,e,g,f,h,l,m){var n=e.legendOptions,n=n&&n.customValues;g=this._getSizeSymbol(d,g);if(!(e.valueUnit&&
"unknown"!==e.valueUnit||!g||!n&&(null==e.minSize||null==e.maxSize))){m=a.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"+(!m?" esriLegendSubFragment":"")},f);f=a.create("tbody",{},m);(b._hoverLabel||b._hoverLabels||l)&&this._createHoverAction(m,b,c,l);(h||e.valueExpression)&&this._addSubHeader(f,this._getRampTitle(e,b));c=e.field;var p;c&&(p=k.isFunction(c)?null:b.getField(c));p=p&&"esriFieldTypeDate"===p.type;n=n||this._getDataValues(d,g,e,p);for(c=m=n.length-1;0<=
c;c--)h=n[c],g=T.fromJson(g.toJson()),this._applySize(g,d,e,h),h=p?R.formatDate(h,R.timelineDateFormatOptions):C.format(h),l="",c===m?l=this._specialChars.gt+" ":0===c&&(l=this._specialChars.lt+" "),l="\x3cspan class\x3d'esriLegendSizeRampLabel'\x3e"+w.encode(l+h)+"\x3c/span\x3e",this._buildRow_Renderer(b,g,null,l,null,f)}},_getSizeSymbol:function(b,a){var c,d;if(b instanceof N)c=b.symbol;else if(b instanceof U)c=b.defaultSymbol;else if(b instanceof S||b instanceof O)c=b.infos[0].symbol,d=1<b.infos.length;
if(c=c&&-1!==c.type.indexOf("fillsymbol")?null:c)if(c=T.fromJson(c.toJson()),a||d)-1!==c.type.indexOf("linesymbol")?c.setColor(new m(this.sizeRampDarkColor)):(c.setColor(new m(this.sizeRampLightColor)),c.setOutline&&(d=new aa,d.setColor(new m(this.sizeRampDarkColor)),d.setWidth(1.5),c.setOutline(d)));return c},_getDataValues:function(b,a,c,d,g,f){g=null==g?5:g;f=null==f?20:f;var k=b.getSizeRangeAtScale(c,this.map.getScale());g=this._interpolateSizeRange(k,g);var h=e.map(g,function(b){return this._getDataValueFromSize(b,
c,k)},this);if(!d){var l,h=C.round(h);for(d=1;d<h.length-1;d++)if(l=this._roundDataValue(b,a,c,h[d],h[d-1],f))h[d]=l[0],g[d]=l[1]}return h},_interpolateSizeRange:function(b,a){var c=b.minSize,d=(b.maxSize-c)/(a-1),e,f=[];for(e=0;e<a;e++)f.push(c+d*e);return f},_getDataValueFromSize:function(b,a,c){var d=c.minSize;c=c.maxSize;var e=a.minDataValue;a=a.maxDataValue;return b=b<=d?e:b>=c?a:(b-d)/(c-d)*(a-e)+e},_roundDataValue:function(b,a,c,d,e,f){var k=this._getSize(a,b,c,d);e=this._getSize(a,b,c,e);
var h,l=C.getDigits(d),m=l.integer,l=l.fractional,p,n,q,s,r,t,v,w,z,A,E;0<d&&1>d&&(h=Math.pow(10,l),d*=h,m=C.getDigits(d).integer);for(m-=1;0<=m&&!(p=Math.pow(10,m),l=Math.floor(d/p)*p,p*=Math.ceil(d/p),null!=h&&(l/=h,p/=h),n=(l+p)/2,n=C.round([l,n,p],{indexes:[1]})[1],q=this._getSize(a,b,c,l),s=this._getSize(a,b,c,p),r=this._getSize(a,b,c,n),t=C.getPctChange(k,q,e,null),v=C.getPctChange(k,s,e,null),w=C.getPctChange(k,r,e,null),z=t.prev<=f,A=v.prev<=f,z&&A&&(t.prev<=v.prev?(z=!0,A=!1):(A=!0,z=!1)),
z?E=[l,q]:A?E=[p,s]:w.prev<=f&&(E=[n,r]),E);m--);return E},_applySize:function(b,a,c,d){var e=b.type;a=this._getSize(b,a,c,d);switch(e){case "simplemarkersymbol":b.setSize(a);break;case "picturemarkersymbol":e=b.width;c=b.height;b.setHeight(a);b.setWidth(a*(e/c));break;case "simplelinesymbol":case "cartographiclinesymbol":b.setWidth(a);break;case "textsymbol":b.font&&b.font.setSize(a)}},_getSize:function(b,a,c,d){return a.getSize(d,{sizeInfo:c,scale:this.map.getScale(),shape:-1!==b.type.indexOf("markersymbol")?
b.style:null})},_buildRow_Renderer:function(b,c,d,e,g,f,h){var k=a.create("tr",{},f),l;this.alignRight?(f=a.create("td",{align:this._isRightToLeft?"left":"right"},k),c&&(l=a.create("td",{align:this._isRightToLeft?"left":"right",width:35},k))):(c&&(l=a.create("td",{width:35,align:"center"},k)),f=a.create("td",{},k));var m=k=30,p;if(c){if("simplemarkersymbol"==c.type)k=Math.min(Math.max(k,c.size+12),125),m=Math.min(Math.max(m,c.size+12),125);else if("picturemarkersymbol"==c.type)k=Math.min(Math.max(k,
c.width),125),m=Math.min(c.height||m,125);else if("textsymbol"==c.type){var n,q;c.text||(n=c.text,q=!0,c.setText(this.defaultText));k=Math.min(Math.max(k,c.getWidth()+12),125);m=Math.min(Math.max(m,c.getHeight()+12),125);q&&c.setText(n)}p=a.create("div",{style:"width:"+k+"px;height:"+m+"px;"},l)}H.isDefined(e)&&"number"===typeof e&&(e=""+e);a.create("td",{innerHTML:e||"",align:this._align},a.create("tr",{},a.create("tbody",{},a.create("table",{width:"95%"},f))));c&&(b=this._drawSymbol(p,c,d,k,m,g,
b,h),this._surfaceItems.push(b))},_addSubHeader:function(b,c){var d=a.create("tr",{},b),d=a.create("td",{align:this._align,colspan:2},d);a.create("td",{innerHTML:w.encode(c)||"",align:this._align},a.create("tr",{},a.create("tbody",{},a.create("table",{width:"95%"},d))))},_drawSymbol:function(b,a,d,e,g,f,h,l){a=T.fromJson(a.toJson());var n=h.opacity;d&&a.setColor(new m(d.toRgba()));if("simplelinesymbol"===a.type||"cartographiclinesymbol"===a.type||"textsymbol"===a.type){if(!a.color)return;d=a.color.toRgba();
d[3]*=n;a.color.setColor(d)}else"simplemarkersymbol"===a.type||"simplefillsymbol"===a.type?(a.color&&(d=a.color.toRgba(),d[3]*=n,a.color.setColor(d)),a.outline&&a.outline.color&&(d=a.outline.color.toRgba(),d[3]*=n,a.outline.color.setColor(d))):"picturemarkersymbol"===a.type&&(b.style.opacity=n,b.style.filter="alpha(opacity\x3d("+100*n+"))");b=q.createSurface(b,e,g);9>c("ie")&&(d=b.getEventSource(),s.set(d,"position","relative"),s.set(d.parentNode,"position","relative"));f=this._getDrawingToolShape(a,
f)||T.getShapeDescriptors(a);var r,n=(d=f.defaultShape)&&"text"===d.type;try{n&&!d.text&&(d.text=this.defaultText),r=b.createShape(l||d).setFill(f.fill).setStroke(f.stroke),n&&r.setFont(f.font)}catch(p){b.clear();b.destroy();return}var t=r.getBoundingBox();l=t.width;f=t.height;var n=-(t.x+l/2),w=-(t.y+f/2);d=b.getDimensions();n={dx:n+d.width/2,dy:w+d.height/2};if("simplemarkersymbol"===a.type&&"path"===a.style)e=h._getScaleMatrix(t,a.size),r.applyTransform(v.scaleAt(e.xx,e.yy,{x:d.width/2,y:d.height/
2}));else if(l>e||f>g)h=l/e>f/g,e=((h?e:g)-5)/(h?l:f),k.mixin(n,{xx:e,yy:e});r.applyTransform(n);return b},_getDrawingToolShape:function(b,a){var c;switch(a?a.drawingTool||null:null){case "esriFeatureEditToolArrow":c={type:"path",path:"M 10,1 L 3,8 L 3,5 L -15,5 L -15,-2 L 3,-2 L 3,-5 L 10,1 Z"};break;case "esriFeatureEditToolTriangle":c={type:"path",path:"M -10,14 L 2,-10 L 14,14 L -10,14 Z"};break;case "esriFeatureEditToolRectangle":c={type:"path",path:"M -10,-10 L 10,-10 L 10,10 L -10,10 L -10,-10 Z"};
break;case "esriFeatureEditToolCircle":c={type:"circle",cx:0,cy:0,r:10};break;case "esriFeatureEditToolEllipse":c={type:"ellipse",cx:0,cy:0,rx:10,ry:5};break;default:return null}return{defaultShape:c,fill:b.getFill(),stroke:b.getStroke()}},_repaintItems:function(){e.forEach(this._surfaceItems,function(b){this._repaint(b)},this)},_repaint:function(b){if(b){b.getStroke&&b.setStroke&&b.setStroke(b.getStroke());try{b.getFill&&b.setFill&&b.setFill(b.getFill())}catch(a){}b.children&&k.isArray(b.children)&&
e.forEach(b.children,this._repaint,this)}},_createHoverAction:function(b,c,d,e){if(e=c._hoverLabel||c._hoverLabels&&c._hoverLabels[d.id]||e)e=w.encode(e),c.mouseMoveHandler=c.mouseMoveHandler||{},c.mouseMoveHandler[d.id]=l.connect(b,"onmousemove",k.hitch(this,function(b,c){this.mouseX=c.clientX;this.mouseY=c.clientY;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,s.set(r.byId(this.id+"_hoverLabel"),"display","none"));setTimeout(k.hitch(this,function(b,c,d){if(b==this.mouseX&&c==this.mouseY&&!this.hoverLabelShowing)if(this.hoverLabelShowing=
!0,r.byId(this.id+"_hoverLabel")){var e=r.byId(this.id+"_hoverLabel");e.innerHTML="\x3cspan\x3e"+d+"\x3c/span\x3e";s.set(e,"top",c+"px");s.set(e,"left",b+15+"px");s.set(e,"display","")}else a.create("div",{innerHTML:"\x3cspan\x3e"+d+"\x3c/span\x3e",id:this.id+"_hoverLabel","class":"esriLegendHoverLabel",style:{top:c+"px",left:b+15+"px"}},document.body)},c.clientX,c.clientY,b),500)},e)),c.mouseOutHandler=c.mouseOutHandler||{},c.mouseOutHandler[d.id]=l.connect(b,"onmouseout",k.hitch(this,function(b){this.mouseY=
this.mouseX=-1;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,s.set(r.byId(this.id+"_hoverLabel"),"display","none"))}))},_removeHoverHandlers:function(){var b;e.forEach(this.layers,function(a){if(a.mouseMoveHandler)for(b in a.mouseMoveHandler)l.disconnect(a.mouseMoveHandler[b]);if(a.mouseOutHandler)for(b in a.mouseOutHandler)l.disconnect(a.mouseOutHandler[b])})},_createDynamicLayers:function(b){var a=[],c;e.forEach(b.dynamicLayerInfos||b.layerInfos,function(d){c={id:d.id};c.source=d.source&&d.source.toJson();
var e;b.layerDefinitions&&b.layerDefinitions[d.id]&&(e=b.layerDefinitions[d.id]);e&&(c.definitionExpression=e);var f;b.layerDrawingOptions&&b.layerDrawingOptions[d.id]&&(f=b.layerDrawingOptions[d.id]);f&&(c.drawingInfo=f.toJson());c.minScale=d.minScale||0;c.maxScale=d.maxScale||0;a.push(c)});return a},_getTemplateFromTypes:function(b,a){var c;for(c=0;c<b.length;c++)if(b[c].id==a&&b[c].templates&&0<b[c].templates.length)return b[c].templates[0];return null},_findParentGroup:function(b,a,c){var d,e=
a.dynamicLayerInfos||a.layerInfos;for(d=0;d<e.length;d++)if(c==e[d].id){-1<e[d].parentLayerId&&(s.set(r.byId(this.id+"_"+b+"_"+e[d].parentLayerId+"_group"),"display","block"),this._findParentGroup(b,a,e[d].parentLayerId));break}},_addSubLayersToHide:function(b){function a(c,d){var g=b.layer.dynamicLayerInfos||b.layer.layerInfos,f,k;for(f=0;f<g.length;f++)if(g[f].id===c&&g[f].subLayerIds)for(k=0;k<g[f].subLayerIds.length;k++){var h=g[f].subLayerIds[k];-1===e.indexOf(d,h)&&(d.push(h),a(h,d))}}b.layer.layerInfos&&
e.forEach(this.hideLayersInLegend[b.layer.id],function(c){a(c,this.hideLayersInLegend[b.layer.id])},this)},_isLayerInScale:function(b,a,c){var d,e=!0;if(b.legendResponse&&b.legendResponse.layers)for(d=0;d<b.legendResponse.layers.length;d++){var f=b.legendResponse.layers[d];if(a.id==f.layerId){var k,h;!b.minScale&&0!==b.minScale||!b.maxScale&&0!==b.maxScale?(0==f.minScale&&b.tileInfo&&(k=b.tileInfo.lods[0].scale),0==f.maxScale&&b.tileInfo&&(h=b.tileInfo.lods[b.tileInfo.lods.length-1].scale)):(k=Math.min(b.minScale,
f.minScale)||b.minScale||f.minScale,h=Math.max(b.maxScale,f.maxScale));if(0<k&&k<c||h>c)e=!1;break}}else if(b.minScale||b.maxScale)if(b.minScale&&b.minScale<c||b.maxScale&&b.maxScale>c)e=!1;return e},_getServiceTitle:function(b){var a=b._titleForLegend;a||((a=b.url)?-1<b.url.indexOf("/MapServer")?(a=b.url.substring(0,b.url.indexOf("/MapServer")),a=a.substring(a.lastIndexOf("/")+1,a.length)):-1<b.url.indexOf("/ImageServer")?(a=b.url.substring(0,b.url.indexOf("/ImageServer")),a=a.substring(a.lastIndexOf("/")+
1,a.length)):-1<b.url.indexOf("/FeatureServer")&&(a=b.url.substring(0,b.url.indexOf("/FeatureServer")),a=a.substring(a.lastIndexOf("/")+1,a.length)):a="",b.name&&(a=0<a.length?a+(" - "+b.name):b.name));"esri.layers.ArcGISImageServiceVectorLayer"===b.declaredClass&&b.vectorFieldPixelFilter&&(b=b.vectorFieldPixelFilter.outputUnit?this["NLS_"+b.vectorFieldPixelFilter.outputUnit]:this["NLS_"+b.vectorFieldPixelFilter.inputUnit],H.isDefined(b)&&(a+=" ("+b+")"));return w.encode(a)},_getEffectiveScale:function(a,
c){var d=c.minScale,e=c.maxScale;if(H.isDefined(c.parentLayerId)){var f=a.layerInfos,k=c.parentLayerId,h;for(h=f.length-1;0<=h;h--)if(f[h].id==k)if(0==d&&0<f[h].minScale?d=f[h].minScale:0<d&&0==f[h].minScale||0<d&&0<f[h].minScale&&(d=Math.min(d,f[h].minScale)),e=Math.max(e||0,f[h].maxScale||0),-1<f[h].parentLayerId)k=f[h].parentLayerId;else break}return{minScale:d,maxScale:e}},_isSupportedLayerType:function(a){return a&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISImageServiceLayer"===
a.declaredClass&&10.2<=a.version||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass||"esri.layers.ArcGISTiledMapServiceLayer"===a.declaredClass||"esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===a.declaredClass||"esri.layers.KMLLayer"===a.declaredClass||"esri.layers.GeoRSSLayer"===a.declaredClass||"esri.layers.WMSLayer"===a.declaredClass||"esri.layers.WFSLayer"===a.declaredClass||"esri.layers.CSVLayer"===a.declaredClass)?!0:!1}});k.mixin(L,{ALIGN_LEFT:0,ALIGN_RIGHT:1});
c("extend-esri")&&k.setObject("dijit.Legend",L,M);return L});