//>>built
require({cache:{"dojox/gfx/shape":function(){define("./_base dojo/_base/lang dojo/_base/declare dojo/_base/kernel dojo/_base/sniff dojo/on dojo/_base/array dojo/dom-construct dojo/_base/Color ./matrix".split(" "),function(d,p,n,r,m,b,l,e,k,c){var h=d.shape={};h.Shape=n("dojox.gfx.shape.Shape",null,{constructor:function(){this.parentMatrix=this.parent=this.bbox=this.strokeStyle=this.fillStyle=this.matrix=this.shape=this.rawNode=null;if(m("gfxRegistry")){var a=h.register(this);this.getUID=function(){return a}}},
destroy:function(){m("gfxRegistry")&&h.dispose(this);this.rawNode&&"__gfxObject__"in this.rawNode&&(this.rawNode.__gfxObject__=null);this.rawNode=null},getNode:function(){return this.rawNode},getShape:function(){return this.shape},getTransform:function(){return this.matrix},getFill:function(){return this.fillStyle},getStroke:function(){return this.strokeStyle},getParent:function(){return this.parent},getBoundingBox:function(){return this.bbox},getTransformedBoundingBox:function(){var a=this.getBoundingBox();
if(!a)return null;var b=this._getRealMatrix();return[c.multiplyPoint(b,a.x,a.y),c.multiplyPoint(b,a.x+a.width,a.y),c.multiplyPoint(b,a.x+a.width,a.y+a.height),c.multiplyPoint(b,a.x,a.y+a.height)]},getEventSource:function(){return this.rawNode},setClip:function(a){this.clip=a},getClip:function(){return this.clip},setShape:function(a){this.shape=d.makeParameters(this.shape,a);this.bbox=null;return this},setFill:function(a){if(!a)return this.fillStyle=null,this;var c=null;if("object"==typeof a&&"type"in
a)switch(a.type){case "linear":c=d.makeParameters(d.defaultLinearGradient,a);break;case "radial":c=d.makeParameters(d.defaultRadialGradient,a);break;case "pattern":c=d.makeParameters(d.defaultPattern,a)}else c=d.normalizeColor(a);this.fillStyle=c;return this},setStroke:function(a){if(!a)return this.strokeStyle=null,this;if("string"==typeof a||p.isArray(a)||a instanceof k)a={color:a};a=this.strokeStyle=d.makeParameters(d.defaultStroke,a);a.color=d.normalizeColor(a.color);return this},setTransform:function(a){this.matrix=
c.clone(a?c.normalize(a):c.identity);return this._applyTransform()},_applyTransform:function(){return this},moveToFront:function(){var a=this.getParent();a&&(a._moveChildToFront(this),this._moveToFront());return this},moveToBack:function(){var a=this.getParent();a&&(a._moveChildToBack(this),this._moveToBack());return this},_moveToFront:function(){},_moveToBack:function(){},applyRightTransform:function(a){return a?this.setTransform([this.matrix,a]):this},applyLeftTransform:function(a){return a?this.setTransform([a,
this.matrix]):this},applyTransform:function(a){return a?this.setTransform([this.matrix,a]):this},removeShape:function(a){this.parent&&this.parent.remove(this,a);return this},_setParent:function(a,c){this.parent=a;return this._updateParentMatrix(c)},_updateParentMatrix:function(a){this.parentMatrix=a?c.clone(a):null;return this._applyTransform()},_getRealMatrix:function(){for(var a=this.matrix,b=this.parent;b;)b.matrix&&(a=c.multiply(b.matrix,a)),b=b.parent;return a}});h._eventsProcessing={on:function(a,
c){return b(this.getEventSource(),a,h.fixCallback(this,d.fixTarget,c))},connect:function(a,c,b){"on"==a.substring(0,2)&&(a=a.substring(2));return this.on(a,b?p.hitch(c,b):c)},disconnect:function(a){return a.remove()}};h.fixCallback=function(a,c,b,g){g||(g=b,b=null);if(p.isString(g)){b=b||r.global;if(!b[g])throw['dojox.gfx.shape.fixCallback: scope["',g,'"] is null (scope\x3d"',b,'")'].join("");return function(d){return c(d,a)?b[g].apply(b,arguments||[]):void 0}}return!b?function(d){return c(d,a)?g.apply(b,
arguments):void 0}:function(d){return c(d,a)?g.apply(b,arguments||[]):void 0}};p.extend(h.Shape,h._eventsProcessing);h.Container={_init:function(){this.children=[];this._batch=0},openBatch:function(){return this},closeBatch:function(){return this},add:function(a){var c=a.getParent();c&&c.remove(a,!0);this.children.push(a);return a._setParent(this,this._getRealMatrix())},remove:function(a,c){for(var b=0;b<this.children.length;++b)if(this.children[b]==a){c||(a.parent=null,a.parentMatrix=null);this.children.splice(b,
1);break}return this},clear:function(a){for(var c,b=0;b<this.children.length;++b)c=this.children[b],c.parent=null,c.parentMatrix=null,a&&c.destroy();this.children=[];return this},getBoundingBox:function(){if(this.children){var a=null;l.forEach(this.children,function(b){var d=b.getBoundingBox();d&&((b=b.getTransform())&&(d=c.multiplyRectangle(b,d)),a?(a.x=Math.min(a.x,d.x),a.y=Math.min(a.y,d.y),a.endX=Math.max(a.endX,d.x+d.width),a.endY=Math.max(a.endY,d.y+d.height)):a={x:d.x,y:d.y,endX:d.x+d.width,
endY:d.y+d.height})});a&&(a.width=a.endX-a.x,a.height=a.endY-a.y);return a}return null},_moveChildToFront:function(a){for(var c=0;c<this.children.length;++c)if(this.children[c]==a){this.children.splice(c,1);this.children.push(a);break}return this},_moveChildToBack:function(a){for(var c=0;c<this.children.length;++c)if(this.children[c]==a){this.children.splice(c,1);this.children.unshift(a);break}return this}};h.Surface=n("dojox.gfx.shape.Surface",null,{constructor:function(){this._parent=this.rawNode=
null;this._nodes=[];this._events=[]},destroy:function(){l.forEach(this._nodes,e.destroy);this._nodes=[];l.forEach(this._events,function(a){a&&a.remove()});this._events=[];this.rawNode=null;if(m("ie"))for(;this._parent.lastChild;)e.destroy(this._parent.lastChild);else this._parent.innerHTML="";this._parent=null},getEventSource:function(){return this.rawNode},_getRealMatrix:function(){return null},isLoaded:!0,onLoad:function(a){},whenLoaded:function(a,c){var d=p.hitch(a,c);if(this.isLoaded)d(this);
else b.once(this,"load",function(a){d(a)})}});p.extend(h.Surface,h._eventsProcessing);h.Rect=n("dojox.gfx.shape.Rect",h.Shape,{constructor:function(a){this.shape=d.getDefault("Rect");this.rawNode=a},getBoundingBox:function(){return this.shape}});h.Ellipse=n("dojox.gfx.shape.Ellipse",h.Shape,{constructor:function(a){this.shape=d.getDefault("Ellipse");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=this.shape;this.bbox={x:a.cx-a.rx,y:a.cy-a.ry,width:2*a.rx,height:2*a.ry}}return this.bbox}});
h.Circle=n("dojox.gfx.shape.Circle",h.Shape,{constructor:function(a){this.shape=d.getDefault("Circle");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=this.shape;this.bbox={x:a.cx-a.r,y:a.cy-a.r,width:2*a.r,height:2*a.r}}return this.bbox}});h.Line=n("dojox.gfx.shape.Line",h.Shape,{constructor:function(a){this.shape=d.getDefault("Line");this.rawNode=a},getBoundingBox:function(){if(!this.bbox){var a=this.shape;this.bbox={x:Math.min(a.x1,a.x2),y:Math.min(a.y1,a.y2),width:Math.abs(a.x2-
a.x1),height:Math.abs(a.y2-a.y1)}}return this.bbox}});h.Polyline=n("dojox.gfx.shape.Polyline",h.Shape,{constructor:function(a){this.shape=d.getDefault("Polyline");this.rawNode=a},setShape:function(a,c){a&&a instanceof Array?(this.inherited(arguments,[{points:a}]),c&&this.shape.points.length&&this.shape.points.push(this.shape.points[0])):this.inherited(arguments,[a]);return this},_normalizePoints:function(){var a=this.shape.points,c=a&&a.length;if(c&&"number"==typeof a[0]){for(var b=[],g=0;g<c;g+=
2)b.push({x:a[g],y:a[g+1]});this.shape.points=b}},getBoundingBox:function(){if(!this.bbox&&this.shape.points.length){for(var a=this.shape.points,c=a.length,b=a[0],g=b.x,d=b.y,e=b.x,l=b.y,h=1;h<c;++h)b=a[h],g>b.x&&(g=b.x),e<b.x&&(e=b.x),d>b.y&&(d=b.y),l<b.y&&(l=b.y);this.bbox={x:g,y:d,width:e-g,height:l-d}}return this.bbox}});h.Image=n("dojox.gfx.shape.Image",h.Shape,{constructor:function(a){this.shape=d.getDefault("Image");this.rawNode=a},getBoundingBox:function(){return this.shape},setStroke:function(){return this},
setFill:function(){return this}});h.Text=n(h.Shape,{constructor:function(a){this.fontStyle=null;this.shape=d.getDefault("Text");this.rawNode=a},getFont:function(){return this.fontStyle},setFont:function(a){this.fontStyle="string"==typeof a?d.splitFontString(a):d.makeParameters(d.defaultFont,a);this._setFont();return this},getBoundingBox:function(){var a=null;this.getShape().text&&(a=d._base._computeTextBoundingBox(this));return a}});h.Creator={createShape:function(a){switch(a.type){case d.defaultPath.type:return this.createPath(a);
case d.defaultRect.type:return this.createRect(a);case d.defaultCircle.type:return this.createCircle(a);case d.defaultEllipse.type:return this.createEllipse(a);case d.defaultLine.type:return this.createLine(a);case d.defaultPolyline.type:return this.createPolyline(a);case d.defaultImage.type:return this.createImage(a);case d.defaultText.type:return this.createText(a);case d.defaultTextPath.type:return this.createTextPath(a)}return null},createGroup:function(){return this.createObject(d.Group)},createRect:function(a){return this.createObject(d.Rect,
a)},createEllipse:function(a){return this.createObject(d.Ellipse,a)},createCircle:function(a){return this.createObject(d.Circle,a)},createLine:function(a){return this.createObject(d.Line,a)},createPolyline:function(a){return this.createObject(d.Polyline,a)},createImage:function(a){return this.createObject(d.Image,a)},createText:function(a){return this.createObject(d.Text,a)},createPath:function(a){return this.createObject(d.Path,a)},createTextPath:function(a){return this.createObject(d.TextPath,{}).setText(a)},
createObject:function(a,c){return null}};return h})},"dojox/gfx/path":function(){define(["./_base","dojo/_base/lang","dojo/_base/declare","./matrix","./shape"],function(d,p,n,r,m){m=n("dojox.gfx.path.Path",m.Shape,{constructor:function(b){this.shape=p.clone(d.defaultPath);this.segments=[];this.tbbox=null;this.absolute=!0;this.last={};this.rawNode=b;this.segmented=!1},setAbsoluteMode:function(b){this._confirmSegmented();this.absolute="string"==typeof b?"absolute"==b:b;return this},getAbsoluteMode:function(){this._confirmSegmented();
return this.absolute},getBoundingBox:function(){this._confirmSegmented();return this.bbox&&"l"in this.bbox?{x:this.bbox.l,y:this.bbox.t,width:this.bbox.r-this.bbox.l,height:this.bbox.b-this.bbox.t}:null},_getRealBBox:function(){this._confirmSegmented();if(this.tbbox)return this.tbbox;var b=this.bbox,d=this._getRealMatrix();this.bbox=null;for(var e=0,k=this.segments.length;e<k;++e)this._updateWithSegment(this.segments[e],d);d=this.bbox;this.bbox=b;return this.tbbox=d?[{x:d.l,y:d.t},{x:d.r,y:d.t},{x:d.r,
y:d.b},{x:d.l,y:d.b}]:null},getLastPosition:function(){this._confirmSegmented();return"x"in this.last?this.last:null},_applyTransform:function(){this.tbbox=null;return this.inherited(arguments)},_updateBBox:function(b,d,e){e&&(d=r.multiplyPoint(e,b,d),b=d.x,d=d.y);this.bbox&&"l"in this.bbox?(this.bbox.l>b&&(this.bbox.l=b),this.bbox.r<b&&(this.bbox.r=b),this.bbox.t>d&&(this.bbox.t=d),this.bbox.b<d&&(this.bbox.b=d)):this.bbox={l:b,b:d,r:b,t:d}},_updateWithSegment:function(b,l){var e=b.args,k=e.length,
c;switch(b.action){case "M":case "L":case "C":case "S":case "Q":case "T":for(c=0;c<k;c+=2)this._updateBBox(e[c],e[c+1],l);this.last.x=e[k-2];this.last.y=e[k-1];this.absolute=!0;break;case "H":for(c=0;c<k;++c)this._updateBBox(e[c],this.last.y,l);this.last.x=e[k-1];this.absolute=!0;break;case "V":for(c=0;c<k;++c)this._updateBBox(this.last.x,e[c],l);this.last.y=e[k-1];this.absolute=!0;break;case "m":c=0;"x"in this.last||(this._updateBBox(this.last.x=e[0],this.last.y=e[1],l),c=2);for(;c<k;c+=2)this._updateBBox(this.last.x+=
e[c],this.last.y+=e[c+1],l);this.absolute=!1;break;case "l":case "t":for(c=0;c<k;c+=2)this._updateBBox(this.last.x+=e[c],this.last.y+=e[c+1],l);this.absolute=!1;break;case "h":for(c=0;c<k;++c)this._updateBBox(this.last.x+=e[c],this.last.y,l);this.absolute=!1;break;case "v":for(c=0;c<k;++c)this._updateBBox(this.last.x,this.last.y+=e[c],l);this.absolute=!1;break;case "c":for(c=0;c<k;c+=6)this._updateBBox(this.last.x+e[c],this.last.y+e[c+1],l),this._updateBBox(this.last.x+e[c+2],this.last.y+e[c+3],l),
this._updateBBox(this.last.x+=e[c+4],this.last.y+=e[c+5],l);this.absolute=!1;break;case "s":case "q":for(c=0;c<k;c+=4)this._updateBBox(this.last.x+e[c],this.last.y+e[c+1],l),this._updateBBox(this.last.x+=e[c+2],this.last.y+=e[c+3],l);this.absolute=!1;break;case "A":for(c=0;c<k;c+=7)this._updateBBox(e[c+5],e[c+6],l);this.last.x=e[k-2];this.last.y=e[k-1];this.absolute=!0;break;case "a":for(c=0;c<k;c+=7)this._updateBBox(this.last.x+=e[c+5],this.last.y+=e[c+6],l);this.absolute=!1}var h=[b.action];for(c=
0;c<k;++c)h.push(d.formatNumber(e[c],!0));if("string"==typeof this.shape.path)this.shape.path+=h.join("");else{c=0;for(k=h.length;c<k;++c)this.shape.path.push(h[c])}},_validSegments:{m:2,l:2,h:1,v:1,c:6,s:4,q:4,t:2,a:7,z:0},_pushSegment:function(b,d){this.tbbox=null;var e=this._validSegments[b.toLowerCase()];"number"==typeof e&&(e?d.length>=e&&(e={action:b,args:d.slice(0,d.length-d.length%e)},this.segments.push(e),this._updateWithSegment(e)):(e={action:b,args:[]},this.segments.push(e),this._updateWithSegment(e)))},
_collectArgs:function(b,d){for(var e=0;e<d.length;++e){var k=d[e];"boolean"==typeof k?b.push(k?1:0):"number"==typeof k?b.push(k):k instanceof Array?this._collectArgs(b,k):"x"in k&&"y"in k&&b.push(k.x,k.y)}},moveTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"M":"m",b);return this},lineTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"L":"l",b);return this},hLineTo:function(){this._confirmSegmented();
var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"H":"h",b);return this},vLineTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"V":"v",b);return this},curveTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"C":"c",b);return this},smoothCurveTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"S":
"s",b);return this},qCurveTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"Q":"q",b);return this},qSmoothCurveTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"T":"t",b);return this},arcTo:function(){this._confirmSegmented();var b=[];this._collectArgs(b,arguments);this._pushSegment(this.absolute?"A":"a",b);return this},closePath:function(){this._confirmSegmented();this._pushSegment("Z",
[]);return this},_confirmSegmented:function(){if(!this.segmented){var b=this.shape.path;this.shape.path=[];this._setPath(b);this.shape.path=this.shape.path.join("");this.segmented=!0}},_setPath:function(b){b=p.isArray(b)?b:b.match(d.pathSvgRegExp);this.segments=[];this.absolute=!0;this.bbox={};this.last={};if(b){for(var l="",e=[],k=b.length,c=0;c<k;++c){var h=b[c],a=parseFloat(h);isNaN(a)?(l&&this._pushSegment(l,e),e=[],l=h):e.push(a)}this._pushSegment(l,e)}},setShape:function(b){this.inherited(arguments,
["string"==typeof b?{path:b}:b]);this.segmented=!1;this.segments=[];d.lazyPathSegmentation||this._confirmSegmented();return this},_2PI:2*Math.PI});n=n("dojox.gfx.path.TextPath",m,{constructor:function(b){"text"in this||(this.text=p.clone(d.defaultTextPath));"fontStyle"in this||(this.fontStyle=p.clone(d.defaultFont))},getText:function(){return this.text},setText:function(b){this.text=d.makeParameters(this.text,"string"==typeof b?{text:b}:b);this._setText();return this},getFont:function(){return this.fontStyle},
setFont:function(b){this.fontStyle="string"==typeof b?d.splitFontString(b):d.makeParameters(d.defaultFont,b);this._setFont();return this}});return d.path={Path:m,TextPath:n}})},"*noref":1}});
define("dojox/gfx/svg","dojo/_base/lang dojo/_base/sniff dojo/_base/window dojo/dom dojo/_base/declare dojo/_base/array dojo/dom-geometry dojo/dom-attr dojo/_base/Color ./_base ./shape ./path".split(" "),function(d,p,n,r,m,b,l,e,k,c,h,a){function q(f,a){return n.doc.createElementNS?n.doc.createElementNS(f,a):n.doc.createElement(a)}function t(f){return g.useSvgWeb?n.doc.createTextNode(f,!0):n.doc.createTextNode(f)}var g=c.svg={};g.useSvgWeb="undefined"!=typeof window.svgweb;var v=navigator.userAgent,
w=p("ios"),u=p("android"),x=p("chrome")||u&&4<=u?"auto":"optimizeLegibility";g.xmlns={xlink:"http://www.w3.org/1999/xlink",svg:"http://www.w3.org/2000/svg"};g.getRef=function(f){return!f||"none"==f?null:f.match(/^url\(#.+\)$/)?r.byId(f.slice(5,-1)):f.match(/^#dojoUnique\d+$/)?r.byId(f.slice(1)):null};g.dasharray={solid:"none",shortdash:[4,1],shortdot:[1,1],shortdashdot:[4,1,1,1],shortdashdotdot:[4,1,1,1,1,1],dot:[1,3],dash:[4,3],longdash:[8,3],dashdot:[4,3,1,3],longdashdot:[8,3,1,3],longdashdotdot:[8,
3,1,3,1,3]};var y=0;g.Shape=m("dojox.gfx.svg.Shape",h.Shape,{destroy:function(){if(this.fillStyle&&"type"in this.fillStyle){var f=this.rawNode.getAttribute("fill");(f=g.getRef(f))&&f.parentNode.removeChild(f)}if(this.clip&&(f=this.rawNode.getAttribute("clip-path")))(f=r.byId(f.match(/gfx_clip[\d]+/)[0]))&&f.parentNode.removeChild(f);h.Shape.prototype.destroy.apply(this,arguments)},setFill:function(f){if(!f)return this.fillStyle=null,this.rawNode.setAttribute("fill","none"),this.rawNode.setAttribute("fill-opacity",
0),this;var a,d=function(f){this.setAttribute(f,a[f].toFixed(8))};if("object"==typeof f&&"type"in f){switch(f.type){case "linear":a=c.makeParameters(c.defaultLinearGradient,f);f=this._setFillObject(a,"linearGradient");b.forEach(["x1","y1","x2","y2"],d,f);break;case "radial":a=c.makeParameters(c.defaultRadialGradient,f);f=this._setFillObject(a,"radialGradient");b.forEach(["cx","cy","r"],d,f);break;case "pattern":a=c.makeParameters(c.defaultPattern,f),f=this._setFillObject(a,"pattern"),b.forEach(["x",
"y","width","height"],d,f)}this.fillStyle=a;return this}this.fillStyle=a=c.normalizeColor(f);this.rawNode.setAttribute("fill",a.toCss());this.rawNode.setAttribute("fill-opacity",a.a);this.rawNode.setAttribute("fill-rule","evenodd");return this},setStroke:function(f){var a=this.rawNode;if(!f)return this.strokeStyle=null,a.setAttribute("stroke","none"),a.setAttribute("stroke-opacity",0),this;if("string"==typeof f||d.isArray(f)||f instanceof k)f={color:f};f=this.strokeStyle=c.makeParameters(c.defaultStroke,
f);f.color=c.normalizeColor(f.color);if(f){var b=0>f.width?0:f.width;a.setAttribute("stroke",f.color.toCss());a.setAttribute("stroke-opacity",f.color.a);a.setAttribute("stroke-width",b);a.setAttribute("stroke-linecap",f.cap);"number"==typeof f.join?(a.setAttribute("stroke-linejoin","miter"),a.setAttribute("stroke-miterlimit",f.join)):a.setAttribute("stroke-linejoin",f.join);var e=f.style.toLowerCase();e in g.dasharray&&(e=g.dasharray[e]);if(e instanceof Array){var e=d._toArray(e),h;for(h=0;h<e.length;++h)e[h]*=
b;if("butt"!=f.cap){for(h=0;h<e.length;h+=2)e[h]-=b,1>e[h]&&(e[h]=1);for(h=1;h<e.length;h+=2)e[h]+=b}e=e.join(",")}a.setAttribute("stroke-dasharray",e);a.setAttribute("dojoGfxStrokeStyle",f.style)}return this},_getParentSurface:function(){for(var f=this.parent;f&&!(f instanceof c.Surface);f=f.parent);return f},_setFillObject:function(f,a){var b=g.xmlns.svg;this.fillStyle=f;var d=this._getParentSurface().defNode,e=this.rawNode.getAttribute("fill");if(e=g.getRef(e))if(e.tagName.toLowerCase()!=a.toLowerCase()){var h=
e.id;e.parentNode.removeChild(e);e=q(b,a);e.setAttribute("id",h);d.appendChild(e)}else for(;e.childNodes.length;)e.removeChild(e.lastChild);else e=q(b,a),e.setAttribute("id",c._base._getUniqueId()),d.appendChild(e);if("pattern"==a)e.setAttribute("patternUnits","userSpaceOnUse"),b=q(b,"image"),b.setAttribute("x",0),b.setAttribute("y",0),b.setAttribute("width",(0>f.width?0:f.width).toFixed(8)),b.setAttribute("height",(0>f.height?0:f.height).toFixed(8)),b.setAttributeNS?b.setAttributeNS(g.xmlns.xlink,
"xlink:href",f.src):b.setAttribute("xlink:href",f.src),e.appendChild(b);else{e.setAttribute("gradientUnits","userSpaceOnUse");for(d=0;d<f.colors.length;++d){var h=f.colors[d],k=q(b,"stop"),l=h.color=c.normalizeColor(h.color);k.setAttribute("offset",h.offset.toFixed(8));k.setAttribute("stop-color",l.toCss());k.setAttribute("stop-opacity",l.a);e.appendChild(k)}}this.rawNode.setAttribute("fill","url(#"+e.getAttribute("id")+")");this.rawNode.removeAttribute("fill-opacity");this.rawNode.setAttribute("fill-rule",
"evenodd");return e},_applyTransform:function(){if(this.matrix){var f=this.matrix;this.rawNode.setAttribute("transform","matrix("+f.xx.toFixed(8)+","+f.yx.toFixed(8)+","+f.xy.toFixed(8)+","+f.yy.toFixed(8)+","+f.dx.toFixed(8)+","+f.dy.toFixed(8)+")")}else this.rawNode.removeAttribute("transform");return this},setRawNode:function(f){f=this.rawNode=f;"image"!=this.shape.type&&f.setAttribute("fill","none");f.setAttribute("fill-opacity",0);f.setAttribute("stroke","none");f.setAttribute("stroke-opacity",
0);f.setAttribute("stroke-width",1);f.setAttribute("stroke-linecap","butt");f.setAttribute("stroke-linejoin","miter");f.setAttribute("stroke-miterlimit",4);f.__gfxObject__=this},setShape:function(f){this.shape=c.makeParameters(this.shape,f);for(var a in this.shape)if("type"!=a){f=this.shape[a];if("width"===a||"height"===a)f=0>f?0:f;this.rawNode.setAttribute(a,f)}this.bbox=null;return this},_moveToFront:function(){this.rawNode.parentNode.appendChild(this.rawNode);return this},_moveToBack:function(){this.rawNode.parentNode.insertBefore(this.rawNode,
this.rawNode.parentNode.firstChild);return this},setClip:function(f){this.inherited(arguments);var a=f?"width"in f?"rect":"cx"in f?"ellipse":"points"in f?"polyline":"d"in f?"path":null:null;if(f&&!a)return this;"polyline"===a&&(f=d.clone(f),f.points=f.points.join(","));var b,c=e.get(this.rawNode,"clip-path");c&&(b=r.byId(c.match(/gfx_clip[\d]+/)[0]))&&b.removeChild(b.childNodes[0]);f?(b?(a=q(g.xmlns.svg,a),b.appendChild(a)):(c="gfx_clip"+ ++y,this.rawNode.setAttribute("clip-path","url(#"+c+")"),b=
q(g.xmlns.svg,"clipPath"),a=q(g.xmlns.svg,a),b.appendChild(a),this.rawNode.parentNode.insertBefore(b,this.rawNode),e.set(b,"id",c)),e.set(a,f)):(this.rawNode.removeAttribute("clip-path"),b&&b.parentNode.removeChild(b));return this},_removeClipNode:function(){var a,b=e.get(this.rawNode,"clip-path");b&&(a=r.byId(b.match(/gfx_clip[\d]+/)[0]))&&a.parentNode.removeChild(a);return a}});g.Group=m("dojox.gfx.svg.Group",g.Shape,{constructor:function(){h.Container._init.call(this)},setRawNode:function(a){this.rawNode=
a;this.rawNode.__gfxObject__=this},destroy:function(){this.clear(!0);g.Shape.prototype.destroy.apply(this,arguments)}});g.Group.nodeType="g";g.Rect=m("dojox.gfx.svg.Rect",[g.Shape,h.Rect],{setShape:function(a){this.shape=c.makeParameters(this.shape,a);this.bbox=null;for(var b in this.shape)if("type"!=b&&"r"!=b){a=this.shape[b];if("width"===b||"height"===b)a=0>a?0:a;this.rawNode.setAttribute(b,a)}null!=this.shape.r&&(this.rawNode.setAttribute("ry",this.shape.r),this.rawNode.setAttribute("rx",this.shape.r));
return this}});g.Rect.nodeType="rect";g.Ellipse=m("dojox.gfx.svg.Ellipse",[g.Shape,h.Ellipse],{});g.Ellipse.nodeType="ellipse";g.Circle=m("dojox.gfx.svg.Circle",[g.Shape,h.Circle],{});g.Circle.nodeType="circle";g.Line=m("dojox.gfx.svg.Line",[g.Shape,h.Line],{});g.Line.nodeType="line";g.Polyline=m("dojox.gfx.svg.Polyline",[g.Shape,h.Polyline],{setShape:function(a,b){a&&a instanceof Array?(this.shape=c.makeParameters(this.shape,{points:a}),b&&this.shape.points.length&&this.shape.points.push(this.shape.points[0])):
this.shape=c.makeParameters(this.shape,a);this.bbox=null;this._normalizePoints();for(var d=[],e=this.shape.points,g=0;g<e.length;++g)d.push(e[g].x.toFixed(8),e[g].y.toFixed(8));this.rawNode.setAttribute("points",d.join(" "));return this}});g.Polyline.nodeType="polyline";g.Image=m("dojox.gfx.svg.Image",[g.Shape,h.Image],{setShape:function(a){this.shape=c.makeParameters(this.shape,a);this.bbox=null;a=this.rawNode;for(var b in this.shape)if("type"!=b&&"src"!=b){var d=this.shape[b];if("width"===b||"height"===
b)d=0>d?0:d;a.setAttribute(b,d)}a.setAttribute("preserveAspectRatio","none");a.setAttributeNS?a.setAttributeNS(g.xmlns.xlink,"xlink:href",this.shape.src):a.setAttribute("xlink:href",this.shape.src);a.__gfxObject__=this;return this}});g.Image.nodeType="image";g.Text=m("dojox.gfx.svg.Text",[g.Shape,h.Text],{setShape:function(a){this.shape=c.makeParameters(this.shape,a);this.bbox=null;a=this.rawNode;var b=this.shape;a.setAttribute("x",b.x);a.setAttribute("y",b.y);a.setAttribute("text-anchor",b.align);
a.setAttribute("text-decoration",b.decoration);a.setAttribute("rotate",b.rotated?90:0);a.setAttribute("kerning",b.kerning?"auto":0);a.setAttribute("text-rendering",x);a.firstChild?a.firstChild.nodeValue=b.text:a.appendChild(t(b.text));return this},getTextWidth:function(){var a=this.rawNode,b=a.parentNode,a=a.cloneNode(!0);a.style.visibility="hidden";var c=0,d=a.firstChild.nodeValue;b.appendChild(a);if(""!=d)for(;!c;)c=a.getBBox?parseInt(a.getBBox().width):68;b.removeChild(a);return c},getBoundingBox:function(){var a=
null;if(this.getShape().text)try{a=this.rawNode.getBBox()}catch(b){a={x:0,y:0,width:0,height:0}}return a}});g.Text.nodeType="text";g.Path=m("dojox.gfx.svg.Path",[g.Shape,a.Path],{_updateWithSegment:function(a){this.inherited(arguments);"string"==typeof this.shape.path&&this.rawNode.setAttribute("d",this.shape.path)},setShape:function(a){this.inherited(arguments);this.shape.path?this.rawNode.setAttribute("d",this.shape.path):this.rawNode.removeAttribute("d");return this}});g.Path.nodeType="path";g.TextPath=
m("dojox.gfx.svg.TextPath",[g.Shape,a.TextPath],{_updateWithSegment:function(a){this.inherited(arguments);this._setTextPath()},setShape:function(a){this.inherited(arguments);this._setTextPath();return this},_setTextPath:function(){if("string"==typeof this.shape.path){var a=this.rawNode;if(!a.firstChild){var b=q(g.xmlns.svg,"textPath"),d=t("");b.appendChild(d);a.appendChild(b)}b=(b=a.firstChild.getAttributeNS(g.xmlns.xlink,"href"))&&g.getRef(b);if(!b&&(d=this._getParentSurface())){var d=d.defNode,
b=q(g.xmlns.svg,"path"),e=c._base._getUniqueId();b.setAttribute("id",e);d.appendChild(b);a.firstChild.setAttributeNS?a.firstChild.setAttributeNS(g.xmlns.xlink,"xlink:href","#"+e):a.firstChild.setAttribute("xlink:href","#"+e)}b&&b.setAttribute("d",this.shape.path)}},_setText:function(){var a=this.rawNode;if(!a.firstChild){var b=q(g.xmlns.svg,"textPath"),c=t("");b.appendChild(c);a.appendChild(b)}a=a.firstChild;b=this.text;a.setAttribute("alignment-baseline","middle");switch(b.align){case "middle":a.setAttribute("text-anchor",
"middle");a.setAttribute("startOffset","50%");break;case "end":a.setAttribute("text-anchor","end");a.setAttribute("startOffset","100%");break;default:a.setAttribute("text-anchor","start"),a.setAttribute("startOffset","0%")}a.setAttribute("baseline-shift","0.5ex");a.setAttribute("text-decoration",b.decoration);a.setAttribute("rotate",b.rotated?90:0);a.setAttribute("kerning",b.kerning?"auto":0);a.firstChild.data=b.text}});g.TextPath.nodeType="text";var z=534<function(){var a=/WebKit\/(\d*)/.exec(v);
return a?a[1]:0}();g.Surface=m("dojox.gfx.svg.Surface",h.Surface,{constructor:function(){h.Container._init.call(this)},destroy:function(){h.Container.clear.call(this,!0);this.defNode=null;this.inherited(arguments)},setDimensions:function(a,b){if(!this.rawNode)return this;var c=0>a?0:a,d=0>b?0:b;this.rawNode.setAttribute("width",c);this.rawNode.setAttribute("height",d);z&&(this.rawNode.style.width=c,this.rawNode.style.height=d);return this},getDimensions:function(){return this.rawNode?{width:c.normalizedLength(this.rawNode.getAttribute("width")),
height:c.normalizedLength(this.rawNode.getAttribute("height"))}:null}});g.createSurface=function(a,b,d){var e=new g.Surface;e.rawNode=q(g.xmlns.svg,"svg");e.rawNode.setAttribute("overflow","hidden");b&&e.rawNode.setAttribute("width",0>b?0:b);d&&e.rawNode.setAttribute("height",0>d?0:d);b=q(g.xmlns.svg,"defs");e.rawNode.appendChild(b);e.defNode=b;e._parent=r.byId(a);e._parent.appendChild(e.rawNode);c._base._fixMsTouchAction(e);return e};p={_setFont:function(){var a=this.fontStyle;this.rawNode.setAttribute("font-style",
a.style);this.rawNode.setAttribute("font-variant",a.variant);this.rawNode.setAttribute("font-weight",a.weight);this.rawNode.setAttribute("font-size",a.size);this.rawNode.setAttribute("font-family",a.family)}};var s=h.Container;m=g.Container={openBatch:function(){if(!this._batch){var a;a=g.useSvgWeb?n.doc.createDocumentFragment(!0):n.doc.createDocumentFragment();this.fragment=a}++this._batch;return this},closeBatch:function(){this._batch=0<this._batch?--this._batch:0;this.fragment&&!this._batch&&(this.rawNode.appendChild(this.fragment),
delete this.fragment);return this},add:function(a){this!=a.getParent()&&(this.fragment?this.fragment.appendChild(a.rawNode):this.rawNode.appendChild(a.rawNode),s.add.apply(this,arguments),a.setClip(a.clip));return this},remove:function(a,b){this==a.getParent()&&(this.rawNode==a.rawNode.parentNode&&this.rawNode.removeChild(a.rawNode),this.fragment&&this.fragment==a.rawNode.parentNode&&this.fragment.removeChild(a.rawNode),a._removeClipNode(),s.remove.apply(this,arguments));return this},clear:function(){for(var a=
this.rawNode;a.lastChild;)a.removeChild(a.lastChild);var b=this.defNode;if(b){for(;b.lastChild;)b.removeChild(b.lastChild);a.appendChild(b)}return s.clear.apply(this,arguments)},getBoundingBox:s.getBoundingBox,_moveChildToFront:s._moveChildToFront,_moveChildToBack:s._moveChildToBack};a=g.Creator={createObject:function(a,b){if(!this.rawNode)return null;var c=new a,d=q(g.xmlns.svg,a.nodeType);c.setRawNode(d);c.setShape(b);this.add(c);return c}};d.extend(g.Text,p);d.extend(g.TextPath,p);d.extend(g.Group,
m);d.extend(g.Group,h.Creator);d.extend(g.Group,a);d.extend(g.Surface,m);d.extend(g.Surface,h.Creator);d.extend(g.Surface,a);g.fixTarget=function(a,b){a.gfxTarget||(a.gfxTarget=w&&a.target.wholeText?a.target.parentElement.__gfxObject__:a.target.__gfxObject__);return!0};g.useSvgWeb&&(g.createSurface=function(a,b,d){var e=new g.Surface;b=0>b?0:b;d=0>d?0:d;if(!b||!d){var h=l.position(a);b=b||h.w;d=d||h.h}a=r.byId(a);var h=a.id?a.id+"_svgweb":c._base._getUniqueId(),k=q(g.xmlns.svg,"svg");k.id=h;k.setAttribute("width",
b);k.setAttribute("height",d);svgweb.appendChild(k,a);k.addEventListener("SVGLoad",function(){e.rawNode=this;e.isLoaded=!0;var a=q(g.xmlns.svg,"defs");e.rawNode.appendChild(a);e.defNode=a;if(e.onLoad)e.onLoad(e)},!1);e.isLoaded=!1;return e},g.Surface.extend({destroy:function(){var a=this.rawNode;svgweb.removeChild(a,a.parentNode)}}),p={connect:function(a,b,c){"on"===a.substring(0,2)&&(a=a.substring(2));c=2==arguments.length?b:d.hitch(b,c);this.getEventSource().addEventListener(a,c,!1);return[this,
a,c]},disconnect:function(a){this.getEventSource().removeEventListener(a[1],a[2],!1);delete a[0]}},d.extend(g.Shape,p),d.extend(g.Surface,p));return g});