// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
define("esri/graphic","dojo/_base/declare dojo/_base/lang dojo/has ./kernel ./domUtils ./lang ./InfoTemplate ./geometry/jsonUtils ./symbols/jsonUtils".split(" "),function(f,h,m,n,k,l,p,q,r){f=f(null,{declaredClass:"esri.Graphic",constructor:function(a,b,c,d){a&&!a.declaredClass?(this.geometry=a.geometry?q.fromJson(a.geometry):null,this.symbol=a.symbol?r.fromJson(a.symbol):null,this.attributes=a.attributes||null,this.infoTemplate=a.infoTemplate?new p(a.infoTemplate):null):(this.geometry=a,this.symbol=
b,this.attributes=c,this.infoTemplate=d)},_shape:null,_graphicsLayer:null,_visible:!0,visible:!0,getDojoShape:function(){return this._shape},getShapes:function(){var a=[];this._shape&&a.push(this._shape);this._bgShape&&a.push(this._bgShape);return a},getNode:function(){var a=this._shape&&this._shape.getNode();return a&&a.nodeType?a:null},getNodes:function(){var a=this.getShapes(),b,c,d=a.length,e=[];for(c=0;c<d;c++)(b=a[c]&&a[c].getNode())&&b.nodeType&&e.push(b);return e},getLayer:function(){return this._layer},
draw:function(){var a=this._graphicsLayer;a&&a._draw(this,!0);return this},setGeometry:function(a){this.geometry=a;if(a=this._graphicsLayer)a._updateExtent(this),a._draw(this,!0);return this},setSymbol:function(a,b){var c=this._graphicsLayer,d=this._shape;this.symbol=a;c&&(b&&d&&c._removeShape(this),c._draw(this,!0));return this},setAttributes:function(a){this.attributes=a;this._clearCache();return this},setInfoTemplate:function(a){this.infoTemplate=a;return this},getInfoTemplate:function(){return this._getEffInfoTemplate()},
_getEffInfoTemplate:function(){var a=this.getLayer();return this.infoTemplate||a&&a.infoTemplate},getTitle:function(){var a=this.getInfoTemplate(),b=a&&a.title;if(h.isFunction(b))b=b.call(a,this);else if(h.isString(b))var c=(a=this.getLayer())&&a._getDateOpts,b=l.substitute(this.attributes,b,{first:!0,dateFormat:c&&c.call(a)});return b},getContent:function(){var a=this.getInfoTemplate(),b=a&&a.content;if(h.isFunction(b))b=b.call(a,this);else if(h.isString(b))var c=(a=this.getLayer())&&a._getDateOpts,
b=l.substitute(this.attributes,b,{dateFormat:c&&c.call(a)});return b},attr:function(a,b){var c=this.getNodes(),d,e=c.length;for(d=0;d<e;d++)null==b?c[d].removeAttribute(a):c[d].setAttribute(a,b);return this},show:function(){this.visible=this._visible=!0;var a,b,c;if(this.getShapes().length){a=this.getNodes();c=a.length;this.attr("data-hidden");for(b=0;b<c;b++)k.show(a[b])}else this._graphicsLayer&&this._graphicsLayer._draw(this,!0);return this},hide:function(){this.visible=this._visible=!1;var a=
this._graphicsLayer,b,c;if(a)if("canvas-2d"===a.surfaceType)a._removeShape(this);else if(a=this.getNodes(),c=a.length){this.attr("data-hidden","");for(b=0;b<c;b++)k.hide(a[b])}return this},toJson:function(){var a={};this.geometry&&(a.geometry=this.geometry.toJson());this.attributes&&(a.attributes=h.mixin({},this.attributes));this.symbol&&(a.symbol=this.symbol.toJson());this.infoTemplate&&(a.infoTemplate=this.infoTemplate.toJson());return a},_getDataValue:function(a,b,c){var d=this._getCacheItem(a,
b);if(void 0===d.value){var e=null,g=this.attributes,f=a.field;if(b.exprTree)e=c.executeExpression(b.exprTree,c.createExecContext(this));else if(h.isFunction(f))e=f(this);else if(g&&(e=g[f],(a=a.normalizationField)&&this._isValidNumber(e)))g=parseFloat(g[a]),e=this._isValidNumber(g)&&0!==g?e/g:null;this._isValidNumber(e)||(e=null);d.value=e}return d.value},_isValidNumber:function(a){return"number"===typeof a&&!isNaN(a)},_getCacheItem:function(a,b){var c=this._findCacheItem(a);c?c.version!==b.version&&
(c.version=b.version,c.value=void 0):c=this._createCacheItem(a,b);return c},_findCacheItem:function(a){var b,c=this._cache;if(c){var d,e=c.length;for(d=0;d<e;d++){var f=c[d];if(f.variable===a){b=f;break}}}return b},_createCacheItem:function(a,b){var c=this._cache;c||(c=this._cache=[]);var d={variable:a,version:b.version,value:void 0};c.push(d);return d},_clearCache:function(){this._cache=null}});f.prototype.getShape=f.prototype.getDojoShape;m("extend-esri")&&(n.Graphic=f);return f});