// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
define("esri/urlUtils","dojo/_base/lang dojo/_base/array dojo/_base/url dojo/io-query ./kernel ./config ./sniff dojo/i18n!./nls/jsapi".split(" "),function(k,s,m,r,l,t,q,u){var n=function(){return this}(),b={},p=t.defaults.io,v=/^[a-z][a-z0-9\+\-\.]*:/i;b.isHTTP=function(a){var c=n.location.protocol;return null==a?"http:"===c||"https:"===c:a?"https:"===c:"http:"===c};b.getProtocolForWebResource=function(a){return b.isHTTP()?n.location.protocol:a?"https:":"http:"};b.urlToObject=function(a){var c={},
b=new m(a),e=a.indexOf("?");null===b.query?c={path:a,query:null}:(c.path=a.substring(0,e),c.query=r.queryToObject(b.query));b.fragment&&(c.hash=b.fragment,null===b.query&&(c.path=c.path.substring(0,c.path.length-(b.fragment.length+1))));return c};b.getProxyUrl=function(a,c){var d=k.isString(a)?0===k.trim(a).toLowerCase().indexOf("https:"):a,e=p.proxyUrl,f,g,h=u.io.proxyNotSet;if(k.isString(a)&&(g=b.getProxyRule(a)))e=g.proxyUrl;if(!e)throw console.log(h),Error(h);d&&(!1!==c&&0!==n.location.href.toLowerCase().indexOf("https:"))&&
(d=e,0!==d.toLowerCase().indexOf("http")&&(d=b.getAbsoluteUrl(d)),d=d.replace(/^http:/i,"https:"),b.canUseXhr(d)&&(e=d,f=1));e=b.urlToObject(e);e._xo=f;return e};b.addProxy=function(a){var c=b.getProxyRule(a),d;c?d=b.urlToObject(c.proxyUrl):p.alwaysUseProxy&&(d=b.getProxyUrl());d&&(c=b.urlToObject(a),a=d.path+"?"+c.path,(d=r.objectToQuery(k.mixin(d.query||{},c.query)))&&(a+="?"+d));return a};b.addProxyRule=function(a){var c=a.urlPrefix=b.urlToObject(a.urlPrefix).path.replace(/([^\/])$/,"$1/").replace(/^https?:\/\//ig,
"").toLowerCase(),d=p.proxyRules,e,f=d.length,g,h=f;for(e=0;e<f;e++)if(g=d[e].urlPrefix,0===c.indexOf(g)){if(c.length===g)return-1;h=e;break}else 0===g.indexOf(c)&&(h=e+1);d.splice(h,0,a);return h};b.getProxyRule=function(a){var c=p.proxyRules,d=c.length,e=b.urlToObject(a).path.replace(/([^\/])$/,"$1/").replace(/^https?:\/\//ig,"").toLowerCase(),f;for(a=0;a<d;a++)if(0===e.indexOf(c[a].urlPrefix)){f=c[a];break}return f};b.hasSameOrigin=function(a,b,d){a=a.toLowerCase();b=b.toLowerCase();var e=n.location.href.toLowerCase();
a=0===a.indexOf("http")?new m(a):e=new m(e);b=0===b.indexOf("http")?new m(b):k.isString(e)?new m(e):e;return(d||a.scheme===b.scheme)&&a.host===b.host&&a.port===b.port};b.canUseXhr=function(a,c){var d=q("esri-phonegap")?!0:!1,e=b.hasSameOrigin,f=p.corsEnabledServers,g,h=-1;!d&&(q("esri-cors")&&f&&f.length)&&(d=s.some(f,function(b,c){var d=b&&"object"===typeof b?b.host:b;return d&&(g=0!==k.trim(d).toLowerCase().indexOf("http"),e(a,g?"http://"+d:d)||g&&e(a,"https://"+d))?(h=c,!0):!1}));return c?h:d};
b.getAbsoluteUrl=function(a){var c=b.getProtocolForWebResource();return k.isString(a)&&!v.test(a)?0===a.indexOf("//")?c+a:0===a.indexOf("/")?c+"//"+n.location.host+a:l._appBaseUrl+a:a};b.fixUrl=function(a){/^\/\//i.test(a)&&(a=b.getProtocolForWebResource()+a);return a=a.replace(/^(https?:\/\/)(arcgis\.com)/i,"$1www.$2")};b.normalize=function(a){a=b._ensureProtocol(a);return a=b._ensureProperProtocolForAGOResource(a)};b._ensureProtocol=function(a){if(!a)return a;/^\/\//i.test(a)&&(a=b.getProtocolForWebResource(!0)+
a);return a};b._ensureProperProtocolForAGOResource=function(a){return!b.isHTTP(!1)&&(/^http\:\/\/server\.arcgisonline\.com(?!:)/i.test(a)||/^http\:\/\/services\.arcgisonline\.com(?!:)/i.test(a)||/^http\:\/\/.+\.arcgis\.com(?!:)/i.test(a))?a.replace(/http:/i,"https:"):a};q("extend-esri")&&(k.mixin(l,b),l._getProxyUrl=b.getProxyUrl,l._getProxiedUrl=b.addProxy,l._hasSameOrigin=b.hasSameOrigin,l._canDoXOXHR=b.canUseXhr,l._getAbsoluteUrl=b.getAbsoluteUrl,l.fixUrl=b.fixUrl);return b});