// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/vectorTiles/Placement",["require","exports","./Geometry","./GeometryUtils","./Conflict"],function(z,v,r,d,B){z=function(){return function(d,a,b,g,c){void 0===b&&(b=0);void 0===g&&(g=-1);void 0===c&&(c=q);this.x=d;this.y=a;this.angle=b;this.segment=g;this.minzoom=c}}();v.Anchor=z;z=function(){return function(d,a,b){this.glyph=d;this.x=a;this.y=b}}();v.ShapedGlyph=z;var U=function(){return function(h,a,b,g,c,e){void 0===g&&(g=!1);void 0===c&&(c=q);void 0===e&&(e=
d.C_INFINITY);this.anchor=h;this.labelAngle=a;this.glyphAngle=b;this.upsideDown=g;this.minzoom=c;this.maxzoom=e}}(),W=function(){return function(d,a,b,g,c,e,V,n,r){this.tl=d;this.tr=a;this.bl=b;this.br=g;this.mosaicRect=c;this.labelAngle=e;this.anchor=V;this.minzoom=n;this.maxzoom=r}}();v.PlacedSymbol=W;var X=function(){return function(d,a){this.footprint=d;this.shapes=a}}();v.Placement=X;var q=0.5;z=function(){function h(a){this.mapAngle=a;this._conflictEngine=new B.ConflictEngine(a)}h.prototype.getIconPlacement=
function(a,b,g,c,e,V){var n=b.width/b.pixelRatio,h=b.height/b.pixelRatio;c=e.offset[0]-n/2;var s=e.offset[1]-h/2,n=c+n,h=s+h,G=b.rect,C=new r.Point(c,s),m=new r.Point(c+G.width/b.pixelRatio,s+G.height/b.pixelRatio),l=new r.Point(c,m.y),p=new r.Point(m.x,s),t=e.rotate*d.C_DEG_TO_RAD;b=1===e.rotationAlignment;0<=a.segment&&!b&&(t+=a.angle);if(0!==t){var f=Math.cos(t),k=Math.sin(t);C.rotate(f,k);m.rotate(f,k);l.rotate(f,k);p.rotate(f,k)}f=8*e.padding;k=new r.Point(a.x,a.y);a=new B.Footprint(this.mapAngle,
f,b);a.addBox(k,new B.Box(c,s,n,h),g,t,q,d.C_INFINITY);g=new W(C,p,l,m,G,0,k,q,d.C_INFINITY);g=new X(a,[g]);c=q;e.allowOverlap||(c=this._conflictEngine.getMinZoom(g.footprint,c,V,b));a.minzoom=c;return g};h.prototype.getTextPlacement=function(a,b,g,c,e,h,n,z){for(var s=new r.Point(a.x,a.y),G=Math.cos(n.maxAngle*d.C_DEG_TO_RAD),C=n.rotate*d.C_DEG_TO_RAD,m=0===n.rotationAlignment,l=n.keepUpright,p=q,t=!m,f=t?0:a.angle,k=0<=a.segment&&m,w=new B.Footprint(this.mapAngle,8*n.padding,t),ca=[],v=!k,D=Number.POSITIVE_INFINITY,
E=Number.NEGATIVE_INFINITY,J=D,K=E,da=k?l:m&&l,Y,Z=0;Z<g.length;Z++){var A=g[Z],u=c[A.glyph];if(u){var H=u.rect;if(H&&!(0>=H.width||0>=H.height)){var F=u.metrics;v&&(Y&&Y!==A.y&&(w.addBox(s,new B.Box(D,J,E,K),e,C,q,d.C_INFINITY),D=Number.POSITIVE_INFINITY,E=Number.NEGATIVE_INFINITY,J=D,K=E),Y=A.y);var I=[];if(k){if(u=(b.x+A.x+F.left-3+0.5*u.metrics.width)*e,p=this._placeGlyph(a,p,u,h,a.segment,1,G,I),l&&(p=this._placeGlyph(a,p,u,h,a.segment,-1,G,I)),2<=p)break}else I.push(new U(s,f,f)),m&&l&&I.push(new U(s,
f+d.C_PI,f+d.C_PI,!0));for(var u=A.x+b.x+F.left,A=A.y+b.y-F.top,$=u+F.width,F=A+F.height,L=new r.Point(u-3,A-3),aa=new r.Point(L.x+H.width,L.y+H.height),ea=new r.Point(L.x,aa.y),fa=new r.Point(aa.x,L.y),ba=0;ba<I.length;ba++){var x=I[ba],O=L.clone(),P=ea.clone(),Q=fa.clone(),R=aa.clone(),M=A,N=F;if(x.upsideDown){var y=-48*n.offset[1],M=M+y,N=N+y;O.y+=y;P.y+=y;Q.y+=y;R.y+=y}y=x.glyphAngle+C;if(0!==y){var S=Math.cos(y),T=Math.sin(y);O.rotate(S,T);R.rotate(S,T);P.rotate(S,T);Q.rotate(S,T)}ca.push(new W(O,
Q,P,R,H,x.labelAngle,x.anchor,x.minzoom,x.maxzoom));if(!da||this._legible(x.labelAngle))v?(u<D&&(D=u),M<J&&(J=M),$>E&&(E=$),N>K&&(K=N)):2>x.minzoom&&w.addBox(x.anchor,new B.Box(u,M,$,N),e,y,x.minzoom,x.maxzoom)}}}}if(2<=p)return null;v&&w.addBox(s,new B.Box(D,J,E,K),e,C,q,d.C_INFINITY);a=new X(w,ca);n.allowOverlap||(p=this._conflictEngine.getMinZoom(a.footprint,p,z,t));w.minzoom=p;return a};h.prototype.add=function(a){this._conflictEngine.add(a.footprint)};h.prototype._legible=function(a){a=d.radToByte(a);
return 65>a||193<=a};h.prototype._placeGlyph=function(a,b,g,c,e,h,n,v){var s=0>h?d.positiveMod(a.angle+d.C_PI,d.C_2PI):a.angle,z=this._legible(s),C=0;0>g&&(h*=-1,g*=-1,C=d.C_PI);0<h&&++e;a=new r.Point(a.x,a.y);var m=c[e],l=d.C_INFINITY,p,t;if(c.length<=e)return l;for(;;){var f=m.x-a.x,k=m.y-a.y,w=Math.sqrt(f*f+k*k),q=Math.max(g/w,b),f=f/w,k=k/w,B=d.positiveMod(Math.atan2(k,f)+C,d.C_2PI);if(void 0!==p&&f*p+k*t<n)return l;p=f;t=k;v.push(new U(a,s,B,z,q,l));if(q<=b)return q;a=m.clone();do{e+=h;if(c.length<=
e||0>e)return q;m=c[e]}while(a.isEqual(m));l=m.x-a.x;f=m.y-a.y;k=Math.sqrt(l*l+f*f);l*=w/k;f*=w/k;a.x-=l;a.y-=f;l=q}};return h}();v.PlacementEngine=z});