// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
define("esri/layers/vectorTiles/views/vectorTiles/SymbolBucket","require exports ../../core/tsSupport/extendsHelper ../../core/tsSupport/decorateHelper ./Bucket ./Geometry ./style/StyleLayer ./Placement ./GeometryUtils ./TextShaping dojox/string/BidiEngine".split(" "),function(J,K,D,L,E,x,A,B,t,F,G){var H=function(){return function(){}}(),I=function(){return function(t,e,l,g){this.line=e;this.shaping=t;this.iconMosaicItem=l;this.anchor=g}}();return function(C){function e(l,g,b,c,a,f,e,r){C.call(this,
l,g);this._markerRatio=1;this._markerVertexBuffer=b;this._markerIndexBuffer=c;this._textVertexBuffer=a;this._textIndexBuffer=f;this._placementEngine=e;this._workerTileHandler=r}D(e,C);Object.defineProperty(e.prototype,"markerIndexStart",{get:function(){return this._markerTriangleElementsStart},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"markerIndexCount",{get:function(){return this._markerTriangleElementsNum},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,
"textIndexStart",{get:function(){return this._textTriangleElementsStart},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"textIndexCount",{get:function(){return this._textTriangleElementsNum},enumerable:!0,configurable:!0});Object.defineProperty(e.prototype,"sdfMarker",{get:function(){return!1},enumerable:!0,configurable:!0});e.prototype.copy=function(l,g,b,c,a){a=new e(this.layer,this.zoom,l,g,b,c,a,this._workerTileHandler);a.layerIndex=this.layerIndex;a.layerExtent=this.layerExtent;
a._markerVertexStart=l.index;a._markerTriangleElementsStart=g.index;a._textVertexStart=b.index;a._textTriangleElementsStart=c.index;a._markerTriangleElementsNum=0;a._textTriangleElementsNum=0;a._symbolInstances=this._symbolInstances;a._glyphItems=this._glyphItems;a._textLayout=this._textLayout;a._markerLayout=this._markerLayout;a._isLinePlacement=this._isLinePlacement;a._avoidEdges=this._avoidEdges;return a};e.prototype.getResources=function(l,g,b){var c=this.layer,a=this.zoom;l&&l.setExtent(this.layerExtent);
for(var f=c.getLayoutValue("icon-image",a),y=c.getLayoutValue("text-field",a),r=c.getLayoutValue("text-font",a),c=c.getLayoutValue("text-transform",a),a=[],q=0,u=this._features;q<u.length;q++){var n=u[q],s=n.getGeometry(l);if(s&&0!==s.length){var m=void 0;f&&(m=this._replaceKeys(f,n.values))&&g.add(m);var d=void 0,p=!1;if(y){d=this._replaceKeys(y,n.values);switch(c){case 2:d=d.toLowerCase();break;case 1:d=d.toUpperCase()}e._bidiEngine.hasBidiChar(d)&&(p=void 0,p="rtl"===e._bidiEngine.checkContextual(d)?
"IDNNN":"ICNNN",d=e._bidiEngine.bidiTransform(d,p,"VLYSN"),p=!0);n=d.length;if(0<n){var k=b[r];k||(k=b[r]=new Set);for(var h=0;h<n;h++){var v=d.charCodeAt(h);k.add(v)}}}if(m||d)n=new H,n.sprite=m,n.label=d,n.rtl=p,n.geometry=s,a.push(n)}}this._symbolFeatures=a};e.prototype.processFeatures=function(l,g){l&&l.setExtent(this.layerExtent);var b=this.layer,c=this.zoom,a=this._isLinePlacement=1===b.getLayoutValue("symbol-placement",c),f=this._avoidEdges=b.getLayoutValue("symbol-avoid-edges",c)&&!a,y=b.getLayoutValue("symbol-spacing",
c),r=b.getLayoutValue("icon-image",c),q=b.getLayoutValue("text-field",c),u=this._workerTileHandler,n;r&&(this._markerLayout=new A.IconLayout(b,c,a),n=u.getSpriteItems());var s,m;if(q){var d=this._textLayout=new A.TextLayout(b,c,a);s=void 0;d.font&&d.font.length&&(s=d.font[0]);m=0.5;switch(d.anchor){case 5:case 1:case 7:m=0;break;case 6:case 2:case 8:m=1}b=0.5;switch(d.anchor){case 5:case 3:case 6:b=0;break;case 7:case 4:case 8:b=1}c=0.5;switch(d.justify){case 0:c=0;break;case 2:c=1}var r=24*d.letterSpacing,
q=a?0:24*d.maxWidth,p=24*d.lineHeight,d=[24*d.offset[0],24*d.offset[1]];s=u.getGlyphItems(s);m=new F(s,q,p,r,d,m,b,c)}this._markerVertexStart=this._markerVertexBuffer.index;this._markerTriangleElementsStart=this._markerIndexBuffer.index;this._textVertexStart=this._textVertexBuffer.index;this._textTriangleElementsStart=this._textIndexBuffer.index;this._textTriangleElementsNum=this._markerTriangleElementsNum=0;this._symbolInstances=u=[];this._glyphItems=s;c=this._textLayout;b=1;c&&c.size&&(b=c.size/
24);c=0;for(r=this._symbolFeatures;c<r.length;c++){var k=r[c],q=void 0;k.sprite&&(q=n[k.sprite]);var p=void 0,h=k.label,d=0;if(h&&(p=m.getShaping(h,k.rtl))&&0<p.length){for(var d=1E30,h=-1E30,v=0,t=p;v<t.length;v++)var w=t[v],d=Math.min(d,w.x),h=Math.max(h,w.x);d=(h-d+48)*b}h=0;for(k=k.geometry;h<k.length;h++){v=k[h];w=void 0;w=a?e._findAnchors(v,y,8,d):[new B.Anchor(v[0].x,v[0].y)];for(t=0;t<w.length;t++){var z=w[t],x=0>z.x||4096<z.x||0>z.y||4096<z.y;(!f||!x)&&u.push(new I(p,v,q,z))}}}for(a=0;a<
u.length;a++)this._processFeature(u[a],s,f)};e.prototype.updateSymbols=function(){this._markerVertexStart=this._markerVertexBuffer.index;this._markerTriangleElementsStart=this._markerIndexBuffer.index;this._textVertexStart=this._textVertexBuffer.index;this._textTriangleElementsStart=this._textIndexBuffer.index;this._textTriangleElementsNum=this._markerTriangleElementsNum=0;for(var l=this._glyphItems,g=this._avoidEdges,b=0,c=this._symbolInstances;b<c.length;b++)this._processFeature(c[b],l,g)};e.prototype._replaceKeys=
function(l,g){return l.replace(/{([^{}]+)}/g,function(b,c){return c in g?g[c]:""})};e.prototype._processFeature=function(l,g,b){var c=l.line,a=l.iconMosaicItem,f=l.shaping,e=l.anchor,r=(l=this._markerLayout)&&!!a,q=!0,u=1;r&&(u=8*(l.size/(1/this._markerRatio)),q=l.optional||!a);var n=this._textLayout,s=n&&f&&0<f.length,m;m=1;var d=!0;s&&(m=n.size/24,m*=8,d=n.optional||!f||0===f.length);var p=new x.Point(0,-17),k;if(r){k=this._placementEngine.getIconPlacement(e,a,u,c,l,b);if(k.footprint.minzoom===
t.C_INFINITY&&!q)return;e.minzoom>k.footprint.minzoom&&(k.footprint.minzoom=e.minzoom)}var h;if(s&&(h=this._placementEngine.getTextPlacement(e,p,f,g,m,c,n,b))){if(h.footprint.minzoom===t.C_INFINITY&&!d)return;e.minzoom>h.footprint.minzoom&&(h.footprint.minzoom=e.minzoom)}if(!d&&!q||!q&&h&&h.footprint.minzoom!==t.C_INFINITY||!d&&k&&k.footprint.minzoom!==t.C_INFINITY)g=Math.max(k.footprint.minzoom,h.footprint.minzoom),k.footprint.minzoom=g,h.footprint.minzoom=g;h&&h.footprint.minzoom!==t.C_INFINITY&&
(n.ignorePlacement||this._placementEngine.add(h),this._addPlacedSymbols(h.shapes,h.footprint.minzoom,this.zoom,!1));k&&k.footprint.minzoom!==t.C_INFINITY&&(l.ignorePlacement||this._placementEngine.add(k),this._addPlacedSymbols(k.shapes,k.footprint.minzoom,this.zoom,!0))};e.prototype._addPlacedSymbols=function(l,g,b,c){g=t.log2(g)+b;for(var a=0;a<l.length;a++){var f=l[a],e=Math.max(b+t.log2(f.minzoom),g),r=Math.min(b+t.log2(f.maxzoom),25);if(!(r<=e)){var q=f.tl,u=f.tr,n=f.bl,s=f.br,m=f.mosaicRect,
d=-f.labelAngle,f=f.anchor,p=c?this._markerVertexBuffer:this._textVertexBuffer,k=c?this._markerIndexBuffer:this._textIndexBuffer,h=p.index,v=m.x,x=m.y,w=v+m.width,m=x+m.height;p.add(f.x,f.y,q.x,q.y,v,x,d,e,r,g);p.add(f.x,f.y,u.x,u.y,w,x,d,e,r,g);p.add(f.x,f.y,n.x,n.y,v,m,d,e,r,g);p.add(f.x,f.y,s.x,s.y,w,m,d,e,r,g);k.add(h+0,h+1,h+2);k.add(h+1,h+2,h+3);c?this._markerTriangleElementsNum+=6:this._textTriangleElementsNum+=6}}};e._findAnchors=function(e,g,b,c){c*=b;g=g*b+c;var a=0,f=e.length-1;for(b=0;b<
f;b++)a+=x.Point.distance(e[b],e[b+1]);b=c||g;b*=0.5;if(a<=b)return[];c=b/a;g=a/Math.max(Math.round(a/g),1);var a=0,f=-g/2,y=[],r=e.length-1;for(b=0;b<r;b++){for(var q=e[b],u=e[b+1],n=u.x-q.x,s=u.y-q.y,m=Math.sqrt(n*n+s*s),d=void 0;f+g<a+m;){var f=f+g,p=(f-a)/m,k=t.interpolate(q.x,u.x,p),p=t.interpolate(q.y,u.y,p);void 0===d&&(d=Math.atan2(s,n));y.push(new B.Anchor(k,p,d,b,c))}a+=m}return y};e._bidiEngine=new G;return e}(E)});