// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
define("esri/arcade/functions/string",["require","exports","../languageUtils","../Feature"],function(m,l,d,k){l.registerFunctions=function(g,f){g.trim=function(c,e){return f(c,e,function(b,h,a){d.pcCheck(a,1,1);return d.toString(a[0]).trim()})};g.upper=function(c,e){return f(c,e,function(b,h,a){d.pcCheck(a,1,1);return d.toString(a[0]).toUpperCase()})};g.proper=function(c,e){return f(c,e,function(b,h,a){d.pcCheck(a,1,2);b=1;2===a.length&&"firstword"===d.toString(a[1]).toLowerCase()&&(b=2);h=/\s/;a=
d.toString(a[0]);for(var c="",e=!0,g=0;g<a.length;g++){var f=a[g];h.test(f)?1===b&&(e=!0):f.toUpperCase()!==f.toLowerCase()&&(e?(f=f.toUpperCase(),e=!1):f=f.toLowerCase());c+=f}return c})};g.lower=function(c,e){return f(c,e,function(b,c,a){d.pcCheck(a,1,1);return d.toString(a[0]).toLowerCase()})};g.guid=function(c,e){return f(c,e,function(b,c,a){d.pcCheck(a,0,1);if(0<a.length)switch(d.toString(a[0]).toLowerCase()){case "digits":return d.generateUUID().replace("-","").replace("-","").replace("-","").replace("-",
"");case "digits-hyphen":return d.generateUUID();case "digits-hyphen-parentheses":return"("+d.generateUUID()+")"}return"{"+d.generateUUID()+"}"})};g.mid=function(c,e){return f(c,e,function(b,c,a){d.pcCheck(a,2,3);b=d.toNumber(a[1]);if(isNaN(b))return"";0>b&&(b=0);if(2===a.length)return d.toString(a[0]).substr(b);c=d.toNumber(a[2]);if(isNaN(c))return"";0>c&&(c=0);return d.toString(a[0]).substr(b,c)})};g.find=function(c,e){return f(c,e,function(b,c,a){d.pcCheck(a,2,3);b=0;if(2<a.length){b=d.toNumber(d.defaultUndefined(a[2],
0));if(isNaN(b))return-1;0>b&&(b=0)}return d.toString(a[1]).indexOf(d.toString(a[0]),b)})};g.left=function(c,e){return f(c,e,function(b,c,a){d.pcCheck(a,2,2);b=d.toNumber(a[1]);if(isNaN(b))return"";0>b&&(b=0);return d.toString(a[0]).substr(0,b)})};g.right=function(c,e){return f(c,e,function(b,c,a){d.pcCheck(a,2,2);b=d.toNumber(a[1]);if(isNaN(b))return"";0>b&&(b=0);return d.toString(a[0]).substr(-1*b,b)})};g.split=function(c,e){return f(c,e,function(b,c,a){d.pcCheck(a,2,4);b=d.toNumber(d.defaultUndefined(a[2],
-1));-1===b||null===b?b=d.toString(a[0]).split(d.toString(a[1])):(isNaN(b)&&(b=-1),-1>b&&(b=-1),b=d.toString(a[0]).split(d.toString(a[1]),b));a=d.defaultUndefined(a[3],!1);if(!1===d.isBoolean(a))throw Error("Invalid Parameter");if(!1===a)return b;a=[];for(c=0;c<b.length;c++)""!==b[c]&&void 0!==b[c]&&a.push(b[c]);return a})};g.text=function(c,e){return f(c,e,function(b,c,a){d.pcCheck(a,1,2);return d.toStringExplicit(a[0],a[1])})};g.concatenate=function(c,e){return f(c,e,function(b,c,a){b=[];if(1>a.length)return"";
if(d.isArray(a[0])){c=d.defaultUndefined(a[2],"");for(var e=0;e<a[0].length;e++)b[e]=d.toStringExplicit(a[0][e],c);return 1<a.length?b.join(a[1]):b.join("")}if(d.isImmutableArray(a[0])){c=d.defaultUndefined(a[2],"");for(e=0;e<a[0].length();e++)b[e]=d.toStringExplicit(a[0].get(e),c);return 1<a.length?b.join(a[1]):b.join("")}for(e=0;e<a.length;e++)b[e]=d.toStringExplicit(a[e]);return b.join("")})};g.reverse=function(c,e){return f(c,e,function(b,c,a){d.pcCheck(a,1,1);if(d.isArray(a[0]))return b=a[0].slice(0),
b.reverse(),b;if(d.isImmutableArray(a[0]))return b=a[0].toArray().slice(0),b.reverse(),b;throw Error("Invalid Parameter");})};g.replace=function(c,e){return f(c,e,function(b,c,a){d.pcCheck(a,3,4);b=d.toString(a[0]);c=d.toString(a[1]);var e=d.toString(a[2]);return(4===a.length?d.toBoolean(a[3]):1)?d.multiReplace(b,c,e):b.replace(c,e)})};g.domainname=function(c,e){return f(c,e,function(b,c,a){d.pcCheck(a,2,4);if(a[0]instanceof k)return a[0].domainValueLookup(d.toString(a[1]),a[2],void 0===a[3]?void 0:
d.toNumber(a[3]));throw Error("Invalid Parameter");})};g.domaincode=function(c,e){return f(c,e,function(b,c,a){d.pcCheck(a,3,4);if(a[0]instanceof k)return a[0].domainCodeLookup(d.toString(a[1]),a[2],void 0===a[3]?void 0:d.toNumber(a[3]));throw Error("Invalid Parameter");})}}});